---
# Regenerate with ./ss-application-quality-sonarqube-db-secrets.sh. Self-contained
# DB credentials shared between the bundled postgresql chart and sonarqube itself,
# so any value works as long as both sides use this same secret.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: application-quality-sonarqube-db-secrets
  namespace: application-quality-sonarqube
spec:
  encryptedData:
    password: AgBlpBWx9JsDLaqrAK50gJ5YVTwM+fL5qHg0h+dBqnA6J1ILMeTB+rG35nRfFlJCCNMcE2irPUFlajyaee7HZg1V5xtCsKxB3kFIGBQbQaCnKcwK3qzKuPxpmz1pDduQPkjj+G6zNIUIVX8jkO3af4NjWyN2vEiQY9SMD1z1ORTUPo+22JdPxjBPH2mfX0RIsVmRfFNYYcKlhL9EJN3FpqmS9zk5YuB6rqUHAFq/wF9ioxLAQwm/VqZkQ1gz+VZ+aiSpLtJfF5ey4FCBCKS6ULj3BhdG227GdvERM7YL3X9paaU6oVUS48xPlnAs0E22Quru66UUFhVqiOvSVuyLsxFM/bhGQrSifJUkWAQokMa5/1M9qXrXbIByJ0Xj1MT3OFTeYT6GzNaeGl5iJT6NqzIFxGN8ZBFPdPf065fiSHL5+D3Nq4zk8egznAQu5TWieXwJQVDdI5XZxKKTvcCZjneQ05JqMJ5YXtD0SmduHJ/3jKxOKdte6pZ0iPWfpOj0WY9De6IE9i5mDPVUm2EcHqtj9j96poMYxPHE6hSxJIPeJx9P7XqBPGX+B8krjxJRRuj/onVBBHhDWbn3iMhNBxV+SZQHCzHKDNP8KU3x1KiXDMxvQfQdW5lhQdVwD7Mvr5te8kI64NV6CQQ8lwfi3gpbcfLaZJpdKAaitxB4Axpr1Ch+M4xwQkyttQSirXtDOei2je5+HnyNqBvs/Z/yDGNiVjs0h0Fwpbr2wYtFbjJ44w==
    postgres-password: AgBqYhpgisTiE3justTHEYPY7njd/LpBBxPltjtd8xIfiZla/K5h5Igj4cBzMyjTZgJc/4PbVMgFb2NLOiLgE/x+EhPUVE5xQNmMISVFxVGzt7iDk6aMOPT2oVW6Odsv6knOKi2lmxujdAFjk0AKTLwnn9b67Hq0UzuawOPCmhgBq0y8fxNzb2Upt77nYdR4TXXoT1TxMziTGn8qolft/croc7QwemwQLEDgc1AAkyIV16m9ii56tCChCPsiah+zCncXmEL7+nFsJ/4DjFvINdYXOpQmtUTO75RMDXKc0w20fne/zYPNa6Htw3Ix5YLprrOl1WgMIsitsADDC9rApIR9VR+FChGIOt0LciJ7Dp8DIDMqeZC3dKnDsn+Fom48XHRmOcXxfCE3uRpuQtcWBndO/dj2Fsy11Y9ByRnV+o3j+hPvZfXimJEA3GO5vj6f2EA6M6PSUHhITAo2qA44YbMS93GIWO11t258nW2lTpj+baNgM4wJ1ukQHO9m/SeHWEl43Oyl3JeVRS5cFIGncVNKbkCJYaOnAUAEao69Wuhslgp2TosDvkfPWMYoJwMmr0zYsIACLmpaHC4nExRrMdoZjc1k/vfAPbFa076aYGMwTAp3SXiW29Fym9OMWVhwfHDlylb5Qbrrpysx0SGjxvFGpW9yMVi5hlxe3XDptQ6ijaBtctSZ/+/M2qZQCs7uJoEi0hj5nmS2Wurd/8vpkh78pm70rjHd3Cw6n0WIchEtHw==
  template:
    metadata:
      creationTimestamp: null
      name: application-quality-sonarqube-db-secrets
      namespace: application-quality-sonarqube
