---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: application-quality-sonarqube-db-secrets
  namespace: application-quality-sonarqube
spec:
  encryptedData:
    password: AgAk53mMVomFC3ADJoiBWVuVRp2wNuMg6eyiQprHqP+JAlI5cTXIgjNyl/NFFS0knVsHH3aoWGgWXuIAtPtU5RN0oigl5ehZYOVlD+MvaV03f8yVPLj/oQ3aQkbhpVizyzRbtrTIHch1AciXJzg+P0cK0fkwm0ObJv12n5FGZHLifXniRqXyVDOws8hT2bKQyGWmmDXQapGtio1AU8/9MA1t4JMgzemJ9IqXBg3Vi7mSJf7IG6zJkQvxWU9wEujP4+g7+RLvAGzIYpGu9S+hfKg2UgT2+yIuumfs61qLvXEZoecz00QL26uVyrzPcbTzJcoX33Zf0GI8/4nWtvtMrwj3TvOnN45rrw4wwnTeDr3ioeC0RfGT2BOLRSufBYrAcC4nFvjvFnmc0p0Bj7ZwmKni/ekj9VOdaZRB4XPzqkvS8avtmZyWy1dt+LQZCPv3tklYTLpxPb7B70X5V9J45SDPOX8eAB7zoobtsuaK34PkH7D71biDH9YYlbPTzEmYPWx1xSes+Jrti21uY52ftZxoK2LyiBTxbJRTZYAB4n/ptRPMI2TZXDCx1rUKIrBSH3GIi/ElcUKdIDYnFKc1qezpFa96MOVsSLxa9pwlDdwtrXMF/EruB3UETa+rkoZkCKu0ZbGdC5+3UM92V9wygAftcHDFwRqJROPrMKRuedKivevxO1EFKFZXCMO2YdH+RjMW57Zr3suL8flVszDkyOuohbeDgXL5jSmJJMSN1XJ8QFDo6+yGOb8qpsLAJOLU/uY=
    postgres-password: AgAHoDmQRAsc1AcLFx2Bc+VWwYSxwydX2WnpcCaSZG9UQmSig6+K6OOuJ0wdhDnOSLFisJ/GEtqaeP15BzMbhmJ/MpCu+EW2evO2bImdDU2NHbZnmIshdZ4wCEH9fQFLETWoJKU7F+9wC4rJF6lcTKK6dbstiPxs0lWUvwb0mj3j3ATjNJJtCCoinIGaoo5tl8dyN4ijj3gwSjffBwHCSY40k/URaoAMNaWvtNvgW4oiy9C+kiNLU9JbUnafP9me+exbPazweT9z/5TI2qvHecivy4dW6EGr4vS8/M3RwXUOa3ZFLyLbheg50eTFVoIuu9Z5mWgKJ/OV9WBrp6oDK0QIkjzTz6OXhl8Me8NCulmTralrmdWtbTUDFukCuqNs+7dkHVCMyUuFT7/PkoekWQ5WNP+0CY++NQt6tw6tnKQHU3sUI4kfx5kWp3vRzbxCeTLXR6utBV95gPPJJihYYUbjjPqMS+pOKOAdxdBa2VkYEtjac3+qoYsAh5g10gVWGTFP38INIMTC+b7W6OcJ8V7IGAiqbQoSd5Yx2Go0s4sZYAZovh3qm7etCTZmZ9c5jqbpJYSA9BiGA2EaotTkQTI0wZBPzZDpwdgrw7IWJOi7mxMm3BuPWESMRF0KJWJKgIrqVBknzvMR4hgQ+w72G2gbsGm+M6PKWknCyyR1R44jRRIqhLTEoAc4w5q4DAEIjljTgrGJAKWRWKBeNxNmNqRy/8a8F+iVCX74dhKqBb4/MJajaf4CEVdcCZri3PUutFk=
  template:
    metadata:
      creationTimestamp: null
      name: application-quality-sonarqube-db-secrets
      namespace: application-quality-sonarqube
