---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: application-quality-sonarqube-monitoring-passcode
  namespace: application-quality-sonarqube
spec:
  encryptedData:
    passcode: AgBYrPsTIogx9DiEJ//lKbQRr2/j4HJnr0gNG3HR+RaJoNirsYyzgqfi2p+InYu9HUbuqMC6xepmTpn/QQNZnJbLLYGIOBVAdGdVZeXd+kFdzqtYH7D0SfmmYfGrvp+iqXMyfwIlKATou36ZBSM0cUh8VPck5sYUsvzyJ9C1HACfcAf9sFcsJYW1JJZhY7FvKQbSmhdBnxU8XiXL3cy9ocDrjupBEiWhoGMDrVrvK0XGo/EGb8eTGOuV2Jr3IbXmRWvOtO0gaKmglfeGsPqv6uE+Dn0kYEqzXxHXP5ltIDnmwLCu4lEiXcoSPIsGfo4rQzl17zk/8vF5sv/T92gwWfW2jH4t24V5OcgGKrd3V6VmxGJXqv9gFnwj3Gh2mhRy7Vk4hB79Bz88v6Um2GnCg6dBUo8awlLS8BiB/7qs5RmonI9j/BsFP5aFcvekSby03gaMPbD8lDCQNH6GhojDM0zZN1bKjEc5WMNeGHkuHEAzBOiuohZaIsMiq/VQszWmYZU6iDgHmbXOxe//zcrjnZWISAC8i9cTpdeYRAorr4eOI9wBEua1xkuUSbGil61JHbYZZUjPhrUAiCQ2WXF1a1gA3cUS5ljfaLV2JFpR/F21TtN37LdI9bMyYU4+wVp8H8/sggkJ58jesdGrhFiRmUyLC4n9QvEvsj/jbZNzqhNgVfHNAfdxfEB0qm6M5Fw9KQvQgM71l6ZKCkPVcLkUrwcgaxvXrR+qpWfwXv2GUI1J9YqEszQf+QV5N183prB6beQ=
  template:
    metadata:
      creationTimestamp: null
      name: application-quality-sonarqube-monitoring-passcode
      namespace: application-quality-sonarqube
