---
# Regenerate with ./ss-application-quality-sonarqube-monitoring-passcode.sh. Only
# consumed by sonarqube itself (its /api/monitoring/metrics endpoint), so any value works.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: application-quality-sonarqube-monitoring-passcode
  namespace: application-quality-sonarqube
spec:
  encryptedData:
    passcode: AgBHewYVcdHVsfUFZ+rQF4CMh8nuYA/EDSydAfBlMtcVu1b7+XONk7/W6Mgux5/Umas9ysVXFrZrcPx/Tv1QdPMO5wLx3OhBWOado9/zot+WB5tWlqd7GOU877Js7/QHdwjW46X3DmBZrRry+WIHrliCekmYZ6lkj7nZt3tgyQYDCmmXmMj7oE+w39N66MVhIX3Y+8bbhwv1KqCfIxc1C3Vu9aLUenrzm2IRe/vd7eifjstnsKf6PhxyiHUSq8hzUMJDN6E6ayLNl7DI9fkNtN3ZGYHa0VwxYhyXG8u/v1Yb9EPLE8ftjElVf/txHPdGMuh5TwRbjDhmRUE00tpkdR4Fy2sr/PO4h2Lrqvin5lnunwY5yju2s1EbBJ4+M8fJ6AkplQLi5XJ8FjR/abU0jwcwlh08XMqxoiTvMH0DxsrApfq7DeZE9IuYeUy2al2B/qGP5N+gJJBdjutTsMt6bwLBRaEKAVM2EXoZoFvmqFKeAAuhn7t1KtUAAup9W/wtjsruSegYvmNg/Wm2VLf6bhVLa8/D3GMObt/y6P72CNtObMH2OpW/3+/AbuBa5XK7QQyYdZoSuKRh4nb0HQnJZlZVjdhdXY0FfVeTU4axTcvywxheKwIZBdDMDcu3TTT+fUy6sfxovAtMABNVxu8VyLE7ckt8N2Aw5tpBv/HxGxuJASNqboeed1TwmxpXjP8GlY98i7eva+LhSRGpI5JULui/UcQGV7uZwT3f9GNRw6f8vg==
  template:
    metadata:
      creationTimestamp: null
      name: application-quality-sonarqube-monitoring-passcode
      namespace: application-quality-sonarqube
