apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zoo-project-dru-core
  namespace: argocd
  labels:
    eoepca/app-name: zoo-project-dru
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://zoo-project.github.io/charts/
      chart: zoo-project-dru
      targetRevision: 0.2.6
      helm:
        releaseName: zoo-project-dru
        valueFiles:
          - $values/argocd/eoepca/zoo-dru/parts/values-zoo.yaml
          - $values/argocd/eoepca/zoo-dru/parts/values-stageout.yaml
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: zoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
