apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: zoo
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: zoo-oidc
  forProvider:
    realmId: eoepca
    name: zoo
    accessType: CONFIDENTIAL
    clientId: zoo
    enabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    fullScopeAllowed: true
    serviceAccountsEnabled: true
    useRefreshTokens: true
    rootUrl: https://zoostd.develop-v2.eoepca.org
    validRedirectUris:
      - https://zoostd.develop-v2.eoepca.org/*
      - https://zoostd-open.develop-v2.eoepca.org/*
      - https://webuistd.develop-v2.eoepca.org/*
    webOrigins:
      - https://zoostd.develop-v2.eoepca.org
      - https://zoostd-open.develop-v2.eoepca.org
      - https://webuistd.develop-v2.eoepca.org
    authorization:
      - policyEnforcementMode: ENFORCING
        decisionStrategy: UNANIMOUS
        keepDefaults: true
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: zoo-webapp
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: zoo-webapp-oidc
  forProvider:
    realmId: eoepca
    name: zoo-webapp
    accessType: CONFIDENTIAL
    clientId: zoo-webapp
    enabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    useRefreshTokens: true
    rootUrl: https://webuistd.develop-v2.eoepca.org
    validRedirectUris:
      - https://webuistd.develop-v2.eoepca.org/*
    webOrigins:
      - https://webuistd.develop-v2.eoepca.org
---
# crossplane resources
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationResource
metadata:
  name: zoo-alice-home
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: alice-home
    uris:
      - /alice/*
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationResource
metadata:
  name: zoo-bob-home
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: bob-home
    uris:
      - /bob/*
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationResource
metadata:
  name: zoo-eric-home
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: eric-home
    uris:
      - /eric/*
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationResource
metadata:
  name: zoo-eoepcauser-home
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: eoepcauser
    uris:
      - /eoepcauser/*
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
---
# crossplane policies
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientUserPolicy
metadata:
  name: zoo-alice-policy
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: alice-policy
    logic: POSITIVE
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    usersRefs:
      - name: alice
        policy:
          resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientUserPolicy
metadata:
  name: zoo-bob-policy
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: bob-policy
    logic: POSITIVE
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    usersRefs:
      - name: bob
        policy:
          resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientUserPolicy
metadata:
  name: zoo-eric-policy
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: eric-policy
    logic: POSITIVE
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    usersRefs:
      - name: eric
        policy:
          resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientUserPolicy
metadata:
  name: zoo-eoepcauser-policy
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: eoepcauser
    logic: POSITIVE
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    usersRefs:
      # references the shared eoepcauser account declared in argocd/eoepca/iam/parts/eoepca-user.yaml
      - name: eoepca-user
        policy:
          resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationPermission
metadata:
  name: zoo-alice-access
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: alice-access
    type: resource
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    resources:
      - alice-home
    policies:
      - alice-policy
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationPermission
metadata:
  name: zoo-bob-access
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: bob-access
    type: resource
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    resources:
      - bob-home
    policies:
      - bob-policy
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationPermission
metadata:
  name: zoo-eric-access
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: eric-access
    type: resource
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    resources:
      - eric-home
    policies:
      - eric-policy
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationPermission
metadata:
  name: zoo-eoepcauser-access
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: eoepcauser-access
    type: resource
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    resources:
      - eoepcauser
    policies:
      - eoepcauser
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationResource
metadata:
  name: zoo-default-resource
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: default-resource
    uris:
      - /*
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientUserPolicy
metadata:
  name: zoo-default-policy
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: default-policy
    logic: POSITIVE
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    usersRefs:
      - name: alice
        policy:
          resolution: Required
      - name: bob
        policy:
          resolution: Required
      - name: eric
        policy:
          resolution: Required
      - name: eoepca-user
        policy:
          resolution: Required
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientAuthorizationPermission
metadata:
  name: zoo-default-access
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: default-access
    type: resource
    decisionStrategy: UNANIMOUS
    resourceServerIdRef:
      name: zoo
      policy:
        resolution: Required
    resources:
      - default-resource
    policies:
      - default-policy
