cookiecutter:
  templateUrl: https://github.com/gfenoy/eoepca-proc-service-template.git
  templateBranch: feature/zoo-template-common
zoo:
  openapi:
    enabled: true
zoofpm:
  image:
    tag: eoepca-f0080845011eb3fad53f49ee577a2e61dd8331f0
zookernel:
  env:
    ZOO_OUTPUT_FORMAT: "stac-collection"
  image:
    tag: eoepca-f0080845011eb3fad53f49ee577a2e61dd8331f0
customConfig:
  main:
    eoepca: |-
      domain=develop-v2.eoepca.org
      workspace_url=https://workspace-api.develop-v2.eoepca.org
      workspace_prefix=ws
      workspace_catalog_register=false
workflow:
  defaultMaxRam: "1024"
  defaultMaxCores: "2"
  extraEnvFrom:
    - secretRef:
        name: zoo-workflow-env
  inputs:
    STAGEOUT_AWS_SERVICEURL: https://minio.develop-v2.eoepca.org
    STAGEOUT_AWS_ACCESS_KEY_ID: eoepca
    STAGEOUT_AWS_SECRET_ACCESS_KEY: changeme
    STAGEOUT_AWS_REGION: RegionOne
    STAGEOUT_OUTPUT: eoepca
  nodeSelector: {}
  storageClass: managed-nfs-storage-retain
ingress:
  enabled: false
  hosturl: https://zoostd.develop-v2.eoepca.org
  annotations:
    kubernetes.io/ingress.class: apisix
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    argocd.argoproj.io/ignore-healthcheck: "true"
  hosts:
  - host: zoostd.develop-v2.eoepca.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - zoostd.develop-v2.eoepca.org
    secretName: zoostd-tls
persistence:
  procServicesStorageClass: managed-nfs-storage-retain
  storageClass: managed-nfs-storage-retain
  tmpStorageClass: managed-nfs-storage
postgresql:
  persistence:
    storageClass: managed-nfs-storage-retain
rabbitmq:
  autoSetup:
    enabled: false
  persistence:
    storageClass: managed-nfs-storage-retain
iam:
  enabled: true
  openIdConnectUrl: https://develop-v2.eoepca.org/iam/auth/realms/eoepca/.well-known/openid-configuration
  realm: eoepca
  issuer: https://develop-v2.eoepca.org/iam/auth/realms/eoepca
  audience: account
documentation:
  enabled: true
dask:
  enabled: true
webui:
  enabled: true
  url: https://webuistd.develop-v2.eoepca.org
  port: 3000
  image:
    pullPolicy: Always
  oidc:
    issuer: "https://develop-v2.eoepca.org/iam/auth/realms/eoepca"
    authVerifyJwksUri: https://develop-v2.eoepca.org/iam/auth/realms/eoepca/protocol/openid-connect/certs
    clientId: zoo
    clientSecret: C8tV4ijxXVh3Mdcubsedvl1e9uWWyPJ4
