cookiecutter:
  templateUrl: https://github.com/gfenoy/eoepca-proc-service-template.git
  templateBranch: feature/zoo-template-common
zoo:
  openapi:
    enabled: true
zoofpm:
  image:
    tag: eoepca-ad6563d64c564268778263ad41fed9f9d18d07ca
zookernel:
  env:
    ZOO_OUTPUT_FORMAT: "stac-collection"
  image:
    tag: eoepca-ad6563d64c564268778263ad41fed9f9d18d07ca
customConfig:
  main:
    eoepca: |-
      domain=develop.eoepca.org
      workspace_url=https://workspace-api.develop.eoepca.org
      workspace_prefix=ws
      workspace_catalog_register=false
workflow:
  defaultMaxRam: "1024"
  defaultMaxCores: "2"
  extraEnvFrom:
    - secretRef:
        name: zoo-workflow-env
  inputs:
    STAGEOUT_AWS_SERVICEURL: https://minio.develop.eoepca.org
    STAGEOUT_AWS_ACCESS_KEY_ID: eoepca
    STAGEOUT_AWS_SECRET_ACCESS_KEY: changeme
    STAGEOUT_AWS_REGION: RegionOne
    STAGEOUT_OUTPUT: eoepca
  nodeSelector: {}
  storageClass: managed-nfs-storage-retain
ingress:
  enabled: false
  hosturl: https://zoostd.develop.eoepca.org
  annotations:
    kubernetes.io/ingress.class: apisix
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    argocd.argoproj.io/ignore-healthcheck: "true"
  hosts:
  - host: zoostd.develop.eoepca.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - zoostd.develop.eoepca.org
    secretName: zoostd-tls
persistence:
  procServicesStorageClass: managed-nfs-storage-retain
  storageClass: managed-nfs-storage-retain
  tmpStorageClass: managed-nfs-storage
postgresql:
  persistence:
    storageClass: managed-nfs-storage-retain
rabbitmq:
  autoSetup:
    enabled: false
  persistence:
    storageClass: managed-nfs-storage-retain
iam:
  enabled: true
  openIdConnectUrl: https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration
  realm: eoepca
documentation:
  enabled: true
dask:
  enabled: true
webui:
  enabled: true
  image:
    tag: 0.1.3
  url: https://webuistd.develop.eoepca.org
  port: 3000
  oidc:
    issuer: "https://iam-auth.develop.eoepca.org/realms/eoepca"
    authVerifyJwksUri: https://iam-auth.develop.eoepca.org/realms/eoepca/protocol/openid-connect/certs
    clientId: zoo
    clientSecret: Fsw9DtGQ52lje15lQtPC8CDxhpwqE8Di
