apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: keep
  namespace: operations
  labels:
    release: kube-prometheus-stack
spec:
  receivers:
    - name: "null"
    - name: keep
      webhookConfigs:
        - sendResolved: true
          url: http://keep-alertmanager-relay.operations.svc.cluster.local/alerts/event/prometheus
  route:
    groupBy:
      - alertname
    groupInterval: 15s
    groupWait: 15s
    receiver: keep
    repeatInterval: 1m
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: KubeJobFailed
            matchType: =
      - receiver: "null"
        matchers:
          - name: alertname
            value: KubePodNotReady
            matchType: =
