apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: keep
  namespace: ingress-apisix
  labels:
    release: kube-prometheus-stack
spec:
  receivers:
    - name: keep
      webhookConfigs:
        - sendResolved: true
          url: http://keep-alertmanager-relay.operations.svc.cluster.local/alerts/event/prometheus
  route:
    groupBy:
      - alertname
    groupInterval: 15s
    groupWait: 15s
    receiver: keep
    repeatInterval: 1m
