apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: alerting
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  writeConnectionSecretToRef:
    name: alerting-oidc
    namespace: operations
  forProvider:
    realmId: eoepca
    name: alerting
    accessType: CONFIDENTIAL
    clientId: alerting
    enabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    useRefreshTokens: true
    rootUrl: https://alerting.develop.eoepca.org
    validRedirectUris:
      - https://alerting.develop.eoepca.org/oauth2/callback
    validPostLogoutRedirectUris:
      - https://alerting.develop.eoepca.org/
      - https://alerting.develop.eoepca.org/oauth2/*
    webOrigins:
      - https://alerting.develop.eoepca.org
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: alerting-keep-admin
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: keep_admin
    description: Admin access to alerting through oauth2-proxy
    clientIdRef:
      name: alerting
      policy:
        resolution: Required
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: alerting-keep-noc
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: keep_noc
    description: NOC access to alerting through oauth2-proxy
    clientIdRef:
      name: alerting
      policy:
        resolution: Required
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: alerting-client-roles-groups
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    clientIdRef:
      name: alerting
      policy:
        resolution: Required
    realmId: eoepca
    protocol: openid-connect
    protocolMapper: oidc-usermodel-client-role-mapper
    name: alerting-client-roles-groups
    config:
      "access.token.claim": "true"
      "id.token.claim": "true"
      "userinfo.token.claim": "true"
      "multivalued": "true"
      "claim.name": "groups"
      "jsonType.label": "String"
      "usermodel.clientRoleMapping.clientId": "alerting"
