
resources:
  - app-zoo-dru-core.yaml
  - ingress-zoo.yaml
  - ss-zoo-workflow-env.yaml

patches:
  - target: {group: argoproj.io, kind: Application}
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {argocd.argoproj.io/sync-wave: "0"}
  - target: {group: ^(apisix.apache.org|cert-manager.io)$}
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "10"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
