apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: develop
    path: argocd/infra/minio-as-chart/app-minio

    helm:
      releaseName: minio
      valuesObject:
        minio:
          existingSecret: minio-auth
          replicas: 2
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
            path: /
            hosts:
              - minio.guide.svc.rconway.uk
            tls:
              - secretName: minio-tls
                hosts:
                  - minio.guide.svc.rconway.uk
          consoleIngress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
            path: /
            hosts:
              - console.minio.guide.svc.rconway.uk
            tls:
            - secretName: minio-console-tls
              hosts:
                - console.minio.guide.svc.rconway.uk
          resources:
            requests:
              memory: 1Gi
          persistence:
            storageClass: standard
            size: 50Gi
          buckets:
            - name: eoepca
            - name: cache-bucket

  destination:
    name: in-cluster
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
