# Wildcard certificate for preliminary APISIX ingress *.rke2.deploybox.co.uk
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: apx-all-tls
  namespace: ingress-apisix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  ingressClassName: apisix
  hosts:
    - "*.rke2.deploybox.co.uk"
  secret:
    name: apx-all-tls
    namespace: ingress-apisix
