# Wildcard certificate for preliminary APISIX ingress *.develop.eoepca.org
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: apx-all-tls
  namespace: ingress-apisix
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
spec:
  ingressClassName: apisix
  hosts:
    - "*.develop.eoepca.org"
  secret:
    name: apx-all-tls
    namespace: ingress-apisix
