apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-crds
  namespace: argocd
  labels:
    eoepca/app-name: apisix
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: eoepca
  source:
    repoURL: https://github.com/apache/apisix-helm-chart.git
    targetRevision: apisix-2.13.0
    path: charts/apisix-ingress-controller/crds
    directory:
      include: apisixic-crds.yaml
  destination:
    name: in-cluster
    namespace: ingress-apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
