apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-core
  namespace: argocd
  labels:
    eoepca/app-name: apisix
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://apache.github.io/apisix-helm-chart
      chart: apisix
      targetRevision: 2.13.0
      helm:
        releaseName: apisix
        valueFiles:
          - $values/argocd/infra/apisix/parts/values/apisix-values.yaml
        skipCrds: false
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: rke2-argocd-sync-wave
      ref: values

  destination:
    name: in-cluster
    namespace: ingress-apisix
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.versions[].additionalPrinterColumns[].priority | select(. == 0)
    - group: ""
      kind: Secret
      name: apisix-ingress-controller-webhook-cert
      namespace: ingress-apisix
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: apisix-ingress-controller-webhook
      namespace: ingress-apisix
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
#    - group: ""
#      kind: Secret
#      name: apisix-etcd-jwt-token
#      namespace: ingress-apisix
#      jsonPointers:
#        - /data
#    - group: apps
#      kind: StatefulSet
#      name: apisix-etcd
#      namespace: ingress-apisix
#      jqPathExpressions:
#        - '.spec.template.metadata.annotations["checksum/token-secret"]'
  syncPolicy:
    automated:
      prune: true
      # selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
