# Wildcard certificate for preliminary APISIX ingress *.rke2.deploybox.co.uk
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apx-main-tls
  namespace: ingress-apisix
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  secretName: apx-main-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - "rke2.deploybox.co.uk"
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
