
resources:
  - app-apisix-core.yaml
  - apisixtls-apx-all.yaml
  - cert-apx-all.yaml
  - apisixglobalrule-redirect-to-tls.yaml
  - apisixglobalrule-tls-port-correction.yaml
  - apisixglobalrule-prometheus.yaml
  - servicemonitor-apisix.yaml
  - servicemonitor-apisix-ingress-controller.yaml
