apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apisix-ingress-controller
  namespace: ingress-apisix
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: ingress-controller
