apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: monitoring
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  writeConnectionSecretToRef:
    name: monitoring-oidc
    namespace: operations
  forProvider:
    realmId: eoepca
    name: monitoring
    accessType: CONFIDENTIAL
    clientId: monitoring
    enabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    useRefreshTokens: true
    rootUrl: https://monitoring.rke2.deploybox.co.uk
    validRedirectUris:
      - https://monitoring.rke2.deploybox.co.uk/login/generic_oauth
    validPostLogoutRedirectUris:
      - https://monitoring.rke2.deploybox.co.uk/
      - https://monitoring.rke2.deploybox.co.uk/login
    webOrigins:
      - https://monitoring.rke2.deploybox.co.uk
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: grafana-admin
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: grafana_admin
    description: Admin access for monitoring stack
    clientIdRef:
      name: monitoring
      policy:
        resolution: Required
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: grafana-editor
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: grafana_editor
    description: Editor access for monitoring stack
    clientIdRef:
      name: monitoring
      policy:
        resolution: Required
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: grafana-viewer
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: grafana_viewer
    description: Viewer access for monitoring stack
    clientIdRef:
      name: monitoring
      policy:
        resolution: Required
