apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: monitoring
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: monitoring-oidc
  forProvider:
    realmId: eoepca
    name: monitoring
    accessType: CONFIDENTIAL
    clientId: monitoring
    enabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    useRefreshTokens: true
    rootUrl: https://monitoring.develop-v2.eoepca.org
    validRedirectUris:
      - https://monitoring.develop-v2.eoepca.org/login/generic_oauth
    validPostLogoutRedirectUris:
      - https://monitoring.develop-v2.eoepca.org/
      - https://monitoring.develop-v2.eoepca.org/login
    webOrigins:
      - https://monitoring.develop-v2.eoepca.org
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: grafana-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: grafana_admin
    description: Admin access for monitoring stack
    clientIdRef:
      name: monitoring
      policy:
        resolution: Required
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: grafana-editor
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: grafana_editor
    description: Editor access for monitoring stack
    clientIdRef:
      name: monitoring
      policy:
        resolution: Required
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: grafana-viewer
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: grafana_viewer
    description: Viewer access for monitoring stack
    clientIdRef:
      name: monitoring
      policy:
        resolution: Required
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: eoepca-offline-access
  namespace: iam-management
  annotations:
    crossplane.io/external-name: eoepca/offline_access
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: offline_access
  managementPolicies:
    - Observe
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: monitoring-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: monitoring-admin
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: monitoring-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: monitoring-admin
      policy:
        resolution: Required
    roleIdsRefs:
      - name: grafana-admin
        policy:
          resolution: Required
      - name: eoepca-offline-access
        policy:
          resolution: Required
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: monitoring-admin-members
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: monitoring-admin
      policy:
        resolution: Required
    members:
      - eoepca-admin
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: monitoring-editor
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: monitoring-editor
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: monitoring-editor
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: monitoring-editor
      policy:
        resolution: Required
    roleIdsRefs:
      - name: grafana-editor
        policy:
          resolution: Required
      - name: eoepca-offline-access
        policy:
          resolution: Required
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: monitoring-editor-members
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: monitoring-editor
      policy:
        resolution: Required
    members:
      - eoepcauser
