apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: monitoring
  namespace: operations
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  ingressClassName: apisix
  http:
    - name: grafana
      match:
        hosts:
          - monitoring.rke2.deploybox.co.uk
        paths:
          - /
          - /*
      backends:
        - serviceName: kube-prometheus-stack-grafana
          servicePort: 80
