---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-s3-credentials
  namespace: operations
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBBMVFKM0kgtMCOXWN9yq3tgOBWCbr/9nIfdK/GaemTQBbCXQMg9I3FmSLwmumUmo7pOg1yFqzUzJkoKIdumNlQTlsOukPLJWh2rQSf7bKVuSiNcZucdzxVrlJQDXlT7bt2eqxtGfBfxB8K1ptDUIIi6/J8vqeeadFjC+1ugWUiWmhCeYIXTjuVkjF0hvZHptL+WA8KUB79zGp7xtG1ce58slBegUqT2aSkBuICvL6HhCeJmF+hqJw7URwI7srI5p8X0yMSgTa+L97kQlrdlEs6r21HNb1qD7hwX9edTKWHWfBZmZv98PwWJiJEjWVzMKrY/MzhkUleifACNuL5nf4lttUEhIW9njhVkNx1y7+65Tm/vzOnuB3JJ3AAC61z1tKBb06jaT+CEEcUqY2B00LPuxKHkSyEVQxBWvJYxTg3WCMz4fXZj3OG+yp/PSkqYXLO94/nhtwEjMqSRG3zl4f5wS4FzV28fywQQn0o6gL2xNqZQ7GDgNdAHzUt2QDi3pCR+kPf8DWAoJdKiHmn3jPSAC6HkIHOnlUlyj7U3aUa1f01FX6PQlSxXR/ccl8vJ3rJ/ykY30fGgWEat+Trg2kIqfuQd5QHctmjYq9Y1t1rOh5OheOw5APoQItJBe4rg5kSmKYKuLfwAEsDNCQLOeZX2SAW/eR5OjNdaaHwLpvc7+iwrptkdkH1ePhDHkhp+ti6iqx5jpU=
    AWS_SECRET_ACCESS_KEY: AgA4S5O7n96tmRF0S82RrPsyVA4GygBqudUOFitfypHisGpyj4gI34WeKaj8FU1VQKs90RbdYce4m+gqTb9CmJfylNfODsEDD4d6iLCkcIosAWUDRnJt18yjbXn5RfBD/t8YDQxCZUoyU3yf5rkP/Y4Hhvt+7KVsaD4UfyxeKu6YT4tngWYaCza1D90SvnPunkhPiy86ucGXEM8aVaapdxvepD/N1jPg8JJqf/h4ELhFmHMhE0eyGw9fQLMV9PPeZGjO7psj1wrVwODXjHVcLW6WQMXtg736XBuav2/HTXHMjhJZuEjmNfdnfXIOFzWP1rTGCjG8tcRe1lyD+AFmXbRmGErHzoP1zsaJuLI2JMlrgbwVhwjjdA+2Kt6iG7XxUjSXz5fmvwDsbc44BSoRyHOhoC5Dwk34VIwS1ZcUpBNK7FUcE4QnujkTL6N2mNoRUVTTmvU+SrgUGhsnUEln41L9L4Qxc8JVcTZteEUVF/Ev8V2ni0zTqh/QHG0MC/dSyMABddeeAmiFxrzenIqiKYDvalJRgdgde0RU7rfc/pC7oqM86qZAO05Gd1Oj8GAfJhfNw1T2Qre2h3GiBqelcUHFf+7Qlt62dYs6tcQNHVDzm3Pcgkz7CJoyK5QjZ0ON/fwkMg4pOqP+i1Z1XHYjXdkJKJTbRwpj9k3qIvw4z8K6qJ8UyS4mRs2TZYhHESR3g1NKculfP2Tunw==
  template:
    metadata:
      creationTimestamp: null
      name: loki-s3-credentials
      namespace: operations
    type: Opaque
