apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: resource-health-route
  namespace: resource-health
spec:
  ingressClassName: apisix
  http:
  - name: resource-health-web-route
    match:
      hosts:
        - resource-health.rke2.deploybox.co.uk
      paths:
        - /
        - /_next/*
        - /.apisix/*
        - /check/*
        - /login
        - /login/*
        - /logout
    backends:
      - serviceName: resource-health-web
        servicePort: 80
    plugin_config_name: resource-health-route-browser-auth-plugin
  - name: resource-health-telemetry-api-route
    match:
      hosts:
        - resource-health.rke2.deploybox.co.uk
      paths:
        - /api/telemetry
        - /api/telemetry/*
    backends:
      - serviceName: resource-health-telemetry-api
        servicePort: 8080
    plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/api/telemetry/?(.*)","/$1"]
    plugin_config_name: resource-health-route-browser-auth-plugin
  - name: resource-health-check-api-route
    match:
      hosts:
        - resource-health.rke2.deploybox.co.uk
      paths:
        - /api/healthchecks
        - /api/healthchecks/*
    backends:
      - serviceName: resource-health-check-api
        servicePort: 8000
    plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/api/healthchecks/?(.*)","/$1"]
    plugin_config_name: resource-health-route-browser-auth-plugin
  - name: resource-health-dashboards-route
    match:
      hosts:
        - resource-health.rke2.deploybox.co.uk
      paths:
        - /dashboards
        - /dashboards/*
    backends:
      - serviceName: resource-health-opensearch-dashboards
        servicePort: 5601
    plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/dashboards/?(.*)","/$1"]
    plugin_config_name: resource-health-route-browser-auth-plugin