nameOverride: "eoapi-stac-manager"

ingress:
  enabled: false
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "4"
image:
  tag: latest
  pullPolicy: Always

publicUrl: https://eoapi.develop.eoepca.org/manager
stacApi: https://eoapi.develop.eoepca.org/stac/
primaryColor: "#005ACD"
secondaryColor: "#048A81"

oidc:
  providerUrl: https://iam-auth.develop.eoepca.org
  clientId: eoapi
  realm: eoepca
