ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: eoapi.develop.eoepca.org
  tls:
    enabled: true
    certManager: false
    secretName: eoapi-tls

db:
  enabled: false
  storageClassName: managed-nfs-storage-retain
  accessModes:
    - ReadWriteMany
  settings:
    secrets:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGUSER: username
      PGPASSWORD: password
      PGDATA: /data/pgdata

postgrescluster:
  enabled: true
  postgresVersion: 16
  postGISVersion: 3.4
  pgBouncerReplicas: 1
  monitoring: false
  instances:
  - name: eoapi
    replicas: 1
    dataVolumeClaimSpec:
      storageClassName: managed-nfs-storage-retain
      accessModes:
      - "ReadWriteMany"
      resources:
        requests:
          storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: managed-nfs-storage-retain
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi

pgstacBootstrap:
  enabled: true
  settings:
    envVars:
      KEEP_ALIVE: "true"

raster:
  enabled: true
  settings:
    resources:
      requests:
        memory: "3072Mi"
stac:
  enabled: true
  settings:
    resources:
      limits:
        cpu: "1280m"
        memory: "1536Mi"
      requests:
        cpu: "512m"
vector:
  enabled: true
  settings:
    resources:
      limits:
        memory: "1536Mi"
      requests:
        memory: "1024Mi"
    envVars:
      # needs to on so we can call /refresh for integration tests
      TIPG_DEBUG: "True"
      TIPG_CATALOG_TTL: "30"
