fullnameOverride: "eoapi-geoparquet-export"

image:
  tag: "0.2"

stacApiUrl: "https://eoapi.rke2.deploybox.co.uk/stac"

database:
  existingSecret: "default-pguser-eoapi"

storage:
  outputPath: "s3://eoapi-geoparquet/geoparquet"
  existingSecret: "data-access"
  endpoint: "https://eodata.cloudferro.com"

exportConfig:
  exportAll: true
