nameOverride: "eoapi-stac-manager"

ingress:
  enabled: false
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "4"

publicUrl: https://eoapi.develop-v2.eoepca.org/manager
stacApi: https://eoapi.develop-v2.eoepca.org/stac
stacBrowser: https://eoapi.develop-v2.eoepca.org/browser
primaryColor: "#005ACD"
secondaryColor: "#048A81"
appTitle: "EOEPCA+ STAC Manager"
appDescription: "Manage STAC collections and items on the EOEPCA+ platform"

oidc:
  authority: https://iam-auth.develop-v2.eoepca.org/realms/eoepca
  clientId: eoapi

volumes:
  - name: branding
    configMap:
      name: stac-manager-branding
volumeMounts:
  - name: branding
    mountPath: /app/packages/client/dist/meta
