fullnameOverride: "eoapi-geoparquet-export"

image:
  tag: "0.2"

stacApiUrl: "https://eoapi.develop.eoepca.org/stac"

database:
  existingSecret: "default-pguser-eoapi"

storage:
  outputPath: "s3://geoparquet-exporter/geoparquet"
  existingSecret: "geoparquet-exporter-s3-credentials"
  endpoint: "https://minio.develop.eoepca.org"

exportConfig:
  exportAll: true
