ingress:
  enabled: false

postgresql:
  type: "external-secret"
  external:
    existingSecret:
      name: "default-pguser-eoapi"
      keys:
        username: "user"
        password: "password"
        host: "host"
        port: "port"
        database: "dbname"

postgrescluster:
  enabled: false

pgstacBootstrap:
  enabled: true
  settings:
    envVars:
      KEEP_ALIVE: "false"

raster:
  enabled: true
  ingress:
    path: "/raster"
  overrideRootPath: "/"
  image:
    tag: "1.4.0"
  settings:
    envVars:
      AWS_S3_ENDPOINT: "eodata.cloudferro.com"
      AWS_VIRTUAL_HOSTING: "FALSE"
    envSecrets:
      - data-access
    resources:
      requests:
        memory: "3072Mi"

multidim:
  enabled: true
  ingress:
    path: "/multidim"
  overrideRootPath: "/"
  settings:
    envSecrets:
          - data-access
    resources:
      requests:
        memory: "1024Mi"
stac:
  enabled: true
  settings:
    envVars:
      CORS_METHODS: "GET,POST,PUT,OPTIONS"
      ENABLE_TRANSACTIONS_EXTENSIONS: "TRUE"
    resources:
      limits:
        cpu: "1280m"
        memory: "1536Mi"
      requests:
        cpu: "512m"

vector:
  enabled: true
  settings:
    resources:
      limits:
        memory: "1536Mi"
      requests:
        memory: "1024Mi"
    envVars:
      # needs to on so we can call /refresh for integration tests
      TIPG_DEBUG: "True"
      TIPG_CATALOG_TTL: "30"

eoapi-notifier:
  enabled: true
  config:
    sources:
      - type: postgres
        config:
          channel: pgstac_items_change
    outputs:
      - type: cloudevents
        config:
          source: /eoapi/pgstac
          event_type: org.eoapi.stac.item
          destination:
            ref:
              apiVersion: eventing.knative.dev/v1
              kind: Broker
              name: primary
              namespace: default
