prometheus-adapter:
  prometheus:
    url: 'http://eoapi-support-prometheus-server.data-access.svc.cluster.local'
grafana:
  service:
    type: LoadBalancer
    annotations: {}
  ingress:
    enabled: true
    hosts:
      - eoapisupport.develop.eoepca.org
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - secretName: eoapi-support-tls
        hosts:
          - eoapisupport.develop.eoepca.org
  datasources:
    datasources.yaml:
        datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: http://eoapi-support-prometheus-server.data-access.svc.cluster.local
          access: proxy
          jsonData:
            timeInterval: "5s"
          isDefault: true
          editable: true
          version: 2 # This number should be increased when changes are made to update the datasource
prometheus:
  server:
    service:
      annotations: {}
      type: LoadBalancer
    persistentVolume:
      enabled: true
      storageClass: "managed-nfs-storage-retain"
      accessModes:
        - ReadWriteMany
      size: 1Gi
      selector:
        matchLabels:
          app: prometheus
          storage: nfs