apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  labels:
    eoepca/app-name: gitlab
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: eoepca
  sources:
    - repoURL: https://charts.gitlab.io
      chart: gitlab
      targetRevision: 8.0.1
      helm:
        releaseName: gitlab
        valueFiles:
        - $values/argocd/eoepca/sharinghub/parts/values/values-gitlab.yaml
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values  
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - CreateNamespace=true
