apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: monitoring-crds
spec:
  project: eoepca
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 83.1.0
    helm:
      releaseName: monitoring-crds
      values: |
        crds:
          enabled: true
        defaultRules:
          create: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        coreDns:
          enabled: false
        kubeDns:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheusOperator:
          enabled: false
        prometheus:
          enabled: false
        prometheusAgent:
          enabled: false
        thanosRuler:
          enabled: false
  destination:
    name: in-cluster
    namespace: operations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
