global:
  edition: ce
  hosts:
    domain: develop.eoepca.org
  ingress:
    configureCertmanager: false
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  minio:
    enabled: false
  
  appConfig:
    omniauth:
      enabled: false
      allowSingleSignOn: ['saml', 'openid_connect']
      providers:
      - secret: openid-connect

    lfs:
      enabled: false
    artifacts:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    backups:
      bucket: gitlab-backup-storage
      tmpBucket: gitlab-tmp-storage

  registry:
    enabled: false

upgradeCheck:
  enabled: false

gitlab:
  webservice:
    ingress:
      tls:
        secretName: gitlab.develop.eoepca.org-tls

  toolbox:
    backups:
      objectStorage:
        config:
          secret: gitlab-storage-config
          key: config
  sidekiq:
    enabled: false

registry:
  enabled: false
  ingress:
    tls: 
      secretName: registry.develop.eoepca.org-tls

minio:
  ingress:
    tls:
      secretName: minio.develop.eoepca.org-tls
certmanager-issuer:
  email: me@example.com

certmanager:
  install: false

nginx-ingress:
  enabled: false

nginx-ingress-geo:
  enabled: false

prometheus:
  install: false  

gitlab-runner:
  install: false

redis:
  metrics: 
    enabled: false

postgresql:
  metrics: 
    enabled: false
