apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zoo-project-dru
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: 'https://zoo-project.github.io/charts/'
    chart: zoo-project-dru
    targetRevision: 0.2.6
    helm:
      releaseName: zoo-project-dru
      valueFiles:
        - $app-zoo/values-zoo.yaml
        - $app-zoo/values-stageout.yaml
        - $app-zoo/values-cwlwrapper.yaml
  sources:
    - ref: app-zoo
      repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: develop
      path: argocd/eoepca/zoo-dru

  destination:
    name: in-cluster
    namespace: zoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
