cookiecutter:
  templateUrl: https://github.com/EOEPCA/eoepca-proc-service-template.git
  templateBranch: master
zoofpm:
  image:
    tag: eoepca-092ea7a2c6823dba9c6d52c383a73f5ff92d0762
zookernel:
  image:
    tag: eoepca-092ea7a2c6823dba9c6d52c383a73f5ff92d0762
customConfig:
  main:
    eoepca: |-
      domain=develop.eoepca.org
      workspace_url=https://workspace-api.develop.eoepca.org
      workspace_prefix=ws
workflow:
  defaultMaxRam: 1024
  defaultMaxCores: 2
  inputs:
    STAGEIN_AWS_SERVICEURL: http://eodata.cloudferro.com
    STAGEIN_AWS_ACCESS_KEY_ID: 4SMIGZNCR8LM1LSUY1HU
    STAGEIN_AWS_SECRET_ACCESS_KEY: MBiw2FOddg3Fs2Rm9NoDy10qufvJ4hzjmlQ1qwzV
    STAGEIN_AWS_REGION: WAW3-2
    STAGEOUT_AWS_SERVICEURL: https://minio.develop.eoepca.org
    STAGEOUT_AWS_ACCESS_KEY_ID: eoepca
    STAGEOUT_AWS_SECRET_ACCESS_KEY: changeme
    STAGEOUT_AWS_REGION: RegionOne
    STAGEOUT_OUTPUT: eoepca
  nodeSelector:
    minikube.k8s.io/primary: "true"
  storageClass: managed-nfs-storage-retain
ingress:
  enabled: true
  hosturl: https://zoo.develop.eoepca.org
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: zoo-open.develop.eoepca.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - zoo-open.develop.eoepca.org
    secretName: zoo-open-tls
persistence:
  procServicesStorageClass: managed-nfs-storage-retain
  storageClass: managed-nfs-storage-retain
  tmpStorageClass: managed-nfs-storage
postgresql:
  primary:
    persistence:
      storageClass: managed-nfs-storage-retain
  readReplicas:
    persistence:
      storageClass: managed-nfs-storage-retain
rabbitmq:
  persistence:
    storageClass: managed-nfs-storage-retain
iam:
  enabled: false
