---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns-api-token
  namespace: cert-manager-ns
spec:
  encryptedData:
    api-token: AgB/rZwLeBLAqXsua8B5Iryk+ENd4udBtpj7tVeJa8jL0zQSs4aQMDEz6ytawYVgz0r/EiTvgzk1QT3NQE3kzWtzx1faRTFo3T1kK6tuPDLBguf0cq8rUn0ZDWDA/e4Aqpjg7OwRTx1XLeLnhc2ybCGRMDawiXi725ahEpsiwpejmddzEIosKhw7dQw+SGehDjoK+nPM8Tkngvsd+khteN0EjQFeY1+HaV08I1BdN87ruGNy1LYHA5kFU3+WZNNpFmAZVlISiKwHD1Bh51x65/zI/kfjE78+8EG674cQnssbOI7saLq8Q8UJsjEo/zlSezAvHgof8fr0oDwxLKAoq0YyRvgDT1AYFwPaG1s+FhXrSioxLO6Nz/ith3eHIJnYnh3N2FkK6L12P7myGYbJcuIx7BVjaaPUeKtG4vB1FNXq/ye/JnIkIy/EmNnsHSzIbGzheJMDrO/0XMwR0s89B3VgWxX2gaBNrg7UdugFjvpUT6PggwL8WXfVxr5XWGkuDD4D93qs8lj+C9sYMXoTDRrDB8S1hMjCAg6M3myFdgIvEi5R7tEAbjiZf0ME+GHR5DhHwJgozF1rz9YbbhlJriQz0wfTodAsZ9npimAaCOqK4xjk75Isi07y7fljup05wm7JEGlQox0PjC7tLDqcr9B3O7cSRKPix+bc9dIFTOVkDEtkX/QMyd2N9fPgwKUmsHD7LeqfTe8otpgHgnxqhkr8QY0+INetsjRvXkkdqwb5gTeMfhG4IXqhTOZXadlaewqdESGf1g==
  template:
    metadata:
      creationTimestamp: null
      name: dns-api-token
      namespace: cert-manager-ns
