---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns-api-token
  namespace: cert-manager-ns
spec:
  encryptedData:
    api-token: AgCoj1MqAoadzvhuwVgwTvTb0J13TpDkFQlfDlqyhru14cohatI/dSnpumeRueneR000BhK8VNVbLA2e7ZzQbp+bcEtbM1tTfgvOCquF4FYc+pCr8F9SDN3yPgP46RCbMJVmnFO6eoHlZ/J0tlFSNy2eylCJz8Z1UpURHJnfoQqO1GaxmivpGqUL2VMOMqbPqp6CaBFKePQMLbzn0BOZWRg5iOAYs9Xso+7RPM6CcOMikHT/fej4D1xWPY/bXm9Vft4gqJIHMyFGygOINIGKpkoe3ywY56C+vbmylcXzVwzmJAO3U3VYl7NeajeNFjAlVw9PRzGx8fM9+3ZZjpmQtfY/uUDfSz5uNGQHs6eCc/QOfvCeS76HqZX0GxlfWND9VLdqVYu4rWcwAxvtfiPoITA6Kj1Y38TUCfINmK8Y6XyPlCts1ar6iKDW3IhSQ6haNmsS4YMoy6pHZFX/ZNah8pdxkYKz/Na/hGe9Zv6vhXUk7EsiwCRBr68zFZuDQp19GuT7Nln96Btio1yt8V1JgG89t0qC/Jr086FmNJwuvuVY7CiYsiXZ/7SOQL4hc0loLQCL2i2+Ovs8Fomg/ASHAV3fRHStswN7WZ0yxhkG3m/1fLrGJCtj0Vh6/HcbeDS48dERvwJsX11zUm6z/KeFTaEgN/8cIaxtm+tBA1Wh0erf/5keZWIbStYLuRMOcBG02jhDsR8N+u7CHRhnC/6c4RiBC7/jLNJ7FdAFGsKZM6nsM4Z8DW7+hLNuLN9uRR6OdK2uiB8/Hw==
  template:
    metadata:
      creationTimestamp: null
      name: dns-api-token
      namespace: cert-manager-ns
