---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns-api-token
  namespace: cert-manager-ns
spec:
  encryptedData:
    api-token: AgBECo/I2xecarUmfRZbhk0D+7fTeKrdeBKEzw8fEJVRtv5Yq1ZZrVzufxScF9lKSyeYCxqFWKmMY7B7Dl72a8vYp4IaKs2tuJUMLglPDxmYKAVp6OAxJHcO41frYuabS+hBGtQQ2GbenNIECGrd3CseHFFovSxouBPJLElrhSixkLH/RYKJ9E7Lrjbg2R4pQjUTvTOyhdjYCPxRAGn8vv9NKxnPFPslL6CIVWyQE15ufePK/PRV+HNSO9KLI33yFj2q06PYWGfs7NwM+lwCBk6LVvPhwbGdRGNlKopcE7nEap7tLt4QCGz33E3MNEtiHlkULLiju0Cfbr95D+ti9pocVYhdfPKNnfYASqxpAl2AaJnTAd6iyJAxsGWHM44jX8O1gaG7Nmteb7V6FsMQWfg86gTUprEzbceF7fzQ9NwINWKamTwDQ4AWznrktqEnJASmO62izK/3wi3uGFdZG3IT9FKSUifSvBjgFbneEY/WyExDUiBt/bQBQtKsiU7xHT2jE0zxle1m6L3XBcVdtDMISN2QuDmhXlMPVh0VFUThM9khr37wfXXSaYVQ9BDbVK7bHJ7t+NHgQ1/kM9WMgNPwpY28zda91uJNMzs53aMsnUM5JHu2c/MMoFaZYuDjyBjwKMo/aQbEiSYFeEz78PPEyoJXPH2NXlommRJZZy4jJBozK6a3k245evvnHafltJEUi2RUqG4RvQG7p2ACyTc1PrES63bwHW3bbcdM13Sy42AdwuAxEfUKkQHT1EEVAeRTuC4EPw==
  template:
    metadata:
      creationTimestamp: null
      name: dns-api-token
      namespace: cert-manager-ns
