kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-access-db
  labels:
    k8s-app: data-access
    name: data-access
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
