resources:
  - _dashboards
  - _rules
  - alerting
  - monitoring

patches:
  - target:
      group: monitoring.coreos.com
      kind: PrometheusRule
    patch: |
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: monitoring.coreos.com
      kind: AlertmanagerConfig
    patch: |
      apiVersion: monitoring.coreos.com/v1alpha1
      kind: AlertmanagerConfig
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: role.keycloak.crossplane.io
      kind: Role
    patch: |
      apiVersion: role.keycloak.crossplane.io/v1alpha1
      kind: Role
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: openidclient.keycloak.crossplane.io
      kind: Client
    patch: |
      apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
      kind: Client
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: client.keycloak.crossplane.io
      kind: ProtocolMapper
    patch: |
      apiVersion: client.keycloak.crossplane.io/v1alpha1
      kind: ProtocolMapper
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true