apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: registration-harvester-api
  namespace: registration-harvester-api
spec:
  http:
    # 1. Redirect to /flowable-rest/
    - name: redirect-root
      match:
        hosts:
          - registration-harvester-api.rke2.deploybox.co.uk
        paths:
          - /
          - /flowable-rest
      plugins:
        - name: redirect
          enable: true
          config:
            uri: /flowable-rest/
      backends:  # never hit due to redirect
        - serviceName: registration-harvester-api-engine-flowable-rest
          servicePort: 8080

    # 2. Main service handler
    - name: rewrite-flowable-path
      match:
        hosts:
          - registration-harvester-api.rke2.deploybox.co.uk
        paths:
          - /flowable-rest/*
      backends:
        - serviceName: registration-harvester-api-engine-flowable-rest
          servicePort: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registration-harvester-api-tls
  namespace: registration-harvester-api
spec:
  dnsNames:
    - registration-harvester-api.rke2.deploybox.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01-apisix
  secretName: registration-harvester-api-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: registration-harvester-api-tls
  namespace: registration-harvester-api
spec:
  hosts:
    - registration-harvester-api.rke2.deploybox.co.uk
  secret:
    name: registration-harvester-api-tls
    namespace: registration-harvester-api
