
resources:
  - ss-registration-harvester-secret.yaml
  - app-registration-harvester-flowable.yaml
  - app-registration-harvester-operaton.yaml
  - ingress-registration-harvester-flowable.yaml
  - app-registration-harvester-worker-landsat.yaml
  - app-registration-harvester-worker-sentinel.yaml
  - app-registration-harvester-worker-stac.yaml