apiVersion: v1
kind: Namespace
metadata:
  name: data-access
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.35
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
