apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-service-core
  namespace: argocd
  labels:
    eoepca/app-name: identity-service
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://eoepca.github.io/helm-charts
    chart: identity-service
    targetRevision: 1.0.98
    helm:
      releaseName: identity-service
      valueFiles: 
        - identity-service/parts/values-identity-service.yaml

  destination:
    name: in-cluster
    namespace: um
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
