---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: identity-postgres
  namespace: um
spec:
  encryptedData:
    postgresPassword: AgAl+fZVG5QSYAuFtMLq6gvcNbirUltCdfHRHp+X7/HmS/mtqj5kUOiUUJinp/PzVG0/ZnueKNWjZAU70kT58TCR9BVlb9qSvOw9dsl0UGHrLuMI6P4gmPQj+tXbTrNz/FOJSkfJzRvAu1Thk8gNyj2JFM/kaxQnFOJHPhRwPcoJodjb3cLo3TPAWL2vlAhxMK9FaMXiYrfVcOjnT8YDwkJk9yQtkdntcbZ2dcjwNEkkVdHzYZoPDsHWkA29czmhFiCTzDz19gCr/UYLD2/hzCX75KtQEl0H7zFrCGA3NPWdn+quu9jSWBf+qelVDWBR/YYHPWkZ240OyFq7xTcYHat9cMqzq4Zag8LesTd6DchZX2F3S86QF0iKpcneCdNnU3Hjc8yCgFPwuzKGwsTeQFI1Cf2ONCE7qEz2vB6pdOl0MvDSAutJSDAsJsnXbSjdrRr8jInwTzB2x9Mu6Cav0hUGLQE/ymlzlJqPjlo3HL95rXKpdG4pFdjbbAvIWWljuRcSXjRx8LIt/NrbvIn9usax9n4LGGPKkWCXwnpkhZ7OY39quB8EVTEcdg+CQSUCe6bNBEuQ1V4zZQuW7yRBvH3/JjHCGc4nVD8oOwmNxpVhqBFXur9GPh4PYthQtd85YbO1C+wt1mWXBEl5vmPMAOvtPpWpsMjm4CtqCXQgyUbIh1+7PF+MI8Ujtns3W8AW8jNdI1RSWlpSw6+4PNHy7Uq1IjtKVg==
    pgPassword: AgB+0d3JKMYp+5wyOe/0P0en31JnolM+DtQ8xW6P3IEXNMenuIdQRy5kcko4pJudKeh06bvm/AbDqF+c8rZ1xkDqGp/eKwYMqldsO2d+/BJFL7SjK+dPH25DqLblI2MzeiCu6DN/fuEgpGcqC1npOdZhrSDAoxts6ZeDOh0vhoY9NHl/dKNx8sYEVxK8zA0PHrz/MY+WeXhdkU7CfQfq+5Z9zzaiLlb5xpwJUk0A9DkO+QMM4A6R9UpSDsaKVLaEvo8url9j3MdlzreRGCEDLJLs0CdINcj3vQEni/IKOeYpmtGqoQtCHT7fHThzpkddzl55XwMUKrshW77YUknRHdz93vkfZ07nCtgf3pe6eglpLBIwvVj2whqnnlKrf9sYK7fFmoXOy5k55JOjV602VQpaIGwQgsb4mQgok6KUMkZRkwJVxeWxB134fbGaViLPbCgCbuLsGIFK/Skzh30XxPmMehl36c7frzsmjKtKs9li5UOlxD9fCNqfybuNPCOo6CxsBzYLahpIBz2nZj3giCuRQoac322SZi4reNmu2/EITeSt4Dvuv6w0iwEvdOBe/iFWJH56T8y6Vz1iiQTHz0SHeBvBUOOKnYsGKby+mw1J6iQyeIf/bS9WUMWR6Npck1aMHwZyXxVXPU5hhkxGV+HRFU+tDJY4zVZfM6BTAZwwZa/waqL/IHunVFdv3T5ivy2J49Fr8dnycZIe0QyfW/rvQKiLLEmk1s1Rwc6joMd5SDt1ZGG3fYtz
  template:
    metadata:
      creationTimestamp: null
      name: identity-postgres
      namespace: um
