apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: identity-postgres
  namespace: um
spec:
  encryptedData:
    pgPassword: AgBVccOm74M9JDV6LOdu8r+eRwx/E7wvjlW3juVWlz0znAuIsvgWgx39ys723sYc0KYvhKk+edvB+DKnPaKu6wr43Yjf4XUJuiyKcSwhpMHqg1Yw462dC6yY8Vy9m09gZDKUXCNY1Js6hNokXTf0yqLhwHRAnK2EysKJPOydJ6TNAXXkGjOl90FJU0j5SePmDVdPzTGDpIClpEI8doEG8M0CzZIkj+J4uNGcTSYuP8K0elgrZmpFEedx878NB2V1GwXB3A/4vLOs6RXAT00FdTof85wI488xiNgdTRd2lVAxsx3SY+LZ9squbp7S8KxhK+/q1KyVYc/xKn5FlnAFSp+eNXDQlmnP5s+DCeFfTEUlZ8omZ3nYnD2tHx5Ggblc/Zi/OhxvsybfB7DZGGJbVqzaJCc/E/1cKCy8uIcymAcDJT+RQFMNjOU/CO6uub0Njta475Qj+SXBr+SUg3oHqJ7bDCrUG7398hIGy1DJpOBZmRxr7iDZwR3PmH1CFnITWQ6T4dq5yX4FR3+lqTstUmGTfirt/ZztViTUJrenrUL1QFMokTYlbw8ZOXNQD6JCksqmw+qKGWvOAZbMCn4nx1oWNzdrg1L6Ufg3ukQPft9UeS4/PlX+p5jP2EcYgG2yaDYqcLqHjNFFZbxddJdJG97izqwlf8I7zUlEuqSIFX08v28U0kQUVRmj67OF8j3dxG4cZQBRSTm+A9bA9w==
    postgresPassword: AgAiYeauaaAwBopiVI6Nkgg0EK6LR7dyhOFYi8K0f6B3FI4NkY8Qs3AaMAJYcuWL7jrJ+ymluVxs1ikraxDDfg+bhbpRYjqzw2kGx4OHr8/PGLzLa9XgA3zp8KbbWn+GmZ0+7mybKkymWRE7DLGwlUODFX5V+GK82feku0Ar7NDhOQQDBBCN4/4kfnwsb+PYQhGAxB34Q0O4Ia1eQqjn0mgZxk8FWaPvu6Jxz+VKKao04U9MHQVfJ5Cw5ZFjw/1hXXJAEltlk0ulwL6hY04qbkFhylR43YjWii79hPEP8DaJAGiygD4CSjxJHPIspcaATYsqC21Oh640mPCfgzK3B++UsNwtFC99ciCNymFNE3wG7/e0593Tm+1wq/FAlw02+mh9x498cdlifgh3FYsKkpORhOXLV1WsHNYQmlJLvvaJrj9+QVhyn8ftUFYEaiTaUaFP15ycQic+9AcJ5aGb9ROcXN5fCGvVqYg/g2WJenbxMPvylM7ydbvomrsCc8BkrdBJuKpl1DQtrGyTIGwwsjuSiUh4c7zM0dhemJr8Zu2OMpDF/jVCbbCtVlA5L3xts08u8CPD4dl91JHbTbjUGnKInZW9ZuXLDi2dRTwxg0X6YJUKFLPWlSMPOgLGVUj9U3wgetC1yyvM9S92b5u+YAK3nlt8S8ICPlQer+ZIqhK015qbGLf9atve6apuCHYYUWiMe9J2Gag9Typb9A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: identity-postgres
      namespace: um
