apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-management
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: cert-management
spec:
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    path: argocd/infra/cert-management
    targetRevision: deploy-develop
  destination:
    server: in-cluster
    namespace: cert-manager-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
