apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-api-core
  namespace: argocd
  labels:
    eoepca/app-name: registration-api
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: 'https://eoepca.github.io/helm-charts'
    chart: rm-registration-api
    targetRevision: 1.4.0

    helm:
      releaseName: registration-api
      valuesObject:
        fullnameOverride: registration-api
        # image: # {}
          # repository: eoepca/rm-registration-api
          # pullPolicy: Always
          # Overrides the image tag whose default is the chart appVersion.
          # tag: "1.3-dev1"

        ingress:
          enabled: false
          annotations:
            kubernetes.io/ingress.class: nginx
            ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: registration-api.develop.eoepca.org
              paths: ["/"]
          tls:
            - hosts:
                - registration-api.develop.eoepca.org
              secretName: registration-api-tls

        # some values for the workspace API
        workspaceK8sNamespace: "rm"
        redisServiceName: "data-access-v1x-redis-master"

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
