apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-api-core
  namespace: argocd
  labels:
    eoepca/app-name: registration-api
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: 'https://eoepca.github.io/helm-charts-dev'
    chart: registration-api
    targetRevision: 2.0.0-dev7

    helm:
      releaseName: registration-api
      valuesObject:
        global:
          namespace: rm
        ingress:
          enabled: "false"
        pygeoapi:
          image:
            repository: eoepca/registration-api
            pullPolicy: Always
            tag: "latest"
          config:
            server:
              url: https://registration-api.develop.eoepca.org
            logging:
              level: ERROR
              # /tmp/pygeoapi.log
            metadata:
              identification:
                title: EOEPCA+ Registration API
            resources:
              register:
                type: process
                processor:
                  name: registration_api.processes.registration.RegisterProcessor
              deregister:
                type: process
                processor:
                  name: registration_api.processes.registration.DeregisterProcessor
              hello-world:
                type: process
                processor:
                  name: HelloWorld

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
