apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: registration-api-route
  namespace: rm
spec:
  ingressClassName: apisix
  http:
  - name: registration-api-protected
    match:
      hosts:
        - registration-api-protected.develop.eoepca.org
      paths:
        - /*
    backends:
      - serviceName: registration-api-service
        servicePort: 80
    plugins:
      # Authn - expect JWT in `Authorization: Bearer` header
      - name: openid-connect
        enable: true
        config:
          client_id: "registration-api"
          client_secret: "TBD"
          session:
            secret: "V649LpBqKIfJv95BzDsR29e9"
          discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
          realm: eoepca
          use_jwks: true
          bearer_only: false # as we want to redirect to login screen (default: false)
          set_access_token_header: true  # (default: true)
          access_token_in_authorization_header: true  # (default: false)
      # Authz
      - name: authz-keycloak
        enable: true
        config:
          client_id: "registration-api"
          client_secret: "TBD"
          discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration"
          lazy_load_paths: true
          ssl_verify: false
      # Allow CORS access
      - name: cors
        enable: true
  - name: registration-api-open
    match:
      hosts:
        - registration-api.develop.eoepca.org
      paths:
        - /*
    backends:
      - serviceName: registration-api-service
        servicePort: 80
    plugins:
      - name: cors
        enable: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registration-api-tls
  namespace: rm
spec:
  dnsNames:
    - registration-api-protected.develop.eoepca.org
    - registration-api.develop.eoepca.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01-apisix
  secretName: registration-api-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: registration-api-tls
  namespace: rm
spec:
  ingressClassName: apisix
  hosts:
    - registration-api-protected.develop.eoepca.org
    - registration-api.develop.eoepca.org
  secret:
    name: registration-api-tls
    namespace: rm
