---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registration-api-secret
  namespace: rm
spec:
  encryptedData:
    EOEPCA_REGISTRATION_API_IAM_CLIENT_ID: AgBz8pGUyfVPWlssEOEvY5ydwvYx4naIBwrCwi2bKi9VmriYoAjSSyn3h2lSKp7IbGfMs6kmJ1QKtclEGPy9IKeHPvRTyUNqLJMXngJZ0uq9KJKCqN4vIIZwipD2U7zXAxskcAEsxhy9KQX/p3FmW/Db8Qrs+Uge/Kw6zASS6o7oRYkQINzqmaHdhXWjumCdy174mvWm2iHE/fG31IeULpy9hfLUPXPYr7+Lmsktue9Hk29woEhJ7cQ3stv2UERznqTbMDOmjQG2ElFS5PMic776pVD6zcYaAR5FoZucgI2G43DhjHiXconzWJxToIqd9/SeI8S/wlv0USLG8NoHXbkGxJ26tW+gAZWalRyQAq4OyutINA86GiSBzuDgL2mYemBGYjoyskSh7ivTCEww00sOxWub1G0FFxtn/w2IhT4YWoMgqt/87d7svdMpVQIJoF/PelnX+CNWgbcoRVpWrwu/o3Nb2PMxweWLjQCIv1Rkqi1gCH+NRjSWXa1Q92v1ENJYJ7owPYdDyRerPQomaORqmfoJQuqZp8DK+PRabJJddtDsxdpm6AMAzMWvBh2pskgqtKcs5kjML5CeXz/AOUDtET9ioRgBOwTDNfZRaOaVuAAmYVeLf3R9riOg5Rzl8hUqR9O5gjXM2LZdUZlef72vAB/Y16AYQA0FATBGDrU81NOoDN87zY4XvGJ/rERAXyB2U2fA+f7XCQjmJOdpaUq2FWQ5e9HY
    EOEPCA_REGISTRATION_API_IAM_CLIENT_SECRET: AgAzxTAYPXzg/l9ueG0rxQOpl9UqXrVecPPlJRUUSw38K/ry3jFuhjzDmIN2XCR1Fa/xPiX4vQWd99KefsLgskvW8jw8qM/yirEzb8EZo8cLY/WUTqfFvc7wXJda7BRQnGxC50OgaSi8ZSUZwMzXczH0K8lzaYZJTbyLWFkO3r+dBB+DiD2CnbpZECbtRfTyFPWLi9YsSJqYFINPHnZkBVOjcy+WDcHS/Ybkbi+B6j8X2Abm36YmwuAz3dRq4qEBZjhSHpcpAKozhrE804DPcoC3HUKoFDcjyYkmhStkLBESX4vYRjJlHq53n/DuSctTrtgko3yyb5VC5qQf9eVO9MjReJ/XOZS+ILJ/rMYr1JQGUFsq7JakX/3KPXxTyrs3XOC6Vuy1f6E1zS0aIhb8cOOt/b4UXHN7PQyjsKOmOTr4zO3JMFHdf6D+cdAXUcxyzDC+J7fHcoIwx03xWfLC+CW1jluacsoMgUItKHsBfn12yyB0EXB9RIz3yAV5LAQxFfGRPPxVRjo50SUW0Vdo80xkiNp65ZEi5wD6Q3DSOSmP0iF5bkVMU9npxElhnnnI7KqHtC2i5FxFknnmWsI3lvHkST7CY5j2u2In3c+Y6vicCm7F5nv6jVCIs+nUh8CA6X3AXkGE1x4a97HuOyIJBEboCkC8Ug/ACWT+ZrK4XvQkIcyEZqvrCrZvKDX282dhjDOFNSpYM4hfvlReCe7F8xq2S5QH4ITBy17dH0S3+3aPsQ==
  template:
    metadata:
      name: registration-api-secret
      namespace: rm
