
global:
  defaultExternalIssuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01-apisix

application-quality:
  # Values for deploying the Application Quality Building Block in the EOEPCA Develop cluster.

  publicUrl: "https://application-quality.develop.eoepca.org"

  # Application Quality frontend
  web:
    publicUrl: "https://application-quality.develop.eoepca.org"

  persistence:
    enabled: true
    storageClassName: managed-nfs-storage-retain

  calrissian:
    storageClassName: managed-nfs-storage-retain

  oidc:
    enabled: true
    realm: eoepca
    realmBaseUrl: "https://iam-auth.develop.eoepca.org/realms/eoepca"
    clientId: application-quality-bb
    clientSecret: ""
    postLogoutRedirectUrl: "https://application-quality.develop.eoepca.org/"
    loginRedirectUrl: "https://application-quality.develop.eoepca.org/"
    rpRedirectUri: "https://application-quality.develop.eoepca.org/"

    iam_provisioning:
      enabled: false
      # keycloakProviderConfig: keycloak-provider-config
      # clientName: Application Quality BB
      # clientDescription: Application Quality Web Portal and Grafana OIDC
      # clientSecretName: application-quality-iam-client
      # clientSecretKey: client_secret
      # clientEnabled: true
      # namespace: iam-management
      # accessType: PUBLIC
      # httpScheme: https
      # initialiseTestUsers: false

  ingress:
    enabled: true
    className: apisix
    domain: application-quality.develop.eoepca.org
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http01-apisix
      apisix.ingress.kubernetes.io/use-regex: "true"
      k8s.apisix.apache.org/upstream-read-timeout: "600s"
      k8s.apisix.apache.org/enable-cors: "true"
      k8s.apisix.apache.org/http-to-https: "true"
      argocd.argoproj.io/ignore-healthcheck: "true"
    tls:
      - hosts:
        - application-quality.develop.eoepca.org
        secretName: application-quality-tls

  notifications:
    enabled: true
    middleware: "knative"
    brokerName: "primary"
    brokerNamespace: "default"
    # Also used as type prefix for incoming notifications
    channelPrefix: "org.eoepca.application-quality"
    responseSource: "/eoepca/application-quality"
    responseTypePrefix: "org.eoepca.application-quality.response"

  automations:
    enabled: false

# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  ingress:
    enabled: true
    ingressClassName: apisix
    hosts:
      - application-quality.develop.eoepca.org
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http01-apisix
      k8s.apisix.apache.org/rewrite-target-regex: "/dashboards/?(.*)"
      k8s.apisix.apache.org/rewrite-target-regex-template: "/$1"
      k8s.apisix.apache.org/upstream-read-timeout: "600s"
      k8s.apisix.apache.org/enable-cors: "true"
      k8s.apisix.apache.org/http-to-https: "true"
      argocd.argoproj.io/ignore-healthcheck: "true"
    path: /dashboards
    pathType: Prefix
    tls:
      - secretName: application-quality-tls
        hosts:
          - application-quality.develop.eoepca.org

  persistence:
    enabled: true
    storageClassName: managed-nfs-storage-retain

  grafana.ini:
    server:
      root_url: https://application-quality.develop.eoepca.org/dashboards
