
resources:
  - app-application-quality-core.yaml
  - ss-application-quality-auth-client.yaml
  - ss-application-quality-iam-client.yaml
  - ss-grafana-dashboards-admin-creds.yaml
  - ss-grafana-dashboards-oauth-config.yaml
  - app-application-quality-sonarqube.yaml
  - ss-application-quality-sonarqube-db-secrets.yaml