apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access-core
  namespace: argocd
  labels:
    eoepca/app-name: data-access
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://eoepca.github.io/helm-charts
      chart: data-access
      targetRevision: 1.4.1
      helm:
        releaseName: data-access
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-core.yaml
          - $values/argocd/eoepca/data-access/parts/values/values-creodias-data.yaml
          - $values/argocd/eoepca/data-access/parts/values/values-harvester.yaml
        valuesObject:
          existingSecret: data-access-secrets
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values
    # pgo cannot be a dependency of eoAPI b/c it causes zombie resources on helm uninstall
    - repoURL: oci://registry.developers.crunchydata.com/crunchydata/pgo
      chart: pgo-5.5.2
      targetRevision: 5.5.2
      helm:
        releaseName: pgo
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-pgo.yaml
    - repoURL: https://devseed.com/eoapi-k8s/
      chart: eoapi
      targetRevision: 0.3.0
      helm:
        releaseName: eoapi
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-eoapi.yaml

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
