apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access-gateway
  namespace: argocd
  labels:
    eoepca/app-name: data-access
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://helm.tyk.io/public/helm/charts/
      chart: tyk-oss
      targetRevision: 1.6.0
      helm:
        releaseName: tyk-oss
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-tyk.yaml
    - repoURL: oci://registry-1.docker.io/bitnamicharts/
      chart: redis
      targetRevision: 20.1.0
      helm:
        releaseName: tyk-redis
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-tyk-redis.yaml
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values
  destination:
    name: in-cluster
    namespace: data-access
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
