apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access-core
  namespace: argocd
  labels:
    eoepca/app-name: data-access
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:

    - repoURL: https://devseed.com/eoapi-k8s/
      chart: eoapi
      targetRevision: 0.12.0
      helm:
        releaseName: eoapi
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-eoapi.yaml

    - repoURL: https://github.com/sentinel-hub/titiler-openeo
      path: deployment/k8s/charts
      targetRevision: titiler-openeo-v0.12.0
      helm:
        releaseName: eoapi-titiler-openeo
        values: |
          stac:
            apiUrl: "https://eoapi.develop.eoepca.org/stac"
            serviceStoreUrl: "/app/services/eoapi.json"
          env:
            TITILER_OPENEO_API_ROOT_PATH: "/openeo/"
          auth:
            method: "oidc"
            oidc:
              enabled: true
              clientId: "eoapi"
              wellKnownUrl: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
              redirectUrl: "https://eoapi.develop.eoepca.org/openeo/"
          extraVolumes:
            - name: services
              configMap:
                name: titiler-openeo-services
          extraVolumeMounts:
            - name: services
              mountPath: /app/services
              readOnly: true

    - repoURL: https://stac-manager.ds.io/
      chart: stac-manager
      targetRevision: 0.0.12
      helm:
        releaseName: eoapi-stac-manager
        valueFiles:
          - $values/argocd/eoepca/data-access/parts/values/values-stac-manager.yaml

    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: data-access
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
