apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geoparquet-exporter
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: data-access
spec:
  project: eoepca
  source:
    repoURL: https://github.com/developmentseed/pgstac-geoparquet-exporter
    targetRevision: pgstac-geoparquet-exporter-v0.2.0
    path: charts/pgstac-geoparquet-exporter
    helm:
      values: |
        stacApiUrl: "https://eoapi.develop.eoepca.org/stac"
        
        database:
          existingSecret: "default-pguser-eoapi"
        
        storage:
          outputPath: "s3://eoapi-geoparquet/geoparquet"
          existingSecret: "data-access"
          endpoint: "eodata.cloudferro.com"
        
        exportConfig:
          exportAll: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: data-access
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true