apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-api-check
  namespace: data-access
  labels:
    argocd.argoproj.io/instance: data-access
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: synthetic-api-check
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synthetic-api-check
    spec:
      restartPolicy: Always
      containers:
        - name: checker
          image: quay.io/curl/curl:8.12.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          command:
            - /bin/sh
            - /opt/synthetic-api-check/check-stac.sh
          env:
            - name: STAC_BASE_URL
              value: https://eoapi.develop.eoepca.org/stac
            - name: SYNTHETIC_API_CHECK_ITEMS_LIMIT
              value: "100"
            - name: SYNTHETIC_API_CHECK_SEARCH_LIMIT
              value: "10"
            - name: SYNTHETIC_API_CHECK_SLEEP_SECONDS
              value: "3"
          volumeMounts:
            - name: synthetic-api-check-script
              mountPath: /opt/synthetic-api-check/check-stac.sh
              subPath: check-stac.sh
              readOnly: true
      volumes:
        - name: synthetic-api-check-script
          configMap:
            name: synthetic-api-check-script
            defaultMode: 0755
