apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: default-pguser-eoapi
  namespace: data-access
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra
  target:
    name: default-pguser-eoapi
    creationPolicy: Owner
  data:
    - secretKey: dbname
      remoteRef:
        key: default-pguser-eoapi
        property: dbname
    - secretKey: host
      remoteRef:
        key: default-pguser-eoapi
        property: host
    - secretKey: password
      remoteRef:
        key: default-pguser-eoapi
        property: password
    - secretKey: port
      remoteRef:
        key: default-pguser-eoapi
        property: port
    - secretKey: uri
      remoteRef:
        key: default-pguser-eoapi
        property: uri
    - secretKey: user
      remoteRef:
        key: default-pguser-eoapi
        property: user
