apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: eoapi
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: eoapi
    accessType: PUBLIC
    clientId: eoapi
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true # allow for now to simplify testing
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    oauth2DeviceAuthorizationGrantEnabled: true
    rootUrl: https://eoapi.rke2.deploybox.co.uk
    webOrigins:
      - '*'
    validRedirectUris:
      - '*'
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: stac-editor
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: stac_editor
    clientIdRef:
      name: eoapi
      policy:
        resolution: Required
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: data-access-admin
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    name: data-access-admin
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: data-access-admin
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: data-access-admin
      policy:
        resolution: Required
    roleIdsRefs:
      - name: stac-editor
        policy:
          resolution: Required
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: eoapi-audience-mapper
spec:
  providerConfigRef:
    name: iam-keycloak-keycloak-provider-config
  forProvider:
    clientIdRef:
      name: eoapi
      policy:
        resolution: Required
    realmId: eoepca
    protocol: openid-connect
    protocolMapper: oidc-audience-mapper
    name: eoapi-audience
    config:
      "included.client.audience": "eoapi"
      "access.token.claim": "true"
      "id.token.claim": "false"
