resources:
  - ss-data-access.yaml
  - app-data-access-core.yaml
  - iam.yaml
  - route.yaml
  - eso-pgo.yaml
  - deployment-synthetic-api-check.yaml

configMapGenerator:
  - name: stac-auth-proxy-filters
    options:
      disableNameSuffixHash: true
    files:
      - eoepca_filters.py=stac-auth-proxy/eoepca_filters.py
  - name: titiler-openeo-services
    options:
      disableNameSuffixHash: true
    files:
      - eoapi.json=titiler-openeo/eoapi.json
  - name: synthetic-api-check-script
    options:
      disableNameSuffixHash: true
    files:
      - check-stac.sh=synthetic-api-check/check-stac.sh
