resources:
  - ss-data-access.yaml
  - app-data-access-core.yaml
  - iam.yaml
  - route.yaml
  - eso-pgo.yaml
  - deployment-synthetic-api-check.yaml

configMapGenerator:
  - name: stac-auth-proxy-filters
    options:
      disableNameSuffixHash: true
    files:
      - eoepca_filters.py=stac-auth-proxy/eoepca_filters.py
  - name: titiler-openeo-services
    options:
      disableNameSuffixHash: true
    files:
      - eoapi.json=titiler-openeo/eoapi.json
  - name: synthetic-api-check-script
    options:
      disableNameSuffixHash: true
    files:
      - check-stac.sh=synthetic-api-check/check-stac.sh

patches:
  - target: {group: bitnami.com, kind: SealedSecret}
    patch: |-
      apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        name: data-access-secrets
        annotations: {argocd.argoproj.io/sync-wave: "-20"}
  - target: {group: external-secrets.io, kind: ExternalSecret}
    patch: |-
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: data-access-database
        annotations:
          argocd.argoproj.io/sync-wave: "-20"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: .*keycloak.m.crossplane.io
    patch: |-
      apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
      kind: Client
      metadata:
        name: data-access-iam
        annotations:
          argocd.argoproj.io/sync-wave: "-10"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target: {group: argoproj.io, kind: Application}
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: data-access-core
        annotations: {argocd.argoproj.io/sync-wave: "0"}
  - target: {group: apisix.apache.org}
    patch: |-
      apiVersion: apisix.apache.org/v2
      kind: ApisixRoute
      metadata:
        name: data-access-routes
        annotations:
          argocd.argoproj.io/sync-wave: "10"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target: {group: apps, kind: Deployment}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: data-access-checks
        annotations: {argocd.argoproj.io/sync-wave: "20"}
