resources:
  - ss-data-access.yaml
  - app-data-access-core.yaml
  - iam.yaml
  - route.yaml
  - eso-pgo.yaml
  - app-geoparquet-exporter.yaml

configMapGenerator:
  - name: stac-auth-proxy-filters
    options:
      disableNameSuffixHash: true
    files:
      - eoepca_filters.py=stac-auth-proxy/eoepca_filters.py
  - name: titiler-openeo-services
    options:
      disableNameSuffixHash: true
    files:
      - eoapi.json=titiler-openeo/eoapi.json
