kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-access-redis
  labels:
    k8s-app: data-access
    name: data-access
    eoepca/app-name: data-access
spec:
  storageClassName: managed-nfs-storage-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
