apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: stac
  namespace: data-access
  # annotations:
  #   argocd.argoproj.io/sync-options: skip
spec:
  ingressClassName: apisix
  http:
  - name: manager-redirect
    websocket: true
    backends:
    - serviceName: eoapi-stac-manager
      servicePort: 80
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /manager
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /manager/
  - name: manager-route
    websocket: true
    backends:
    - serviceName: eoapi-stac-manager
      servicePort: 80
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /manager/
      - /manager/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/manager)($|/.*)
        - $2
      enable: true
    - name: openid-connect
      enable: true
      config:
        discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/openid-configuration"
        use_jwks: true
        bearer_only: false
        set_access_token_header: true
        access_token_in_authorization_header: true
        set_id_token_header: false
        set_userinfo_header: false
        client_id: eoapi
        client_secret: ""
        redirect_uri: "https://eoapi.rke2.deploybox.co.uk/manager/"
    - name: cors
      enable: true

  - name: browser-redirect
    backends:
    - serviceName: eoapi-browser
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /browser
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /browser/
  - name: browser-route
    backends:
    - serviceName: eoapi-browser
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /browser/
      - /browser/*
  - name: vector-redirect
    backends:
    - serviceName: eoapi-vector
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /vector
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /vector/
  - name: vector-route
    backends:
    - serviceName: eoapi-vector
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /vector/
      - /vector/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/vector)($|/.*)
        - $2
      enable: true
  - name: multidim-redirect
    backends:
    - serviceName: eoapi-multidim
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /multidim
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /multidim/
  - name: multidim-route
    backends:
    - serviceName: eoapi-multidim
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /multidim/
      - /multidim/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/multidim)($|/.*)
        - $2
      enable: true
  - name: raster-redirect
    backends:
    - serviceName: eoapi-raster
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /raster
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /raster/
  - name: raster-route
    backends:
    - serviceName: eoapi-raster
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /raster/
      - /raster/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/raster)($|/.*)
        - $2
      enable: true
  - name: openeo-redirect
    backends:
    - serviceName: eoapi-titiler-openeo
      servicePort: 80
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /openeo
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /openeo/
  - name: openeo-route
    backends:
    - serviceName: eoapi-titiler-openeo
      servicePort: 80
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /openeo/
      - /openeo/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/openeo)($|/.*)
        - $2
      enable: true
  - name: stac-redirect
    priority: 100
    backends:
    - serviceName: eoapi-stac-auth-proxy
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      methods:
      - GET
      paths:
      - /stac
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /stac/
    - name: cors
      enable: true
  - name: stac-open-route
    priority: 90
    backends:
    - serviceName: eoapi-stac-auth-proxy
      servicePort: 8080
    match:
      hosts:
        - eoapi.rke2.deploybox.co.uk
      methods:
        - GET
      paths:
        - /stac/
        - /stac/api*
        - /stac/collections
        - /stac/collections/*
      exprs:
      - subject:
          scope: Path
          name: uri
        op: RegexNotMatch
        value: '^/stac/collections/ws-.*'
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
        headers:
          set:
            X-Forwarded-Port: "443"
            X-Forwarded-Proto: "https"
            X-Forwarded-Host: "eoapi.rke2.deploybox.co.uk"
      enable: true
    - name: cors
      enable: true
  - name: stac-open-search-route
    priority: 90
    backends:
    - serviceName: eoapi-stac-auth-proxy
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      methods:
      - GET
      - POST
      paths:
      - /stac/search
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
        headers:
          set:
            X-Forwarded-Port: "443"
            X-Forwarded-Proto: "https"
            X-Forwarded-Host: "eoapi.rke2.deploybox.co.uk"
      enable: true
    - name: cors
      enable: true
  - name: stac-mgmt-route
    priority: 90
    backends:
    - serviceName: eoapi-stac-auth-proxy
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      methods:
      - GET
      paths:
      - /stac/_mgmt/*
      - /stac/healthz*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
        headers:
          set:
            X-Forwarded-Port: "443"
            X-Forwarded-Proto: "https"
            X-Forwarded-Host: "eoapi.rke2.deploybox.co.uk"
      enable: true
    - name: cors
      enable: true
  - name: stac-protected-route
    priority: 10
    backends:
    - serviceName: eoapi-stac-auth-proxy
      servicePort: 8080
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /stac/
      - /stac/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
        headers:
          set:
            X-Forwarded-Port: "443"
            X-Forwarded-Proto: "https"
            X-Forwarded-Host: "eoapi.rke2.deploybox.co.uk"
      enable: true
    - name: openid-connect
      enable: true
      config:
        discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/openid-configuration"
        use_jwks: true
        bearer_only: false # as we want to redirect to login screen (default: false)
        set_access_token_header: true # required for subsequent OPA check (default: true)
        access_token_in_authorization_header: true # required for subsequent OPA check (default: false)
        set_id_token_header: false # not needed (default: true)
        set_userinfo_header: false # not needed (default: true)
        client_id: eoapi
        client_secret: ""
    - name: opa
      enable: true
      config:
        host: http://iam-opa.iam:8181
        policy: eoepca/dataaccess/eoapi
    - name: cors
      enable: true
  - name: docs-redirect
    backends:
    - serviceName: eoapi-doc-server
      servicePort: 80
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /docs
      - /
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /docs/
  - name: docs-route
    backends:
    - serviceName: eoapi-doc-server
      servicePort: 80
    match:
      hosts:
      - eoapi.rke2.deploybox.co.uk
      paths:
      - /docs/
      - /docs/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/docs)($|/.*)
        - $2
      enable: true
