---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-access
  namespace: data-access
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBL/KodDkP9+rKa9lHgPLZIaDHXL0OImKHPa050A7HjLDe7tQV/xueUj/nfzgmfme0PTnai7nJDZP5CvFx9G4H7oxc/tPFy4bWQ0LrpFGGYSQv4Yz+UgcODGG3wCfzU6/uqevoPBW17EumJR5cg5qdi1/TJzWWTNNLit1c/2QvtEqRK9FimhJZwC4uuhnl7Yug7EIulw7nPkimn4oHSAD8zhu9SjdAtOeWo+2lN9GkF8LXVOp9nFZNtWTX6HnmDb766vXqbeWQHpv98sc3S0l0SzSrFRY+UFbLLVHBY8eh7aSNV/VSsLr5a389bGcGmEKdhhzqlpJapK/phFLwbCvkYU2A7VLqynVgqwoa1x1OGoBBF5J/hiB7AkAlRnyK3NRPx6rfqNhA0IcdK9rMQO+qBJFUvKeT2OZMFTYS9uZq7m2qJC9OItTdxVnnIgz55m6D121A1qpxi2Z3d4v9p3thRqtu9IUm431Nd7/yXnsZa8cA0mM0pRQ/xbE+MsOyz1tn2XncZEgSHo8tKFTviIchBj8jXnlSmwiGytNssz4bor0Mxqz/jhGLeBll26feNQXdclavKy7RsyPpFP+PaofbhkDfX5fMompAExrzbJfKKxG7uhZRtfIHHWFnVYce1X/Pw7OYMPdRea67ik0rypDhmXdic5JYvfuDqtUcNlT0IkGWpiHC3KaZk70lIv2eSEFp8uuO07y9No1Y=
    AWS_SECRET_ACCESS_KEY: AgAF8o1OCHSCaCRpzXnvJyp9FNRiZ9bG4QXt4Rkl+/6Sadk5xtBSjGasoQ3uK2paQhylggxgADvHw1Cq/gmx9LsghhJkl59v5PTCB/eBLj2IY7bYO72/r1xmEo7dSUNYyPYWV4B/OrQUdrembWaBZNWVW8zIRH3VyN+FQPL4czx3fqnMdT52HndCwAK4rNrjBZAdivEAUzVk2xFQ+4I4Io/IDkwJarVFAqhdAZWxOLgzkCDOGTteoG+N8sFHdYkIy0dXrnsMQbJZSMNfhQnznb6s9BdIDTjZTeAOrhUv+5ExShjYNeVfQR3sY4rf7CQ+dvoi5ONgTLcZL6qGFjo0hUhYOjEFZgbEbwAfdRwEp/wScpiOSqyADoxR9dvPL8bGBgq3vKNQj/VODeDlGP2q0m09ZqF8WoJEPv7nojf6Yxl6tG/f0MRR6qF628/+Uru9fGdM7y+oYDruGK7dNnRp79upG7agw5LU2rs20Vnm6ZjgGwrGxoZYAfG3jMlmNcrLNbpQZBPRmFX6aT31X9ks2VAaUBuUcqUpD04x8051Je0Kq8EhvvYtlwSRWTmSWYYjpceQNVP2qcdKJ45KtpU0/cwHlJFuxt66Eig+EbICE9jtdy5NAzsYDMN9Wk79tJLmrUzkoR9fnzFkO3MocivwUPtuh+RDtE/AKXCMlSoi/qKyPeeF7acSN4pnuLkDDI/VK716gVA9SrKkstxs/E9uJXpH8WtdLp/+qsk3VBJpin8i9jUz5Xattvhp
  template:
    metadata:
      creationTimestamp: null
      name: data-access
      namespace: data-access
