---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-access
  namespace: data-access
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBNsbTCHJ1WUDyyc1D4UQW6CWOipdVOTfygNeoZSbtea/WZrTMLHKMxaWnPwWCEvSCAGJlSIVVL+5/9S24LXKaLPjas5DzR3gxtemcQm+sojU7rf5qmY/o9/PHn4kuDG23BxMfvqwZYg1bXM7KP1LTCSZLtwrDI2K0Ak6bvN1/WGBjL2Z5owLrIrVwA1fXIin3lLa7gclmPgH0nKDDkji2W3amlLymBT8f00YPdb15tftKw1NbG+6jaDW69a+hk1WsVFnEyOUqcfrK3et+W7Ayc8L0FDMhBuIn2klEEpadGX/I14fIHZ0cNtD8NnO1OGH9OAIqwhKXXlp/rtU7dXZ3W2NJpnq+EshsmAJmAhKt22rIqEZgqyN0HgcaAyh1XVuoKiTJUEHxattAguSGDQiEfmfSN1GSOgb2SDPCseuKfRYk8OnsWp0fCWZ3X9z/lLEDl2lGnnubZO6i0J1BYq46NmuSy+0evawHCX0tyHXP5GLD5A6FmeSLxuBS9o+U3M7Be2poBeDkDKtvl1YQhj9dq0Uip1PaVJszYXJSC6D1OmtxIzEH2k0YZUGeALTyaeC6OOB5Ww8URIxa3UyKVDClE/VmLWdTF7Cz0gUa50ySQ8FYMjhEN+Hx5/4L7fr5xx40u/R4rMm5x3sgckJ8Kjy7hx72uIQTw/tsK3CGrO2S9ogjqj39nCnGPqJ0Odhr2f5EPV7hN+M/M6BMLXMQ7kS/RDrNGpA==
    AWS_SECRET_ACCESS_KEY: AgAPqAGXmDs/mUGXGkaRH3bP3WenTYg0Ou1SGhKumH3vVJ/CDGvgOG+yaR22+rXrabFS9fiAeIVfd8/4QwxSXUmKH1X4SqwM+Gk0M4QccXuSBJgl6plXx2Ez+c0+5/rUeBHbad++FE5aMPQsF2SS4bsKoTtJpOLZPDRsuc1oRyvLdnJMnQzWgFUUaKRXM54fZy8u/ciQUdbdw4zBd0Q0uiAB3xxLFM3/15N3YvI1i2IiIvMZdHvmHmgsI0jwxwR9T4f95PT42Hw619oEKb9IJSGZwO8FssOMuyx4f7/4RE9fhl6tO1yzSkaA03UyIK8rW4jGEFhrSDLfZhPhAwyvotaaZ/bGTHLbDA174DCQLQdSf9IZzYwN3s7RJ8aEfC6ZkMn113i9+t+FWFpaXnwV05hJa5o9ZcDAgLcfT9RzMdcqXyZD5kg4pcsLJd/Y1RyxVNpQ7tbnTphP4G/332Myk35iXoNnWbEluo8UwREB2dB477wr39PZwwdOIg99tQsFtknYJxrCWPJFObyccGjXdDo26Yxnsu14v36MEGe15aLbFpnzXx7wN1/o4nkd2o0pei0Dh9zcIOhDY9UTt5PGymCc1Sc192IWUOUmvirF4vrG4oHhpfQDdiDxYZbc2jqSrn3ldiii/ZN8j4AEvFDZeF5ej5DutvBlKbtkUA90BBwOP3Og7s5seOwJ7gHLDwzpMOPs2RjzWFcah1zd8xAa/TVmtDwkBYikP0wgWV8BHijZpupsWVs6M0Bv
  template:
    metadata:
      creationTimestamp: null
      name: data-access
      namespace: data-access
