apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# TODO: Have two seperate configMapGenerators that generate the full urls based off the BASE_DOMAIN using replacements
configMapGenerator:
  - name: domains
    literals:
      - BASE_DOMAIN=https://vcluster-test.develop.eoepca.org

      - WORKSPACE_API_URL=workspace-api.vcluster-test.develop.eoepca.org
      - S3_ENDPOINT=https://minio.vcluster-test.develop.eoepca.org
      - HARBOR_URL=https://harbor.vcluster-test.develop.eoepca.org
      - KEYCLOAK_URL=https://keycloak.vcluster-test.develop.eoepca.org
      - IDENTITY_API_URL=https://identity-api.vcluster-test.develop.eoepca.org
      - DATA_ACCESS_URL=data-access.vcluster-test.develop.eoepca.org


replacements:
  # Workspace-API
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.WORKSPACE_API_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.ingress.hosts.0.host
          - spec.source.helm.valuesObject.workspace-api.ingress.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.S3_ENDPOINT
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.s3Endpoint
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.IDENTITY_API_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.keycloakIntegration.identityApiUrl
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.KEYCLOAK_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.keycloakIntegration.keycloakUrl
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.HARBOR_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.harborUrl


  # Data Access
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.DATA_ACCESS_URL
    targets:
      - select:
          kind: Application
          name: data-access
        fieldPaths:
          - spec.source.helm.parameters.0.value
          - spec.source.helm.parameters.1.value
