apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: domains
    literals:
      # Workspace-API
      - WORKSPACE_API_URL=workspace-api.vcluster-test.develop.eoepca.org
      
      # Minio
      - S3_ENDPOINT=https://minio.vcluster-test.develop.eoepca.org

      # Harbor
      - HARBOR_URL=harbor.vcluster-test.develop.eoepca.org
      - HARBOR_FULL_URL=https://harbor.vcluster-test.develop.eoepca.org
      
      # Keycloak
      - KEYCLOAK_URL=keycloak.vcluster-test.develop.eoepca.org
      - KEYCLOAK_FULL_URL=https://keycloak.vcluster-test.develop.eoepca.org
      
      # Identity API
      - IDENTITY_API_URL=identity-api.vcluster-test.develop.eoepca.org
      - IDENTITY_API_FULL_URL=https://identity-api.vcluster-test.develop.eoepca.org
      
      # Data Access
      - DATA_ACCESS_URL=data-access.vcluster-test.develop.eoepca.org

      # Registration API
      - REGISTRATION_API_URL=registration-api.vcluster-test.develop.eoepca.org
      - REGISTRATION_API_FULL_URL=https://registration-api.vcluster-test.develop.eoepca.org

      # Resource Catalogue
      - RESOURCE_CATALOGUE_URL=resource-catalogue.vcluster-test.develop.eoepca.org
      - RESOURCE_CATALOGUE_FULL_URL=https://resource-catalogue.vcluster-test.develop.eoepca.org

      # Zoo
      - ZOO_URL=zoo.vcluster-test.develop.eoepca.org
      - ZOO_FULL_URL=https://zoo.vcluster-test.develop.eoepca.org

replacements:
  # Workspace-API
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.WORKSPACE_API_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.ingress.hosts.0.host
          - spec.source.helm.valuesObject.workspace-api.ingress.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.S3_ENDPOINT
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.s3Endpoint
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.IDENTITY_API_FULL_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.keycloakIntegration.identityApiUrl
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.KEYCLOAK_FULL_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.keycloakIntegration.keycloakUrl
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.HARBOR_FULL_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.harborUrl


  # Data Access
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.DATA_ACCESS_URL
    targets:
      - select:
          kind: Application
          name: data-access
        fieldPaths:
          - spec.source.helm.parameters.0.value
          - spec.source.helm.parameters.1.value

  # Harbor
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.HARBOR_URL
    targets:
      - select:
          kind: Application
          name: harbor
        fieldPaths:
          - spec.source.helm.valuesObject.expose.ingress.hosts.core


  # Keycloak Service
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.KEYCLOAK_URL
    targets:
      - select:
          kind: Application
          name: identity-service
        fieldPaths:
          - spec.source.helm.parameters.0.value
          - spec.source.helm.parameters.1.value
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.KEYCLOAK_FULL_URL
    targets:
      - select:
          kind: Application
          name: identity-service
        fieldPaths:
          - spec.source.helm.parameters.2.value
  
  # Identity API
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.IDENTITY_API_URL
    targets:
      - select:
          kind: Application
          name: identity-service
        fieldPaths:
          - spec.source.helm.parameters.4.value
        
  # Registration API
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.REGISTRATION_API_URL
    targets:
      - select:
          kind: Application
          name: registration-api
        fieldPaths:
          - spec.source.helm.valuesObject.ingress.hosts.0.host
          - spec.source.helm.valuesObject.ingress.tls.0.hosts.0

  # Resource Catalogue
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.RESOURCE_CATALOGUE_URL
    targets:
      - select:
          kind: Application
          name: resource-catalogue
        fieldPaths:
          - spec.source.helm.valuesObject.ingress.host
          - spec.source.helm.valuesObject.ingress.tls_host

  # Zoo
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.ZOO_URL
    targets:
      - select:
          kind: Application
          name: zoo-project-dru
        fieldPaths:
          - spec.sources.0.helm.parameters.1.value
          - spec.sources.0.helm.parameters.2.value
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.ZOO_FULL_URL
    targets:
      - select:
          kind: Application
          name: zoo-project-dru
        fieldPaths:
          - spec.sources.0.helm.parameters.0.value
