apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# TODO: Have two seperate configMapGenerators that generate the full urls based off the BASE_DOMAIN using replacements
configMapGenerator:
  - name: domains
    literals:
      - BASE_DOMAIN=https://vcluster-test.develop.eoepca.org

      - WORKSPACE_API_URL=workspace-api.vcluster-test.develop.eoepca.org
      - S3_ENDPOINT=https://minio.vcluster-test.develop.eoepca.org
      - HARBOR_URL=https://harbor.vcluster-test.develop.eoepca.org
      - KEYCLOAK_URL=https://keycloak.vcluster-test.develop.eoepca.org
      - IDENTITY_API_URL=https://identity-api.vcluster-test.develop.eoepca.org
  
  - name: secrets
    literals:
      - HARBOR_SECRET=IONWINGREAgAE3L+v+dF3XZjDil+YecLpUIc2eeFJCzvu8lRjbNiJGy3fw3qHu5Q8WmYR/Eq8ZZDz1nVQf1GJYo7dRHCXSthWQ/nBo6zNVGRkNFkLQhXPq1apTO5RVXMJ9unE2jP3cq6JhphSOe8afjwERuceX4rXF8wuNr7THk9vvn/pJnDWDTpzgxsQsaBpwrqKKoFGzxGrE39bLvcZ8INhDCoamJPoqMfwJxovyZ/+RNIYi6GZnDp3+WhKzkFtsrUgV8fxVhoE8YW3CG3jDzZJWIPre+awff9bjROWDCQ5TjxNQnSfThmqt6mSaTlLOwMNT54jAQx7vVcVtXPcYiOVlq1DHY6ZaG+F38OQ0PmoXx0oiVFQEleKASBJFdJ0hbyChHdO2wnes1v8OTxF3Op3TkSJacsQGnPYIGNz5i/A69WSA2MKSQfeuZIOqKi+cq3YGm6BDzooXMn7VVyCXU3XJ6Hcx++Nf+NMUElJ4YJ8z2oA4AVzBKxn3vbtY6AvTyrVel4HH169Ak8mUVarrSc0v+C6HmnFYJ43mBRYAEPk8ghSE4QDoQLhR74w+WmSIlEhVDdiJbibuHE4gNiHOMpISD+XKiVqZE9vPnZpmJcU72WQtPBmQB0OUR+StKC0TxwWWTt1UoFpfLyDDCT9k4f4sZGcMGtmfjnq2VkjaG0fPlMM+w/WnSqAngezMPOeVhonjOqzkFafdekCMsz5uLM3OINERGIONRG



replacements:
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.WORKSPACE_API_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.ingress.hosts.0.host
          - spec.source.helm.valuesObject.workspace-api.ingress.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.S3_ENDPOINT
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.s3Endpoint
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.IDENTITY_API_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.keycloakIntegration.identityApiUrl
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.KEYCLOAK_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.keycloakIntegration.keycloakUrl
  - source:
      kind: ConfigMap
      name: domains
      namespace: default
      fieldPath: data.HARBOR_URL
    targets:
      - select:
          kind: Application
          name: workspace-api
          namespace: argocd
        fieldPaths:
          - spec.source.helm.valuesObject.workspace-api.harborUrl
  - source:
      kind: ConfigMap
      name: secrets
      namespace: default
      fieldPath: data.HARBOR_SECRET
    targets:
      - select:
          kind: SealedSecret
          name: harbor
        fieldPaths:
          - spec.encryptedData.HARBOR_ADMIN_PASSWORD