apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-api
spec:
  source:
    helm:
      valuesObject:
        workspace-api:
          ingress:
            hosts:
              - host: "workspace-api.$(BASE_DOMAIN)"
                paths: ["/"]
            tls:
              - hosts:
                  - "workspace-api.$(BASE_DOMAIN)"
                secretName: "workspace-api-tls"
