apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: eoepca
  source:
    repoURL: 'https://github.com/EOEPCA/eoepca-plus'
    targetRevision: rke2-upgrade
    path: argocd/infra/cert-manager/parts
  destination:
    name: in-cluster
    namespace: cert-manager-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true