harvester:
  image:
    repository: eoepca/registration-harvester
    pullPolicy: Always
    tag: 2.1.0-rc1
  secret:
    name: registration-harvester-secret
  config:
    log_level: INFO
    bpm_engine:
      url: https://registration-harvester-bpm-engine.develop-v2.eoepca.org/engine-rest
      lock_duration: 300000  # 5 minutes
      retries: 3
      retry_timeout: 30000  # 30 seconds
      async_response_timeout: 30000 # 30 seconds
      timeout_delta_millis: 30000 # 30 seconds
      sleep_seconds: 15
      http_timeout_millis: 420000 # 7 minutes
    iam:
      enabled: true
      oidc_token_endpoint_url: https://develop-v2.eoepca.org/iam/auth/realms/eoepca/protocol/openid-connect/token    
    topics:
      landsat_ondemand_discovery:
        module: worker.landsat.tasks
        handler: LandsatDiscoverHandler
        lock_duration: 1800000  # 30 minutes
        workers: 1
        parallel_tasks: 1
      landsat_continuous_discovery:
        module: worker.landsat.tasks
        handler: LandsatContinuousDiscoveryHandler
        lock_duration: 1800000  # 30 minutes
        workers: 1
        parallel_tasks: 1
      landsat_download_scene:
        module: worker.landsat.tasks
        handler: LandsatDownloadHandler
        lock_duration: 1800000  # 30 minutes
        workers: 1
        parallel_tasks: 1
      landsat_unpack:
        module: worker.landsat.tasks
        handler: LandsatUntarHandler
        lock_duration: 300000  # 5 minutes
        workers: 1
        parallel_tasks: 1
      landsat_extract_metadata:
        module: worker.landsat.tasks
        handler: LandsatExtractMetadataHandler
        lock_duration: 300000  # 5 minutes
        workers: 1
        parallel_tasks: 1
      landsat_register_metadata:
        module: worker.landsat.tasks
        handler: LandsatRegisterMetadataHandler
        lock_duration: 300000  # 5 minutes
        workers: 1
        parallel_tasks: 1
    handlers:
      LandsatDiscoverHandler:
        page_size: 100
      LandsatContinuousDiscoveryHandler:
        enabled: false
        page_size: 100      
        timewindow_hours: 1
        bbox: "8,40,18,60"
        collections: landsat_ot_c2_l2
      LandsatDownloadHandler:
        download_base_dir: "/eodata/landsat"
        download_retry_wait_time_minutes: 1
        download_retry_timeout_minutes: 10
      LandsatUntarHandler:
        remove_tar: false
        create_folder: true
      LandsatRegisterMetadataHandler:
        stac_api_url: https://eoapi.develop-v2.eoepca.org/stac
        stac_file_deletion: true
        rewrite_asset_hrefs:
          prefix_from: ""
          prefix_to: "file://"
