harvester:
  image:
    repository: eoepca/registration-harvester
    pullPolicy: Always
    tag: 2.1.0-dev23
  secret:
    name: registration-harvester-secret
  config:
    log_level: INFO
    bpm_engine:
      url: https://registration-harvester-bpm-engine.develop.eoepca.org/engine-rest
      lock_duration: 300000  # 5 minutes
      retries: 3
      retry_timeout: 30000  # 30 seconds
      async_response_timeout: 30000 # 30 seconds
      timeout_delta_millis: 30000 # 30 seconds
      sleep_seconds: 15
      http_timeout_millis: 420000 # 7 minutes
    iam:
      enabled: true
      oidc_token_endpoint_url: https://iam-auth.develop.eoepca.org/realms/eoepca/protocol/openid-connect/token    
    topics:
      sentinel_ondemand_discovery:
        module: worker.sentinel.tasks
        handler: SentinelDiscoverHandler
        lock_duration: 600000   # 10 minutes
        workers: 1
        parallel_tasks: 1
      sentinel_continuous_discovery:
        module: worker.sentinel.tasks
        handler: SentinelContinuousDiscoveryHandler
        lock_duration: 600000   # 10 minutes
        workers: 1
        parallel_tasks: 1
      sentinel_download_scene:
        module: worker.sentinel.tasks
        handler: SentinelDownloadHandler
        lock_duration: 1800000  # 30 minutes
        workers: 1
        parallel_tasks: 1
      sentinel_unzip:
        module: worker.sentinel.tasks
        handler: SentinelUnzipHandler
        lock_duration: 1800000  # 30 minutes
        workers: 1
        parallel_tasks: 1
      sentinel_check_integrity:
        module: worker.sentinel.tasks
        handler: SentinelCheckIntegrityHandler
        lock_duration: 1800000  # 30 minutes
        workers: 1
        parallel_tasks: 1
      sentinel_extract_metadata:
        module: worker.sentinel.tasks
        handler: SentinelExtractMetadataHandler
        lock_duration: 600000   # 10 minutes
        workers: 1
        parallel_tasks: 1
      sentinel_register_metadata:
        module: worker.sentinel.tasks
        handler: SentinelRegisterMetadataHandler
        lock_duration: 600000   # 10 minutes
        workers: 1
        parallel_tasks: 1
    handlers:
      SentinelDiscoverHandler:
        page_size: 1000
      SentinelContinuousDiscoveryHandler:
        enabled: false
        page_size: 1000
        timewindow_hours: 1
        bbox: "8,40,18,60"
        collections: S2_MSI_L2A
      SentinelDownloadHandler:
        retryTimeout: 10
        download_base_dir: "/eodata/sentinel"
        download_retry_wait_time_minutes: 1
        download_retry_timeout_minutes: 10
      SentinelUnzipHandler:
        remove_zip: false
      SentinelCheckIntegrityHandler:
      SentinelExtractMetadataHandler:
        collections_dir: ./etc/collections
      SentinelRegisterMetadataHandler:
        stac_api_url: https://eoapi.develop.eoepca.org/stac
        stac_file_deletion: true
        rewrite_asset_hrefs:
          prefix_from: ""
          prefix_to: "file://" 
