host:
  # suspect this is not needed since it is only used by the (disabled) ingress
  external: registration-harvester-api.rke2.deploybox.co.uk

rest:
  admin:
    username: eoepca
    password: eoepca

ingress:
  enabled: false
  # useHost: "true"
  # sslRedirect: "true"
  # clusterIssuer: letsencrypt-http01-apisix

# https://github.com/bitnami/charts/tree/postgresql/12.10.0/bitnami/postgresql
global:
  storageClass: managed-nfs-storage-retain


postgresql:
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 16.4.0-debian-12-r10