---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resource-health-opensearch-admin-secret
  namespace: iam-management
spec:
  encryptedData:
    password: AgBuxRkLPHNm/0gFMuyDK8rLONrwYFcfJrIKaoRuJhZl+G2Mje6kI9ENoTmhYpqtzOCscvEBEoEWV8iFi8+SrOSbBP+hKK5KCmqBC0RWbGZs4rmYFSYIlZVVxXLUrG6jL+WNhnFhETSfYElGeNvTSd2nJnFZo6MVjwa33sYwcH30UwRqB/R1hqpmkeadKhsT7lCmuryqx2hEzB77qvGhT07urA6a/kv2B4+puPdlRTqCHZXwOBdaAcZpxkCuVVtI+Le3NSsIacVX4s3JJVi1KwO5BjMkw9hSfRfuL8dPCzXxUwQ1l40Wfo1cBPM5d2mKHy7LIxsJatlwc8OU61F1uB+FlcM/ilVuQQOWXz0R0/e7OR0Nbn1KQUsg6foRcn0G1PmW/sscevCvQP1OOd9j6UhgQ2IdpVu3kOQK+wt3j+PoBMZoTQXxupWEZnfhyMifqewVUGGgcJCqXNNl0UUId24vjOThEbv/UfwdjNBfPR6PnatLEGU+NN2eehNLtilmWShJdgB76JlTQn6LhztwvxHNye9WJSqG4s3Hg5EYU/tOF3qtGwfoN9YxHW2pqP/9+wsO85zpNVHK7WNvrJlzmjRTw8W6JDeSTq5bfIqw9cU9nNYk4Lz0qdG+KarrmkxFZlpBHoqBe56pg11SSxIjOMpPSh1vi7m5ynISRwXumKjjixNxL9L38HUO/okqaauslc1dY5aQhiEEh8ZxG/rPgRsDjg5ZTw==
  template:
    metadata:
      name: resource-health-opensearch-admin-secret
      namespace: iam-management
