apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor
  namespace: rm
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCqsAzN50C+g/4lQygZZ6jLvgDhIIY/dhmbd/h8gpcswDEni2WUOS0OZZB0CqYz5nhLuUDiandNMmZ5E5KwgspM5diLFajCtqLvLuPZ9PhqgrR1gOIzr0k9+2y6ZsTrqpPCB67EENdQDwXW5QdrSN4cVsiA9o/5gk5U9wt5YBAhUp8h8HpzEnyoeMcGPNZzwfx2I8690rpMaN9LRmYj3j5rEPVCvkLmyr/OJiSW5dO/OUAgqvP2NuXNbhtpRmcBYJ0f+aGY9mmvlIEtZcbjpUQhLMTcdwtBJI8vV9yoUMZJmbwThbf3PbDhhMMtd/UQfsly6Qhr6cuYZn7F+wE5EyD0lSY9jG/bbPMUHB2vKucU3F7GPQaM79VnB4aYw7L+69AZS0ybr9HX/oOMTLhbmzTfkwdTr3hHjopurD4rymMZHfqvuliJdAb6ZqTYEQvSksCSb8AWH4GcYzpMFHbAjS3zxUqoaQtrseVN9p5zuz2ZPwohcORpuviIYJ8PfdX7pt9GuTwVQ/sA6Yd/EctcL0KT38ruLp8wqykD6BBn5PfmpJNnxndHZNPKmIi3OL96MoHyjOcAcObG4mDr3EkeNOLO9N6Du+8iyhUKYjLWBHWzRnsW6N+TARZZiRjFw8PCMlGGbcXyKLwdr0X42prwTLm8+BYDukwbilZtu405LTjp28k5FkZhpjnDTyxBdIf8p7Cv72ktt68sug==
  template:
    metadata:
      creationTimestamp: null
      name: harbor
      namespace: rm
