apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor
  namespace: rm
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAVWg+MRSAie53hd/+pM3NVZlo1PydK00pK0e9VWJXM0sGAueAJtiAPAfwbLRKlxcTJvkJAUiJTAizhr3HJujuTubgghE2pJrieNLbfo/j9e5EA0fxhW6xWxbQ9+Raiw7SfQL+Q4NMCfYh2eaDvV22roL+v68WIGt+2+xpD6Eq58GmX9K9w8gd91eg4jEgM59J0rB6t0TjssnsuaJrWYvbXb0hOCuu6jqL0rbaHEDFNVd3nLnIWY5Ycd9f06DtgsUea5lZ89g0EL0Hauln7LLd2MWtjwdMB3byfhCRB8/2npLzLZt5MjORw+1VQRfP8HP1nDvki/sMuvSvMyViTYHDxu2h77xKcCe1ZAHcXoVUQFaJlicKXldep5o3GB/jkmVBZHHvqrb1kKIOEYNXQllJonwNOpm6JwcPtIP4vBe0hFr+Rvw7qLVfLm9BY7PfWzlwVbdnwmlUxIKWoZnmqYGr55u2LlfaeaQQxV9HLr4g4DTBYVyzlE6XV5kM+rkHvBDfOhsXDcgkGf6/8+ySxjLoeledyflIeCsiNEl+qZMU4ORL3AERSm+OwHpy6e2+bp9k3B8oeK3v8Rw55oWXkyd/26K6Ug12w56iv4RVGu/b7bvCbUPnhEqVoW5Bv6WS28rnZvR4ulGbB3NOdCLdKj4XDq8jQjt6onv70m2xqWx9h1Z03kdclD4P7+3W8OnwQuCM9unpdKdz2wg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor
      namespace: rm

