config:
  eoepca-infra:nodeImage: Ubuntu-24.04-noble
  eoepca-infra:sshUser: ubuntu
  eoepca-infra:kubernetesVersion: v1.28.7-rancher1-1

  eoepca-infra:externalNetworkID: a3e4d020-c8b4-48b5-beb1-5f0d47d06ed7 
  eoepca-infra:networkCIDR: 10.0.0.0/24

  eoepca-infra:lbMethod: ROUND_ROBIN
  eoepca-infra:floatingIpPool: MWN_pool

  eoepca-infra:controlPlaneNodeFlavour: pn56su.medium

  eoepca-infra:workerNodeCount: "2"
  eoepca-infra:workerNodeFlavour: pn56su.medium

  eoepca-infra:nfsFlavour: pn56su.medium
  eoepca-infra:nfsVolumeSize: 25

  eoepca-infra:bastionFlavour: pn56su.medium
