ingress:
  enabled: true
  className: apisix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01-apisix
    apisix.ingress.kubernetes.io/use-regex: "true"
    k8s.apisix.apache.org/upstream-read-timeout: "600s"
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    argocd.argoproj.io/ignore-healthcheck: "true"
  hosts:
    - host: datacube-access.develop-v2.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
      - datacube-access.develop-v2.eoepca.org
    secretName: datacube-access-tls
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
config:
  dataBackend: https://eoapi.develop-v2.eoepca.org/stac/
