---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resource-health-alerting-user-emails
  namespace: resource-health
spec:
  encryptedData:
    alert_user_emails.json: AgAqY0yy+15qxkzM5aXnkb5BtzrbpgLng7MbxNsHujAZKE6cBl+Go1mfNNv1y7kMuMCZwFrCyxcBd7S31NRjQIvVlCnXSpG7YVQgqt4vWVRFrC1C5MDyPss2DaxrfxvEK88I9S+HZSKxO5q3fYKolRToO+/Mpu9oPrfY72nV/aQgA5/g6tC4SDjDfAtR6DmvQBN575wlPF8bg5smIQ9A7mXi/17iUfxmcv2Irt/BxW5qPwettnMTi2Nv2gCJOx6i+kvYb15lacY2iueMA0yw8aP3aRMMJ3XIefzjFFGe5XptmtUnbU1stXDsImWxPpgxQu1ZA4ltW406tAPAoE8cqmLWTu3NH/ENBvi7pljF7QGbnPlZCvp0574U9EmyyoAPuI2O4g9Yx4Vo+TJK0FD7IMwubFXIgcYGTqCwyiXcng+8ird9RTA0RTo8K74o+VQSQATdXuhUFd7YtKIARJA1Y6HhkVO3ZYcngTi17Kkb9cqS8I/DlyEAGMN2tMu8mJC8d0zFbCHdM2qJiaANWl43M7O1Dc1sP07jPXOd6m+Zp0X/vV5Di5ok5NTL6WbUjhYxrhbyYmh/kCT+37dxNzb82xSwGBcgEmoF61j2Kgs9IBCPXrgGM7PFVAhTZtISi5ACqLkBDCgXIpgTWJaVWGJoIme93qSwSgcECeFdJFQ705P60sOH6JFgx/5/ZvT7P7KIpNWoN81dpXXvlyqoUrYV5Kl36g9w5qEZMslr5NSoA16vroNxfyPbv+3rBZWmLXnD6qJHpmv9UUr7cJUq4bOQBnwe09jirfDLuz6pZ5g32YftFuwClNQhKbNgOawBqs9curgkTbYAC+3R0ZEWM57j9hG/gcuHUcb9NL6Dsl0mVaMPcajLhgs=
  template:
    metadata:
      name: resource-health-alerting-user-emails
      namespace: resource-health
