---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resource-health-alerting-user-emails
  namespace: resource-health
spec:
  encryptedData:
    alert_user_emails.json: AgCTK408zGJoXSMS3m/uQHYYeFVXI4tw+1sjjo8e+UNcZg+PEx1GcPjaA909vm3Ot1JKeU4xDK/9xw9152g3lHsdkkWZSd3yrXQAl2XiBAlwPbF4KQVzjT1aK6Yl/y5yZ7vmLtD6ehNFVv6fV2UGDNlwpoYZtOaqr08Nx31igXzRWJhxnuh6RStBVS+0Voy3jny1h40aYf3emmznD9+hrcYaRMTSLtEnXqIFymOp31tjz/JrZo5Lm9nxjuEDvbvB45237qCRB+wcH8QoODgSPcSxE4h/6ftdsNdCQQEbEdfPQU8J1sNArwFieBucQD5hAvqHF1XAEFJQbGo+lSQoWh1vWR06CGmquCYi74WTL2bU1PEWq9VSSyQCQ1qfku33uWWoAAcLw9BYHqvVI4NftzR3bZrLaj36MaZCtBA4R3ljJ2T8tG6IxsABGwO7S2UOf3r2hnFBCMiM7JZqfu1Gqq7xNqEs5+aSmsURY4NUmi/k3cjSDc537nTTmNcTitaWxFANRaGHzB30xiuT0Jrkk33BhH68n+qOVgnJRncMKm00HqPHB3exAaOpzXXXvr5wvXyvLU61c6T/Nj/T/JN8wYYBXY264ofVz7xWlslFlEV7mQ9x7UvUsMO0YuRfCPxbj5BIqy0F4u+IaGtuZcPKiKMx1FuhkY5gHSExofvDTASL/3RRdPnyztBVGKh3fL53tSAhU9oiqvs1nRKZ6U4gdR5NI1GQ8QPDNuAng0fPWx8fNU4pOIcJazb2WRNaTBHkdyn0Dd0xUuFsAKN4PuHWBaVO81yKyBsGvRqjNb+yu/QY+YH0JksyNxUv20srbmJPuuU4q5+ZkxMD5rCbALOIrx9luauzCX1AC03eyjUwy4iTRkrMUqs=
  template:
    metadata:
      name: resource-health-alerting-user-emails
      namespace: resource-health
