---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: resource-health-session-secret
  namespace: iam-management
spec:
  encryptedData:
    session.secret: AgBNva61tRQ62oay5/SD+b0OeKmOwX8W3wJm9z+4e3YGZZJC3tRLWKZ1V879W1LbhvePJ0qrsomxrsKuWrvF7dBuj6zGvFFEGdA5g8sx5+RIwh0YVd045zJ3I7Ow1M0ZUpev8r7cJKhKjY6NI5S5x64Mdy383gEjBJTQjct5Pk9va4iRcoYtU8deTMLkJnJzl1ym1VycyVaDamMN8SUYCr923rBZe+YyNmOA4sfvhSE4FWFH6EnZTl397TS1mIbIOnOM0GfoC59Kp/K/hVUM7ClslAYQLUs3ao9mj9LOLJWtbXPuBNC61WXyfnbY1t0wWj043YrzOjeDUu4uL2ua7VO1omSipEQsddnTECRxs4xECFHIUUhQrW1ioMVBplKPPXRYvJEfyJTS3LxLFNwpSDf/QqOLpimF94mWl9PyGqjI2naMst0EyNpCaxFpQ85U1kNoMF1qdOQo2fn3hHAg0A86MEUj9/ukzstBIStuojw7MHGwuAulDTTnF92UgWDs24xp+FFIfw0uUzn8zcUiHR2PzEFGQUZmHdL6h2Cak6Ovwz+MTMhTe8+jgmDdUqeeEMtLjVknqredCmXXHG3H+Ut0CLCgx4nHT0yA2e1h4G2YCAAF5VsjEY8rAG+LZIQ+UO3Rhw4ownjMUoStCd904rM6VtHBtep9BCo32C0Ce3mo+LlnFdud4KR2U9pJXaf6rBSONDi991JCUQaIyjYc93GAdGxYH9+tQVPL5d/KM4kVuw==
  template:
    metadata:
      creationTimestamp: null
      name: resource-health-session-secret
      namespace: iam-management
