apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access-v1x-core
  namespace: argocd
  labels:
    eoepca/app-name: data-access-v1x
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://eoepca.github.io/helm-charts
      chart: data-access
      targetRevision: 1.4.1
      helm:
        releaseName: data-access-v1x
        valueFiles:
          - $values/argocd/eoepca/data-access-v1x/parts/values/values-core.yaml
          - $values/argocd/eoepca/data-access-v1x/parts/values/values-creodias-data.yaml
          - $values/argocd/eoepca/data-access-v1x/parts/values/values-harvester.yaml
        valuesObject:
          existingSecret: data-access-v1x-secrets
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
