apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access-v1x-protection
  namespace: argocd
  labels:
    eoepca/app-name: resource-catalogue
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://eoepca.github.io/helm-charts
      chart: identity-gatekeeper
      targetRevision: 1.0.13
      helm:
        releaseName: data-access-v1x-protection
        valuesObject:
          fullnameOverride: data-access-v1x-protection
          config:
            client-id: data-access-v1x
            discovery-url: https://keycloak-v1x.develop.eoepca.org/realms/master
            cookie-domain: develop.eoepca.org
          targetService:
            host: data-access-v1x.develop.eoepca.org
            name: data-access-v1x-renderer
            port:
              number: 80
          # Values for secret 'data-access-v1x-protection'
          secrets:
            # Note - if ommitted, these can instead be set by creating the secret independently.
            clientSecret: "changeme"
            encryptionKey: "changemechangeme"
          ingress:
            enabled: true
            className: nginx
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
              nginx.ingress.kubernetes.io/enable-cors: "true"
              nginx.ingress.kubernetes.io/rewrite-target: /$1
            # open access to swagger docs
            openUri:
              - ^.*

            # Routes proxied to services
            hosts:
              - host: data-access-v1x.develop.eoepca.org
                paths:
                  - path: /(ows.*|opensearch.*|coverages/metadata.*|admin.*)
                    pathType: Prefix
                    backend:
                      service:
                        name: data-access-v1x-renderer
                        port:
                          number: 80
                  - path: /cache/(.*)
                    pathType: Prefix
                    backend:
                      service:
                        name: data-access-v1x-cache
                        port:
                          number: 80
                  - path: /(.*)
                    pathType: Prefix
                    backend:
                      service:
                        name: data-access-v1x-client
                        port:
                          number: 80

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
