apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-access-v1x-secrets
  namespace: rm
spec:
  encryptedData:
    CREODIAS_EODATA_S3_ACCESS_KEY: AgB48MKGVV9RHnIgwRKg1ZTkbOJ5YebA03WWgP6lw8jk+VmTMin8/EteDRS0PMkNkXuyZM1ceKismjzHdf8MexX1L6xkKElx3RBGAaIUWBiWvHbt9l6jfX6kSOqA8k4EhyAku6cwhGX3eyodHWhrSz9XsHEQNmW/P13mUkwP4nVbIgp3cR0g7zmqAU99+VL5fvw5sm1nhpg3rWnuDgfchrvlBbqeoQgWpIRizNUeEj4LUDNrnxCm4xL5AxB6Hi44CcHa97xGbizkI19xGi4lizwpRi5ohBXxrU7e4KDJhyCDJCGiMN7Hv8NqmgMLGVBryD+sfvQ5EEM2kkMroiBLDG+HTzSxDlNQJ4nnVaJmI93T6FG3J6MeuusO1LIIxMDQJDz2Eb8ToNauc93QQh0kBecDQzVTBFAawdFWmm3J2Ob2AiSozMVym3qwZFjKcWVnI1KzRKFnKjWuIwcxFb5/TrW83FQdHGW6Fd1LjyYJu2a1dZFGmKvUHQUd1J85mJ1ZtncVzKvz38zk/eGd1HTwgdtCnRnLPDgt4am/Si2a1jyEC6PZgE2zX955zlDUxufV66CSSEpeLT7fZUGPZihNPoEqUlSBXwRqmqz55+sUpmsExQKZszbl3MUMX1qJjF51fdZIipEqA6mSAjTnXz5G1k/pcENm30c2wE4XzaL0S1kbOSxzu4RJK0K9DtZmOjhbksqO0Q/MVXU=
    CREODIAS_EODATA_S3_ACCESS_SECRET: AgBf9AZOFIiCArmtwTLqJqX7ThF5q/o+b/cfQXo8BRxV/e06MyYQdx8TgW28L5VHs5CUkpv+TvhvFarQb4la/w8O9ID8/0ecv/LnsseLdSkys6GleeVVmUTRWwDv6KPQktcyvOZTM13w/DI9SdbONEvHFiRK4pOaJQwLKaocCgRKLDlzkGF7cBAJVelHsXvOuQ078XlU3otwVJqqPyHbtRCVYJR3ZADsTF1s6GY2gLJvwMMJGT4Q1Ru6+YiexN+uSqr9EDcr6zrhw7+BYcxerTPMHRw/Hplr+Qy3c75d4OfJvSu2zoZxpA/CZfnboUe48+aJ56w+QNLrzuYaFIk3WlvfNKL89U5OniKrQTdhXLjhO+yWbLw0Sx3IsBVQ9Ytj0pF72aPTnroIXaOLziPkf7a/HHZ3sU1qixqK6ol2yWKS6GjS8oB+kQ8Hflw09go0XcHRa9jRus5vYi3d7WSq/gfq9JSEI4FJKYl0Wc6CjbuNsPl/Y9qJswRxaalkM69bD9fjqjZuCVpgRSGP8E4YYVAZs/rofB7toMSDF+eMQr3wEfAKd/3Wnh0P0TTD3cbqS27gp5ece/1/S/jTloWSFe4ZYiY9q4r+rW+drVM+Jb6b8iLCxXTHdnVx7vz0bA2N6sMv41NsK2hV1sBZbQjokMZ7pSrpijS6jWVefBXq2trKl2XrSsNFqBK+v8cNx35mTdlJgrkeOHv61w==
  template:
    metadata:
      creationTimestamp: null
      name: data-access-v1x-secrets
      namespace: rm

