apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-service
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: 5Gi
