---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zoo-session-secret
  namespace: iam-management
spec:
  encryptedData:
    session.secret: AgBGBLDfld1LwHMEsYojyWC3jdsAw0hnUj3OhCva/pc9A19ldl8vEt7+6Hvki8rqYaGh6HBzxdXJDtcKLIXRhkmqeyitGIa3f7M98kx651gMSUp7iR+TEBnoGx7EQ9uEVENWqWVStc5UD8ko7S7Zf2HB+lNHkOiWQ/MFVuSvI8uivVHDzV3MWTj/dh5WPEmWDgPQZP6ivJMqq1S71zcyFK0dv67HYn3hXUZXga32AeqP3ZXzx1qVIYudYS9yt6+AajNjSIygAStbuCyHR28XVFSf9g4JdErRRIYJpoRKdQ03z23ts0Ei2wdVgJmaDRrdyIqz6/uMyNC0dPcTi0gJRZxahqITS9QUXpia7zCW3HLKYG4u5pEIiNk6bb/qBII5lfEgZVVhwM/mRuVAPl/NN/JVJ9hFH7sq6IAmTD69Cmn/aTuwSaTaxDzhT2UEwtFIdVF8VgV6xuEagBvO00ARSCtkM41rP0btz3LX1CeIP5Mk8KlctJaikgcv9SIihMopYn64NMO0phwuscRVVOBzINkFfokRUE/3UXXMGxzZ40y8HatogUzapdLu0tofS1Ur+li0o6oYQ135SnkjE7p/iqSC0EAZltOBaZOqO4m7/rHE9PuwjVaVC1cgJQYYZkLJzmylL6DLFWprIzRdLhqAW3YvEV2cg4guujeotKVRCCEWmoTEIWQTrEcCrlN61aAoxG6YEIMeuEp6idYfDSlQsQ0o5Urah4fyd5D/T+4CcPDhtw==
  template:
    metadata:
      creationTimestamp: null
      name: zoo-session-secret
      namespace: iam-management
