---
#---
# NOTE: This `latest` image seems broken, so reverting to a snapshot image
# that seems to work (snapshot for eoepca release 2.0-beta2)...
image: vito-docker.artifactory.vgt.vito.be/openeo-geotrellis-kube
imageVersion: latest
#image: eoepca/openeo-geotrellis-kube
#imageVersion: 2.0-beta2
#---
imagePullPolicy: Always
sparkVersion: 3.2.0
configMaps:
  backendConfig: |
    from pathlib import Path


    from openeo_driver.users.oidc import OidcProvider
    from openeogeotrellis.config import GpsBackendConfig
    from openeogeotrellis.deploy import (
        build_gps_backend_deploy_metadata,
        find_geotrellis_jars,
    )


    capabilities_deploy_metadata = build_gps_backend_deploy_metadata(
        packages=[
            "openeo",
            "openeo_driver",
            "openeo-geopyspark",
            "openeo_udf",
            "geopyspark",
        ],
        jar_paths=find_geotrellis_jars(extra_search_locations=[Path("/opt")]),
    )

    oidc_providers = [
        OidcProvider(
            id="egi",
            title="EGI Check-in",
            issuer="https://aai.egi.eu/auth/realms/egi/",
            scopes=["openid", "email"],
            default_clients=[
                {
                    "id": "vito-default-client",
                    "grant_types": [
                        "authorization_code+pkce",
                        "urn:ietf:params:oauth:grant-type:device_code+pkce",
                        "refresh_token",
                    ],
                    "redirect_urls": ["https://editor.openeo.org"],
                }
            ],
        ),
        OidcProvider(
            id="CDSE",
            title="Copernicus Data Space Ecosystem",
            issuer="https://identity.dataspace.copernicus.eu/auth/realms/CDSE/",
            scopes=["openid", "email"],
            default_clients=[
                {
                    "id": "cdse-public",
                    "grant_types": [
                        "authorization_code+pkce",
                        "urn:ietf:params:oauth:grant-type:device_code+pkce",
                        "refresh_token",
                    ],
                    "redirect_urls": ["https://editor.openeo.org"],
                },
            ],
        ),
        OidcProvider(
            id="egi-dev",
            title="EGI Check-in (dev)",
            issuer="https://aai-dev.egi.eu/auth/realms/egi/",
            default_clients=[
                {
                    "id": "openeo-eoepca-demo",
                    "grant_types": [
                        "authorization_code+pkce",
                        "urn:ietf:params:oauth:grant-type:device_code+pkce",
                        "refresh_token",
                    ],
                    "redirect_urls": ["https://editor.openeo.org"],
                }
            ],
        ),
        OidcProvider(
            id="eoepca-iam",
            title="EOEPCA",
            issuer="https://iam-auth.develop.eoepca.org/realms/eoepca/",
            default_clients=[
                {
                    "id": "openeo-default-client",
                    "grant_types": [
                        "authorization_code+pkce",
                        "urn:ietf:params:oauth:grant-type:device_code+pkce",
                        "refresh_token",
                    ],
                    "redirect_urls": ["https://editor.openeo.org"],
                }
            ],
        ),
    ]

    config = GpsBackendConfig(
        id="eoepca-openeo-demo",
        capabilities_title="Demo openEO/EOEPCA+ service (GeoPySpark)",
        capabilities_description="openEO backend based on GeoPyspark stack for EOEPCA+ demo",
        capabilities_deploy_metadata=capabilities_deploy_metadata,
        oidc_providers=oidc_providers,
        enable_basic_auth=True,
        valid_basic_auth=lambda u, p: p == f"{u}123",
    )
  layerCatalog: |
    [
      {
        "id": "TestCollection-LonLat16x16",
        "description": "[DEBUGGING] Fast and predictable layer for debugging purposes. One sample every 5 days. Resolution will vary, to always output 16x16 pixels.",
        "experimental": true,
        "_vito": {"data_source": {"type": "testing"}},
        "cube:dimensions": {
          "x": {"type": "spatial", "axis": "x", "reference_system": 4326},
          "y": {"type": "spatial", "axis": "y", "reference_system": 4326},
          "t": {"type": "temporal"},
          "bands": {
            "type": "bands",
            "values": [
              "Flat:0",
              "Flat:1",
              "Flat:2",
              "TileCol",
              "TileRow",
              "TileColRow:10",
              "Longitude",
              "Latitude",
              "Year",
              "Month",
              "Day"
            ]
          }
        },
        "extent": {
          "spatial": {"bbox": [[-180, -56, 180, 83]]},
          "temporal": {"interval": [["2000-01-01", null]]}
        }
      }
    ]
  log4j2: |
    <Configuration>
        <Appenders>
            <Console name="stdout" target="SYSTEM_OUT">
                <JsonTemplateLayout eventTemplateUri="classpath:OpenEOJsonLogLayout.json"  locationInfoEnabled="true"/>
                <Filters>
                    <!-- this filter allows to print 1 log (maxBurst) every minute (rate) -->
                    <BurstFilter level="warn" rate="0.0166" maxBurst="1"/>
                </Filters>
            </Console>
        </Appenders>
        <Loggers>
            <Logger name="org.openeo.geotrellis.OpenEOProcessScriptBuilder" level="warn"/>
            <Logger name="com.amazonaws.latency" level="warn"/>
            <Logger name="com.amazonaws.request" level="warn"/>
            <Logger name="org.apache.curator" level="warn"/>
            <Logger name="org.apache.hadoop" level="error"/>
            <Logger name="org.apache.spark" level="info"/>
            <Logger name="org.apache.spark.deploy.yarn.ApplicationMaster" level="off"/> <!-- Ignore this: "User application exited with status 1" -->
            <Logger name="org.apache.spark.executor.Executor" level="info"/>
            <Logger name="org.apache.spark.network.server.TransportRequestHandler" level="off"/> <!-- Ignore this: "Could not find CoarseGrainedScheduler." -->
            <Logger name="org.apache.spark.scheduler.TaskSetManager" level="warn"/>
            <Logger name="org.apache.spark.storage.DiskBlockObjectWriter" level="off"/>
            <Logger name="org.apache.zookeeper" level="warn"/>
            <Logger name="org.apache.zookeeper.ClientCnxn" level="error"/> <!-- Ignore this: "Unable to read additional data from server sessionid 0x..., likely server has closed socket" -->
            <Logger name="org.openeo.geotrellis.layers.OpenSearch" level="debug"/>
            <Logger name="org.sparkproject.jetty.server" level="warn"/>
            <Logger name="ucar.nc2.jni.netcdf.Nc4Iosp" level="warn"/>
            <Logger name="software.amazon.awssdk.requestId" level="warn"/>
            <Logger name="software.amazon.awssdk" level="warn"/>
            <Root level="info">
                <AppenderRef ref="stdout"/>
            </Root>
        </Loggers>
    </Configuration>
driver:
  env:
    KUBE: "true"
    KUBE_OPENEO_API_PORT: "50001"
    PYTHONPATH: $PYTHONPATH:/opt/tensorflow/python38/2.3.0/:/opt/openeo/lib/python3.8/site-packages/
    ZOOKEEPERNODES: openeo-geotrellis-zookeeper.openeo-geotrellis.svc.cluster.local:2181
  podSecurityContext:
    fsGroup: 18585
    fsGroupChangePolicy: Always
executor:
  env:
    PYTHONPATH: $PYTHONPATH:/opt/tensorflow/python38/2.3.0/:/opt/openeo/lib/python3.8/site-packages/
existingConfigMaps: false
fileDependencies:
  - local:///opt/layercatalog.json
  - local:///opt/log4j2.xml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: openeo.develop.eoepca.org
      paths:
        - /
  tls:
    - hosts:
        - openeo.develop.eoepca.org
      secretName: openeo-geotrellis-openeo-sparkapplication-cert
jarDependencies:
  - local:///opt/geotrellis-extensions-static.jar
  - local:///opt/geotrellis-dependencies-static.jar
mainApplicationFile: local:///opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/kube.py
sparkConf:
  spark.executorEnv.DRIVER_IMPLEMENTATION_PACKAGE: openeogeotrellis
  spark.appMasterEnv.DRIVER_IMPLEMENTATION_PACKAGE: openeogeotrellis
service:
  enabled: true
  port: 50001
ha:
  enabled: false
rbac:
  create: true
  role:
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - watch
      - apiGroups:
          - ""
        resources:
          - services
        verbs:
          - deletecollection
          - list
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - create
          - delete
          - deletecollection
          - list
      - apiGroups:
          - sparkoperator.k8s.io
        resources:
          - sparkapplications
        verbs:
          - create
          - delete
          - get
          - list
      - apiGroups:
          - ""
        resources:
          - persistentvolumeclaims
        verbs:
          - create
          - delete
          - deletecollection
          - list
  serviceAccountDriver: openeo
