---
image:
  registry: vito-docker.artifactory.vgt.vito.be
  repository: spark-operator
  tag: "v1beta2-2.3.0-4.0.0-json"
hook:
  upgradeCrd: true
  forceConflictsCrd: true
certManager:
  enable: true
  duration: 6000h
  renewBefore: 2000h
controller:
  logEncoder: json
  batchScheduler:
    enable: true
  podMonitor:
    create: false
  uiIngress:
    enable: false
  resources:
    requests:
      cpu: 200m
webhook:
  logEncoder: json
  resources:
    requests:
      cpu: 300m
spark:
  jobNamespaces:
    - ""
