resources:
  - alertmanagerconfig-keep.yaml
  - app-keep.yaml
  - app-keep-oauth2-proxy.yaml
  - iam.yaml
  - keep-alertmanager-relay.yaml
  - secret-keep-oauth2-proxy-cookie.yaml
  - secret-keep-auth-secrets.yaml
  - routes.yaml

patches:
  - target:
      group: argoproj.io
      kind: Application
      name: ^keep$
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: keep
        annotations:
          argocd.argoproj.io/sync-wave: "10"
  - target:
      group: argoproj.io
      kind: Application
      name: ^keep-oauth2-proxy$
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: keep-oauth2-proxy
        annotations:
          argocd.argoproj.io/sync-wave: "20"
