---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: openeo-route
  namespace: openeo
spec:
  http:
    # Open access to OpenEO API documentation and discovery endpoints
    - name: openeo-docs
      match:
        hosts:
          - openeo-eurac.develop.eoepca.org
        paths:
          - /*
        exprs:
          - subject:
              scope: Path
              name: uri
            op: RegexMatch
            value: "^/(\\.well-known.*|openeo/1\\.1\\.0/?$|openeo/1\\.1\\.0/\\.well-known.*|openeo/1\\.1\\.0/credentials.*|openeo/1\\.1\\.0/file_formats.*|openeo/1\\.1\\.0/service_types.*|openeo/1\\.1\\.0/udf_runtimes.*|openeo/1\\.1\\.0/collections.*|openeo/1\\.1\\.0/processes.*|openeo/1\\.1\\.0/process_graphs.*|openeo/1\\.1\\.0/conformance.*)"
      backends:
        - serviceName: openeo-openeo-argo
          servicePort: 8000
      plugins:
        # Allow CORS access
        - name: cors
          enable: true
    # Authorized access to OpenEO protected endpoints (jobs, files)
    - name: openeo-protected
      match:
        hosts:
          - openeo-eurac.develop.eoepca.org
        paths:
          - /openeo/1.1.0/jobs*
          - /openeo/1.1.0/files*
          - /openeo/1.1.0/me*
      backends:
        - serviceName: openeo-openeo-argo
          servicePort: 8000
      plugins:
        # Authn - expect JWT in Authorization: Bearer header
        - name: openid-connect
          enable: true
          config:
            client_id: "openeo-apisix"
            client_secret: "fdeb5f95-b913-45f9-8736-afb618601ad3"
            discovery: "https://edp-portal.eurac.edu/auth/realms/edp/.well-known/openid-configuration"
            realm: edp
            use_jwks: true
            bearer_only: false
            set_access_token_header: true
            access_token_in_authorization_header: true
        # Allow CORS access
        - name: cors
          enable: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openeo-tls
  namespace: openeo
spec:
  dnsNames:
    - openeo-eurac.develop.eoepca.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-prod
  secretName: openeo-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: openeo
  namespace: openeo
spec:
  hosts:
    - openeo-eurac.develop.eoepca.org
  secret:
    name: openeo-tls
    namespace: openeo
