apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor
  namespace: rm
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: changeme
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: harbor
      namespace: rm
    type: Opaque
