apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-certificate
  namespace: resource-health-opensearch
spec:
  secretName: opensearch-admin-certificate
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: admin.resource-health-opensearch.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: eoepca-ca-clusterissuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
