apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-certificate
  namespace: resource-health-opensearch
spec:
  secretName: otel-collector-certificate
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: otel-collector.resource-health-opensearch.svc.cluster.local
  dnsNames:
    - "opentelemetry-collector.resource-health-opensearch.svc.cluster.local"
    - "opentelemetry-collector"
  issuerRef:
    kind: ClusterIssuer
    name: eoepca-ca-clusterissuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
