apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-client-certificate
  namespace: resource-health-opensearch
spec:
  secretName: otel-collector-client-certificate
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: otel-collector.resource-health-opensearch.svc.cluster.local
  #dnsNames:
  #  - "resource-health-opensearch-dashboards.resource-health-opensearch.svc.cluster.local"
  #  - "resource-health-opensearch-dashboards"
  issuerRef:
    kind: ClusterIssuer
    name: eoepca-ca-clusterissuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
