apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
  namespace: infra
data:
  initdb.sql: |
    \c eoapi
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE EXTENSION IF NOT EXISTS btree_gist;
    CREATE EXTENSION IF NOT EXISTS unaccent;
    CREATE ROLE pgstac_admin;
    CREATE ROLE pgstac_read;
    CREATE ROLE pgstac_ingest;
    ALTER DATABASE eoapi OWNER TO eoapi;
    ALTER USER eoapi SET search_path TO pgstac, public;
    ALTER ROLE eoapi WITH CREATEROLE;
    ALTER DATABASE eoapi set search_path to pgstac, public;
    GRANT CONNECT ON DATABASE eoapi TO eoapi;
    GRANT ALL PRIVILEGES ON TABLES TO eoapi;
    GRANT ALL PRIVILEGES ON SEQUENCES TO eoapi;
    GRANT pgstac_read TO eoapi WITH ADMIN OPTION;
    GRANT pgstac_ingest TO eoapi WITH ADMIN OPTION;
    GRANT pgstac_admin TO eoapi WITH ADMIN OPTION;
    \c pycsw
    CREATE EXTENSION IF NOT EXISTS postgis;
    ALTER DATABASE pycsw OWNER TO pycsw;
    GRANT CONNECT ON DATABASE pycsw TO pycsw;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pycsw;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pycsw;
    GRANT CREATE ON SCHEMA public TO pycsw;