apiVersion: postgres-operator.crunchydata.com/v1
kind: PostgresCluster
metadata:
  name: default
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  databaseInitSQL:
    key: initdb.sql
    name: initdb
  instances:
  - name: default
    replicas: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: managed-nfs-storage-retain
  backups: {}
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: pg_stat_statements, auto_explain
        pg_hba:
        - host all all 0.0.0.0/0 md5
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  config:
    parameters:
      shared_buffers: 12GB
      work_mem: 125MB
      effective_cache_size: 20GB
      maintenance_work_mem: 3GB
      random_page_cost: "1.1"
      temp_buffers: 768MB
  port: 5432
  postGISVersion: "3.5"
  postgresVersion: 17
  monitoring:
    pgmonitor:
      exporter: {}
  users:
  - databases:
    - eoapi
    - postgres
    name: postgres
    options: SUPERUSER
  - databases:
    - eoapi
    - postgres
    name: eoapi
    options: CREATEDB CREATEROLE
    password:
      type: AlphaNumeric
  - databases:
    - pycsw
    - postgres
    name: pycsw
    options: CREATEDB CREATEROLE
    password:
      type: AlphaNumeric
