apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: infra
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - targetPort: exporter
      interval: 30s
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: default
