# Additional, manually created route for path-based routing to IAM services.
# Should be made the default later.
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: iam-pathbased-route
  namespace: iam
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  ingressClassName: apisix
  http:
  - name: keycloak
    match:
      hosts:
        - rke2.deploybox.co.uk
        - ngx.rke2.deploybox.co.uk
      paths:
        - /iam/auth
        - /iam/auth/*
    backends:
      - serviceName: iam-keycloak-operator-service
        servicePort: 8080
    plugins:
#      - name: proxy-rewrite
#        config:
#          regex_uri:
#            - ^(/iam/auth)$
#            - /
#            - ^(/iam/auth)(/.*)
#            - $2
#        enable: true
  - name: opa
    match:
      hosts:
        - rke2.deploybox.co.uk
        - ngx.rke2.deploybox.co.uk
      paths:
        - /iam/opa
        - /iam/opa/*
        - /iam/policies
        - /iam/policies/*
    backends:
      - serviceName: iam-opa
        servicePort: 8181
    plugins:
      - name: openid-connect
        enable: true
        config:
          access_token_in_authorization_header: true
          use_jwks: true
          discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/openid-configuration"
        # Note: The opa-route secret is generated by the IAM-BB Helm chart.
        secretRef: "opa-route"
      - name: proxy-rewrite
        config:
          regex_uri:
            - ^(/iam/opa|/iam/policies)$
            - /
            - ^(/iam/opa|/iam/policies)(/.*)
            - $2
        enable: true
