# Additional, manually created route for path-based routing to IAM services.
# Should be made the default later.
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: iam-pathbased-route
  namespace: iam
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  ingressClassName: apisix
  http:
  - name: keycloak
    match:
      hosts:
        - rke2.deploybox.co.uk
        - ngx.rke2.deploybox.co.uk
      paths:
        - /iam/auth
        - /iam/auth/*
    backends:
      - serviceName: iam-keycloak
        servicePort: 80
    plugins:
      - name: proxy-rewrite
        config:
          regex_uri:
            - ^(/iam/auth)$
            - /
            - ^(/iam/auth)(/.*)
            - $2
        enable: true
  - name: opa
    match:
      hosts:
        - rke2.deploybox.co.uk
        - ngx.rke2.deploybox.co.uk
      paths:
        - /iam/opa
        - /iam/opa/*
        - /iam/policies
        - /iam/policies/*
    backends:
      - serviceName: iam-opa
        servicePort: 8181
    plugins:
      # TODO: Configure client secrets through secretRef
      - name: openid-connect
        enable: true
        config:
#          client_id: "opa"
#          client_secret: "RkAUBGEzUCCgKBydiagDGqW5JJeXYdDQ"
          access_token_in_authorization_header: true
          use_jwks: true
          discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
        # Note: The opa-route secret is generated by the IAM-BB Helm chart.
        secretRef: "opa-route"
#      - name: authz-keycloak
#        enable: false
#        config:
#          client_id: "opa"
#          client_secret: "RkAUBGEzUCCgKBydiagDGqW5JJeXYdDQ"
#          discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration"
#          lazy_load_paths: true
#          ssl_verify: false
      - name: proxy-rewrite
        config:
          regex_uri:
            - ^(/iam/opa|/iam/policies)$
            - /
            - ^(/iam/opa|/iam/policies)(/.*)
            - $2
        enable: true
