# Note: This file is not needed if Keycloak is deployed via the iam-bb Helm chart,
# because the chart is able to create the route automatically.
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak-route
  namespace: iam
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  http:
  - backends:
    - serviceName: iam-keycloak
      servicePort: 80
    match:
      hosts:
      - iam-auth.develop.eoepca.org
      paths:
      - /*
    name: keycloak
# The following fix has been moved to apisixglobalrule-tls-port-correction.yaml.
#    plugins:
#      # Possible workaround for redirect-to-9443 problem that also works for HTTP
#      - name: serverless-pre-function
#        enable: true
#        config:
#          phase: "rewrite"
#          functions:
#            - "return function(conf, ctx) if tonumber(ngx.var.var_x_forwarded_port) > 9000 then ngx.var.var_x_forwarded_port = ngx.var.var_x_forwarded_port - 9000 end end"
