apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak-route
  namespace: iam
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  http:
  - backends:
    - serviceName: iam-keycloak
      servicePort: 80
    match:
      hosts:
      # Take iam as a synonym for iam-auth for now.
      - iam.develop.eoepca.org
      - iam-auth.develop.eoepca.org
      - iam-auth.apx.develop.eoepca.org
      paths:
      - /*
    name: keycloak
    plugins:
      # Possible workaround for redirect-to-9443 problem that also works for HTTP
      - name: serverless-pre-function
        enable: true
        config:
          phase: "rewrite"
          functions:
            - "return function(conf, ctx) if tonumber(ngx.var.var_x_forwarded_port) > 9000 then ngx.var.var_x_forwarded_port = ngx.var.var_x_forwarded_port - 9000 end end"
#      - name: redirect
#        enable: true
#        config:
#          http_to_https: true

# Note: Not yet sure how to structure the external view on the IAM BB.
# Alternative: Maybe make iam-auth.develop.eoepca.org/ a synonym for iam.develop.eoepca.org/auth like this:
#spec:
#  http:
#  - name: iam-auth
#    match:
#      hosts:
#        - iam-auth.develop.eoepca.org
#      paths:
#        - /*
#    backends:
#    - serviceName: keycloak
#      servicePort: 80
#    plugins:
#      - name: redirect
#        enable: true
#        config:
#          http_to_https: true
#  - name: iam
#    match:
#      hosts:
#        - iam.develop.eoepca.org
#      paths:
#        - /auth/*
#    backends:
#      - serviceName: keycloak
#        servicePort: 80
#    plugins:
#      - name: redirect
#        enable: true
#        config:
#          http_to_https: true
