# Note: This file is not needed if Identity API is deployed via the iam-bb Helm chart,
# because the chart is able to create the route automatically.
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: identity-api-route
  namespace: iam
spec:
  http:
  - name: identity-api
    match:
      hosts:
        - identity-api.rke2.deploybox.co.uk
      paths:
        - /*
    backends:
      - serviceName: identity-api
        servicePort: 8080
    plugins:
      - name: openid-connect
        enable: false
        config:
          client_id: "identity-api"
          client_secret: "eBlG9c7IEKlCJglwVC7N8EGwZArl141h"
          access_token_in_authorization_header: true
          discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/openid-configuration"
      - name: authz-keycloak
        enable: true
        config:
          client_id: "identity-api"
          client_secret: "eBlG9c7IEKlCJglwVC7N8EGwZArl141h"
          discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/uma2-configuration"
          #permissions: "Resource all"
          lazy_load_paths: true
          ssl_verify: false
