# Copied from identity-service and adapted

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-keycloak
  namespace: argocd
  labels:
    eoepca/app-name: iam-keycloak
spec:
  project: eoepca
  sources:
    - repoURL: https://eoepca.github.io/helm-charts-dev
      chart: iam-bb
      targetRevision: 2.1.0-dev1
      helm:
        #releaseName: iam-keycloak
        valueFiles:
          - $values/argocd/eoepca/iam/parts/values/iam-values.yaml
        # For now, all services are disabled by default in iam-values.yaml in order to
        # allow installing them as separate ArgoCD Applications.
        # This explicitly enables Keycloak.
        valuesObject:
          iam:
            keycloak:
              enabled: true
              # Create Crossplane Provider Config
              configuration:
                provider:
                  create: true
          iam-bb-config:
            iam:
              keycloak:
                enabled: true
                configuration:
                  provider:
                    create: true
          keycloak:
            enabled: true
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: iam
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
