# Copied from identity-service and adapted

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-apisix
  namespace: argocd
  labels:
    eoepca/app-name: iam-apisix
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
#    - repoURL: https://charts.bitnami.com/bitnami
    - repoURL: https://charts.apiseven.com
      chart: apisix
      # Bitnami:
      #targetRevision: 2.5.8
      # Apache:
      targetRevision: 2.9.0
      helm:
        releaseName: apisix
        valueFiles:
          # Bitnami:
          #- $values/argocd/eoepca/iam/parts/values/apisix-values.yaml
          # Apache:
          - $values/argocd/eoepca/iam/parts/values/apisix-values-asf.yaml
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: iam
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.versions[].additionalPrinterColumns[].priority | select(. == 0)
  syncPolicy:
    automated:
      prune: true
      #selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
