# Wildcard certificate for APISIX ingress
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apx-all
  namespace: iam
#  annotations:
#    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: apx-all-tls
#  privateKey:
#    algorithm: RSA
#    encoding: PKCS1
#    size: 2048
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.apx.develop.eoepca.org"
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
