apiVersion: user.keycloak.m.crossplane.io/v1alpha1
kind: User
metadata:
  name: eoepca-user
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    username: eoepcauser
    firstName: EOEPCA
    lastName: User
    email: eoepcauser@gmail.com
    enabled: true
    emailVerified: true
    initialPassword:
      - temporary: false
        valueSecretRef:
          name: eoepca-user
          key: eoepcauser-password
---
apiVersion: user.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: eoepca-user-roles
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    userIdRef:
      name: eoepca-user
      policy:
        resolution: Required
    roleIdsRefs:
      - name: default-roles-eoepca
        policy:
          resolution: Required
