
resources:
  - app-keycloak.yaml
  - app-opal.yaml
  - app-identity-api.yaml
#  - pvc-kc-database.yaml
  - ss-kc-postgres.yaml
  - ss-identity-api.yaml
  - ss-keycloak-provider.yaml
  - provider-config-keycloak.yaml
  # Preliminary configuration for path-based routing (to be removed later)
  - apisixroute-pathbased.yaml
  # Removing this one as it makes no sense
  # - ingress-pathbased.yaml
  - naming-workaround.yaml
  - iam-management-ns.yaml

