# Note: This is s workaround for a Bitnami oddity. A full solution does not make sense now, because we want to get rid of Bitnami charts anyway.
# The Keycloak service should be constructed as "<release_name>-keycloak", which should result in "iam-keycloak-keycloak".
# However, the Bitnami chart names the service just "iam-keycloak", because the release name contains the string "keycloak".
# This seems to be an optimization, but it leads to a name mismatch with the IAM Helm chart in this special case.

apiVersion: v1
kind: Service
metadata:
  name: iam-keycloak-keycloak
  namespace: iam
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: iam-keycloak
    app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: ClusterIP
