# realm roles with no single owning bb; grant to users/groups in the owning bb's iam.yaml
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: eoepca-user-premium
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: user-premium
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: eoepca-admin-ui
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: admin-ui
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: eoepca-user
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: user
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: default-roles-eoepca
  namespace: iam-management
  annotations:
    crossplane.io/external-name: eoepca/default-roles-eoepca
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: default-roles-eoepca
  managementPolicies:
    - Observe
