---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eoepca-realm
  namespace: iam
spec:
  encryptedData:
    github_client_secret: AgBd9EpdjT5oY+fOVCS4xMl6gsWYSd1qB9W1QaYsIkEVfOSkCYxzy/scPu8agJDa5Uzoq2+w4kvDkq5n7whMZo38V9xLBWpWG4p8IMOrQ+MQU8TNGk0MYuM8L0463Y2xJX/6146iJBAhssz4lpWmqFxQhFeiZqja5hraEAVzs5/0XSEOuVvzKop+7TMsj0Ef/onuxRp6I0zrznq7T2mtqqkgedBPbykiLEg1f/8pAv3NgOXt2HER1MRPLTPyiOIls9kv+F+coIF2xRYNOw/FSnFhiyFY2v1F2vmgSX5BdH51DrmA0XYEZWuE3eD+ICQ4ZKZJT3RmCZAUqqWWuA+qHbh/iEP19vkrO+lFUyxFF85visK046i9XnGH436a3ZczXxLrcputLfBRep66csQ5LIxxsZswZjGAQrTTZaoOzesy1GOGU39ksdzR9IZLaCHUKsS9XmWbE+TCyv+6PVcu2C0uOdmNs7AsfFLXgdoxAXHMLubVcEMUUGSVrNoW5pQiXxEjFftW/S65kM+RxoxC+ZCW7+Il7/ueoRzJcI/xvY/U43udPyIor68aeKHW2E5Di2PoL27UPMzu9xQfBt1Oxd8HqBIJX0b5Ropg+aQVQxvc027ypRKYNBP9kD4Mdrw6KcP82Lo+vhWS4qVxvQUTzIywlyoGXUT0nUoez5c10gg09n7lXCaQFMXI3lBJ76JN4D/ugSZHBAS2zYss/DomDIxdG5AVpkNxbAImdcJjGAfa6VyFz3BW/4EF
    smtp_password: AgCuomIptJuFpXHX/IOAG0hSs+4l9zW063vuyXNfFWBFM33v0GJO3eeeMn+zvQgRivHclChyjMHxygEP43R6AJ31ukCnIGE3Jp3sglwAQwGBXzTOtF2QnWRFCJxyBO9qKe1F9Eoju6xqwLPbV5722fosHEQaTPiQJXEpwADSmm8O9B8mbEfgswVf6R52Gdxy5kgF5SX29IW2/ceEPcRbQeKJV7QqaRanqcbw9rVNuvglFrZmrtx83mUiAkg3PmobINT9LnuCpHasRdjNaeeG7cXqpzaDV4i89EnvDmo/uwN1usQ6wj+JArbocBRHH7JFHsvKxbcvYeXA4SssemNhCvATUIzLsOase54KjYD9EEvEUjiP//SbQeDVlzb7XKYyfTT0WLLBA5DndPKbwuModq4tPQ887wvhtqvpKUkKY2eNmf0s+Uq16NOuVi8+gywRhZMU9G/z6kzkJDv0lmI+oiSH0iHNa6UJNB7I9DQmbRyFdc+Xxhj2UlO5zT+9y0ASuhfiZyGKDMmhHKcaUULZkcp4fgMyuqd80S8HYIm1BCaS4O2PpXKEiGK5wwX0hGJSXDLKoI/AlHkPRbEqnO7XZXRUcuxdmMOyUJHKxxi7wUvh42fjQTVNAOt/68629ukjdU4LALvDVnKAKiLHirTghaxOX4yM6Z+SwsFvKHFbgUup1sxncRHAtpnV2cN4YaQoiOtTK87uXe+FuJTnTC5L7VUnDMAe
  template:
    metadata:
      creationTimestamp: null
      name: eoepca-realm
      namespace: iam
