---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eoepca-realm
  namespace: iam
spec:
  encryptedData:
    github_client_secret: AgBNeTejlaFXnSYa9aPQMnkKaRort+URN8+s4zy+I66i4Vp2nsmOtZ5BWRLfCbgHE3IgBHmKc2oS56MNusffgpmXD6wgno7Mjb+aQ36pbg3JkS1NjdXHzgf78GW7bi1a52gfBFbdwb8LV/iBm+6fYvKukAC1AQgqQQ0Y+kNfFTkdOUlgxGsdTc66NGn6D1z56xjHfugvFrdNdiuM6FgKjkr1J4OcQlf7HF3KzqRblh6PLhh8nkff1XBVl76gkFogTuarZ74oA+cUPTiJXweQXS0eAecNhqu+vvQRSfKbroWb7kbECy9RinLdglB9JZJG3q6w7X4+Iu9fyJHLqftWZNQY5msBtOQAZsLTYv0On85heNb18BfdQuleCz6f5HrDcDt2HNUnerLrlufif0dMNU8xicgdJB2Ct1ez2zwCzlUOqybYOQl+cKRdd8ir2cxQWT2fc78fuzeI4btYjbHA/exGLo/5cmgnHMX8xdzIik8gmHL1cDE01z00bOKmipyVsu8T//9JJXdt9QJukN1WzbUvw0bp3rVwEYXlh4M6G69RLWc73+dz5et7HkXbtAVGNWAKAHSV7n0VAzNkKAz1i27ghjJxcnKLHz+fzwZmJdiqryvCPEjnGKv8RWtyvEkMc1mY+G0lWNMV9hinl17YKnPPzFMcYw3ISG/PUUdIZAisGNOnJQlhC3PVjIZo8uYNkvc6aGYrKA7yHScsZfv4kIFqUmSyMN7T8jyyUoKxrw15qecpNYhy1wfH
    smtp_password: AgAHKJbvzE/kAYLUpXBwtcW/3336PmfRHT3sux4lbafW7gVPqJh/GgdDPyBYrPGrWNlKEB226ljyCobaFuTM/1BIiL9H4Yvw8MOCoeticJyKj7gqtTtYDV2KKdv0r59dViZZqaHXtGTqJnxe7+zp8GBFNz9BIWfbdG3r49yHuk4ANxAW3UXCy6jBT5cN0w2KYASH5EHyhIcMr38ckhFtFy+CObcqNjoDbeV4+nHLs1Mx75zQxGrbh+iGNIH5PcPEBefIsnYlKtZ3vgeuETmlCeyOtezcLQ5itqoHKV5J7a3Z8F39VAQJPoQbxG2WlKVE3BrQjftSQWbMyDnrypqSaTzXewsdagOpjNnYHJzTe/fE57Hv6SZULYJ+t+Qd/hYkds3CFTcsYqHAU54JK54OTNL57EPOhQ52OVHXVEIFWYaU49b+mKasMYb4zq9ofI3RbW5hc2WFfhdoeAJ3uHGYlYWe98BI/BtyIuaDlDG9ld9B1kNMk8xvTnY1Fe6JR0/d22BVaTJMeNirbsiopRzpyYTkStJ15EXEIkBlBmLzhMs9nD6Z3hsiDYnnzVDM90Ie0tumtQ+gsXZ9GfabdPwMMz6yG83vlhHEk+ZqrcfVXsawZPkHB35z6caxfs4XZYIvJkZw7LZWMl2cpM+xTzU3lp0xkxqzWfsv47OE0YNmwIBm7ZcCBPHgujB9ItH9QwmPlXDNjEMlr6MciuqoH9LxjfFH5OCy
  template:
    metadata:
      creationTimestamp: null
      name: eoepca-realm
      namespace: iam
