---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eoepca-realm
  namespace: iam
spec:
  encryptedData:
    github_client_secret: AgBLnMU9PSRMf2BAAHPs/6Oplq/Vz8h5qrB85Esd7rWKjOeiosan6cykIdnynUErrdwGGKH+IpPkYuyHdDobqRD2YmzU4/j2M+bSkhadZd608l0zCKPYkMh+c1/a9uqhh8HZshFbhLoY6OQE+kLeWBcK6pZ+DBdIbcWXFcAZZTOFESftUX59PESVDCzr6Ze9z08cs+sxjeRCZVdosFsU04SoBESVSnXyPxhicDDkkqrrUNdFPNmzyXFesl4poF0nqvfQlGpwWratUaY1o70dBDwpn522ej0Os3ArB+Mlvifh0uc1H47VWKwDCJ31NfjvnWwBy1qIB2SzW1MK9SXYCU+/B+/KwWZRMgUDV2bUUfUOyob6wwQpmcxOQnGiseB6eJSynAiyOgkOsOXxicWxpb5BQ0XrZZHBTPurNN3roFMAUAlExDCQHB8GnOBubEbKkolOQ/yWjVWRhRDzwCt3tTrW3cjvQztsf2tg4lO7etbT99we4V7KTONF+2Wu1K3pwik++5Cre+8QB/1RDEX7tlgv1d14lpv2nBl7BhD6C3RLiQkRUj5nV8uPGRzSEUs/oZFB2pEUBNO1t/Blbn/bJ4UVpYAduIdQz2527Z6m8TnOQ/IeOO3X+c4CU3Uj4FQKyjGajoYkeCQDRE4w7kxj2IY3SmB91k++OYRnld/V2LIvsCD5lUnHzmrB4cZkbMwFv287KjXSVaLqMCoFeRK1dSJa6xEfO/B6/4nPxhIvZqRuHBwrmObPOmEL
    smtp_password: AgCT04qNTCWWEtB/6VFlU17l9koK+AB/xqAAtzfCpWqC+T2ajzvjOE3uo79cX1pZ8GXH1bUjOnr4XuUwynCAHMO6G4XnlAUeYE2QR7ToeDb8+qSxJcQD+f/XYrVMnopXr/P49LRD73ggjiPC30xpIiUMR67ZconK7m+XUJe+tnxEYUAllgwC6FcU8MVdVoBraKTGljQ6Lhshj46+AuZQft1umvyF2WRB7r7JdzKLb/20j/Cyj7aWsl86OztSIqQCNlNsso5JWfN1XFWQZxE+NGYqAPzNDAYULkUHc0QZuSFIR0G83ew41QiTr14rDohF3/vYxPlqAmBpD2UbwkcS37FoLYbJphBCIvk0q3DDv1xka0RQ8QGYRO9YdDSMhXCWS3mcrCA2YnW39My0eciz9MofH16QUsqyImTKKsRAYmp5SnEmuSSUrXtBUbMzOHwyiqW8nbx9a07CW6cyzsEvbi8Qb3kFSTfSTYkwfytbAxwkBvsBa4l9HGvLk/pjhQLrqgGimwK9YiskJ6DR71uTjVQq3OjRhpWiiGQU695aM9DyuxtY5R5e3RwmBhvKV5rGDv2hpcEU8zotb+7TbexrPrPsa7ZgdLCPEH7ltmnksdO1ji0rWP198doOh89ZiZ/0y08XYXGivOngdq0k0CnWM3cAzVfGmg+6ys/KPv/EFWcqoxejH3mAE3+krvbBCoAV4Xd349K4YoOcY7brUeCB5H9pZtrS
  template:
    metadata:
      creationTimestamp: null
      name: eoepca-realm
      namespace: iam
