---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: identity-api
  namespace: iam
spec:
  encryptedData:
    ADMIN_PASSWORD: AgC09W1I4DufzjQrE49J5IiG6H45HwWGJkgx9C6drXOwudxGZkRgvQwmozSgOV4fApfWkpNKGT2h17R3QqAysQFhwzMr/q7W/m9MagwV4Yyq8bnh6KetWkkBrtF+a57dPiCtHbtFzjARUVd/Trz3JsiaqPLvjD95pgOX4cOWXXMC/PwZ1zzBo25K/r/MySivSXewYURhXrpS3eT3YVqPG0rdOZHvXd7JKFIe9MnYIAf+VjyjGAh7tStPZ8RvVObeggyGN9fxvWg/7veRPQxo33y/SlaKiV7hNRlz/3L+AEJJLdPtfHlwGmxB+xcOCGmW2TgYbSVw5iwM51qA1wKYMsyUGSxZzp++SxCR0ZWvp5sCimChtPbAZG/vMqG5o+qsmMwT/vvOXkxUMdhYfmo+G+QSYyqiPOo7OfeXiR2bgwSSP/3ppKum3RiFZ7jjL3fiyX9sfnaNbKQArvqwNtqUnuBmeNIgcqp3BHXlAixtB7Rlhh12MtWFNkFz/sYNwBbJey9txlXokV7vLwu7iboXLGULRfUq9KTfmuADDf1OiNcenBoleFEFIEoFF26q/4UgHgWswDP5bwGbAzgCuJQgoAv5/jCwUVk5VXmORtze9a8fRb6J0M+nMCpsGHCS879Kdv0TkHShX5yZlJl2jYsBZwa6PoPvzb3lrvac+wYvzN26r9eAuiR8KFY1xG7sHdRUowdUj0ppqIjOWw==
  template:
    metadata:
      creationTimestamp: null
      name: identity-api
      namespace: iam
