---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iam-keycloak
  namespace: iam-management
spec:
  encryptedData:
    eoepca-admin-password: AgAjus2VWTJZkrHWbjp9CAkJ+XWRUi6PF2MZ/gEGojux4WevYRNxq6Qf5bt4q2JRrvb4sTrSLipVcFUVltyraBu2ycyMktRvNNKsAmvITnqOKizBcUFne7EHlM9LHl0t1JttQYG9oAk7ehbzV68sfSSAoDX31wi5rWKMtsK4toJTKq4KKOqgq2hnYr+wFoV9xDNMc3rTx9vrfZwVn+Tofx2KDKz3+rHNCDVkiAR2u7co4EgDG7OdP4WPTzH80iVU3ycBs0tlN67Ztv+1wBfDkzPsN/Puz+xsssDZbz1GFo1IWw6+xq6Hkua1ZgDgFrAynlke4YGJVbnIMRpxf8/QUtqlpG2WZ7EUqhByvFDt0Hid1II6Bm33OPbmWmRmvauUnqdxzTP4yjLVpApB1FfC22TRpblwQG6uZV/rKv/JDJ5mcKnRAq5VUgtN1Q8j+OhLWwu98lvAKBHKEE2z2TtPKpPvy4spCmV5OlpyFyafPKczKdy3mi+eZADhaMkxpFBFB2NbEMIDF7/pB96f1hz55Ti97PS9qSGVfsX+eZIUeV0IGeDJ65YELGd0AJwKsLxJH173SWagcj123N5xawlyRL+3+H82Vge8er0EM4lZvrPRAwWC+v4ao+iGW1fikbK8t0c17En0gS2knnhU1Ou7+FDrcB2eOKy1VhJrra2lwnjBPl60++ZcWSQPk+1beneXByM6fYBGFHEzKuOqBFea
  template:
    metadata:
      creationTimestamp: null
      name: iam-keycloak
      namespace: iam-management
