---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: identity-api
  namespace: iam
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCR4E98Bapyiv8hqQ8mVtCUFp99z/tzVU6M1rKgQsXvUVWnlPDodhVr/LEZlPaFYkgzRfPBXux72OKfIpFuQBrWy+QUp3JDJ/kuwrbqJsZYbAGuJgtT9XWYpuRCV7LTP7Nt93EGjDCd8xev8MNvD6BMRA2eG4UAtHfaLZjMNCUOSdmDoKn0kuAlkP9gjl58djbYZ00L0qB3/K/RYsWtQz+qKep2+mC5kB/DWHrxHrl8UebeUfaqwbCbDhXsRUx7NcBN7mglirumx5F0EaDgcjwli74vQlDlYSOyG9Xgz3g1LJbAA8+p1syiSmm1bEjT5X5CSz4MK7gR3qBZCo0UzwTP8HuNHEo4/5tHJUWzwrJOl4OsM4ZL0uBRhP/ORYaVQpgWUsJmFJj6UN2lZW8k3gGZWoEzWXfHvfjUYyRKuOdTY6HQyeZ6N5pTpKFuRMlRFhly0lzI9c9jW59N/tYrRc2dVlot6ScY3hNILcO3hfDPvcPBU9NymYlLUykP1ELXN71b1rc1geGpZLXXVitpCZxhk+RMc6SN8whQnyfrsv9xnof78kr1rraEL7hjsdJVp2qlGfmaWtyBYKEuQDx/OiHDsCUKTEdfEuhMkneSHOoyaS3pb7F8AURsRTcQRP9AWnsgQRdYXnkWraoFSsRXvJgWYpbYClU3tqeP2xIGaAowxFE0L36m88Q7+6v7Q6wDNhxWwCY3aWSELQ==
  template:
    metadata:
      creationTimestamp: null
      name: identity-api
      namespace: iam
