---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kc-postgres
  namespace: iam
spec:
  encryptedData:
    password: AgDNTHUcxNpJIQdsmbT2sPeLZqZKjLtmcmehvr9YNaNLpjBZDK3CnJwqLGiewj3sNL4sd/03x3oslzXAWTN8GUSdwZmo+37sYMWDycQMlTTUlWzPtDoR6lQSGeqhLpzXkmgJkhMA4Kr1pXkrbqinX56KkAC5WeblyM84h8VEX6HjU5C+IcVFznRsnoCcFfFbIpGRrf9HxyJZu1tSqGQ76z/yqn+O+Q4iEiXdQAswM9RIhyzMirnj5Wy7JUnNzoxEYEeBALvL3AoMQnBuPnBnVQtTNjkp1h1CDA2ouL+R6S+5D310lXO0dpitDpR3OGSm6EevetQc+W0h6LTeABWTNnV8h1QBe801MVRcjgAMLoUwpDqoq+AmY4+Zqb2rrQZyXa0uxs36jhGLSGGa15CPeTZ6/K9oVBggyx23uq5wlhrUDOengdd2tUgGqcOgibTgrf5j+Wb+t4TzklfgTVm2+mEg0zVtQkE0GaV1FCMdCX9mUMdMlu4Ee21kEW6FM2C/296AwSSh67oA2yU12mdqJgsJTE4cxTgjzWWokSJJWiwfqDWw+FMLffst0TgdRNkOp6rVDXG/bL98gDUEvL1Quw3C8zYM63kag5sjsWyySN25IHsoEnSGzH5bww595Y0F4blN4X8ggq4ypUUMPDwh6A3HCo0KfBejJMN6hUJLYAUDfGBW4SYsuGca3cc8QXr03hD8UDwthgg8ES1xOPGLeiSxqknC4+Ew5aqnWJa8ghUb+A==
    username: AgBH47qIGkrO4buBNh1MqGd9yAjQsz8lxTJKpjq6VO8hwsKmU3CpHrFT0JZ8aVnRD9MQckhKJCTysiwup55ySgQh+RHwLwV3yCvRk/yAhCce0A3DKsj/XdMfHz9GUz6oQrvdt2gcCCquYkfvXitIq8TnJe3GhDR1NZh1NVId5YRl+d3Iiw3VpZEPok5FNldIFrPLu3Tjr/hH7a/UvPIOBgksjVO9/pwVpFRO4Wr/z8Vn6WkQP828LoJtH3Gma5L+zOM+8m2GatVe5yucWbpJbH9QzJ2RDvoNsvoW1vkvR+VIZqrMcccTxZFw9qK/87gq7pHS724tBIr832BwKoXVlvyXutcLZTqqNfQaEmzezMArk4F9oJsJdqdxZ/uh3N6xHR1qDCgX5HEzzwAp4ZH7KHeTN0FY+D1nvNwD056HRAvp6GL42WIT5MAXnhi7sdhFYPulcmlBGFQDynxm/q3BPB14TooFvUFfct6RmaDKVX+/SAIlWDjOKvu/kBYSgj40SyqPdrInXsG2XoUUnT4L5TmxdTmf/mWrIIsA+YeSsjBUN3OXHVQy6KxEQamAjRtsFx7YfrXiYwvRdvCb9fZSLq3GA2VXdX1fKnjZlLQAzCyGBoG2uIWvm38DJqdgPKC6QCzJmULWrmCf3dNROBlMkdDkWZXJ4arfpvq+IFckm5aiFLdScm0wrslRHO0Ydm37shrseuvTVnLNnA==
  template:
    metadata:
      creationTimestamp: null
      name: kc-postgres
      namespace: iam
