---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kc-postgres
  namespace: iam
spec:
  encryptedData:
    password: AgAANdQj2jT7qnc3TyfFrNJ30/5rUBdrTgpWKza/JUHKKMqxd9QNTAMeZyj9S6nRxTfMDZ05Z62Rf2+H9dbyI+sCukgQH63cjutgF0dRsHRYzG5E2sCQd+9lHQkIN9cZy2dsV/ti6t8p8ofkPaIZO9LukUMzpmjCl7vgP6q8bbmp+dmChw/NVepD0P935qJkisHSR2rAsb/gIhqbvsxetDbo3U5sQ1PXUnAyrCr+U+Q/eEZ/bSDtRLvJEd/nJX+zcfG6N8RUFRUSwtQoPEfeU/Hy6AevN1kRoyrYsk5JNuy0y2q0Fy0OG/JVPbXn3tkXjVIClhrVl8IKVuvlU8RHPK+Hg9trRpUyIjubnaFN5dsM/gqnhpcqrSCwuIbRTEB2Llzy8bQyNafl6TNcjYC1Xk61wqUGoeKLpHvnJp/tj3EGUH64uCVsM3AaoCKlXHp3m3w8MO9n0zIW6/BcE6wWy8mLtfIAcMfPZ+6hpy0QCsFEU/G3tcN2z3Vgig3YE0uutpoD0+OE45xV0CJUcUQ4DuRZcCjuNuxRnfRlBQfaB+YSVA6H7dJmdO4uVVYFwKxQlxusNITRnTn2PPtpZG99eCIDiXGWjX69/pthWh1ZCz7zejTpd/gigGsLY++uN7PF8lRzyww33dzLikJSAfkhD1t1Oe7Em0RcoZ8lVCmVyamZBOTF33DkGTd8cfmtIErNNNXA9l99GbbjJprXo4y/uWqsZJindsNsI3NCTz/0zGhH4bqKyFT8cyap89fFRugc4BY=
    username: AgA0yNQvsgdAaNb9FdgAqmPbMNOlkWYxKJyPKBsGtD4JirJze5kBJ1N3cQ+4mE/1cGJZLe4/y5KnML+FZWBRXyfUkhlCxZtat4DfZTLyepGcjWt365KU6+59Q/bnPdTUlTg0WhpYcczSEM/6jfQRuNrx9bK6NFfv6UX7WhFjDE3J9K1QqT7klw7yCwuBgQeXXWODYA+Hz444jRtrdiMklDelbOQ31NB1rscXGTKXwxiPjKkkrCXRORs8Ta/vsIlEBDD0KDPfW9yF1fPVwgxgm+IFkUFXAvhTUT7lz7/yBSr6NEnipaduUhoef0uB63YYGMz2qeOl8UeuYFStaGrkVllFhkLOs6squazTVHYOjs++n9fyLnDIyI0iVXdbqs+NJWjrFPiiNv4mEoV8wBLa3uSh+Zc9ssTZlOrmaumDOkzbDBF4wGDWUHh4nsRErCcQhyBtebMy+YGrpLq4oJdnGUmdb04y2PD4xsLCZ/Go1PngCKl+t3spexIQe5+G6pq/T2o00LF1p0Uy0zhkXcQtQkWbGsHxX4Ifj+5bKlhe+0hpsjX2fOzX2zhvNYRIasotP3i9QygzwZd2rYc2rg7FsG1g/GdyFzJBvhRUr5U5Ce/zfBYUB7O9KSTw3wCL6dvcNDZDoVoMBRbq5QJFdI+QOrySY0wSJYJz3l7Znz4oSAYaCsj77qZspCcAAAGOIoHfB0A6TXpP7yYb2A==
  template:
    metadata:
      creationTimestamp: null
      name: kc-postgres
      namespace: iam
