---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-provider
  namespace: iam
spec:
  encryptedData:
    client_secret: AgAmNUli5PRDkbYj5sKhA0lxEEKa7KRt/ImC9x+GFR9LJue/M6x+dfnTDdcXWKrRNLA+5xGWxWUjIdh/PoXMr4n+7EBRDwF4c6UU4Q2jWYbHffVo3u7XCNOekGnpyxjf0NHP51JUg6KeJY9NgOEEHJ6WyCDbhuLXNsYgizo2aUmeE7Huqcm/mS6fFv9n4kUSMsQoCcJ7uJwfqVmuTgPWYTDuVuNnHNM5Iaz4ilQ3vLYQ9oFU1IX2+qSr1yPCNvFGA1Pm3ssylsJ86kFGg3Um3JaatUHpmsgm6AFdzWL8/DfNSlULsnsHEab0Qm0mLNNTFmCghe+3OkOtahJOolUN8P+eMDJ27Rz+VoKIzsapG+QgQBmUY8aA79Kdm0ECR6BMm6YUbbRZpMaVhUMHOYNtI6lUxClqOyE9AvKZhPEqz1ThFwpJHIpd1t6u1/FNwQFfbjukOldIn/dXqZPDSBl9V4rCneJfa/k79wy7KYSRigJBz5M8XUU6lJShWHESvhuaFsYd+qMFbdlyGGZkNgc/jXK+RbJm2miFeFeS/OHA82JoMVt4bnEVwZZ6licLE633GdgfcKfKhlRYuhoE1EXEWqiCV/JNRJWvI9fjzwBmz4ufPsToujnkjjbFOEB3SWWHMkSgP8aaeVXQt4r3d/trZjXI+8Dozi2UJBQxLOoXvUQ3Q/rvE2uVToRwlqySwJDxW2TEX+r2Mvai5TLrX02iffIJvtQ1eh48DZpZ2JOq4Ez3Xw==
    credentials: AgCnPX2KLC4IUYx+k95CQh/cQYp7xU4KNErI/7km1EPT2RJmcODCSJRuP1VR7adn22OYp78Q1llpQIo9vudbWVeBZD2c4E78vDBvCHcHXLXBqwsboR8ssKtlehDOh8KHUUlutKwtKTE8MlkammcOF/uV5S9hShsUMAkobXEqH/+5HzMa18zlfQmzvZxlLiG8HDF9omXo92XTJK321SMPEJpqqs8HGKg1l31Md9VeUfo5N8+n+TIOOwxJVaJqb/JQnk/5Vai6xitTKYvbL4zcRXio8QletxjGv0ddlL5/GPtDZpivBlgaYIjeWgLu3VR/WR4WMwnjpOe2/jTPDxeqbZ2fscXjegTDEKMFaY03Fp8A5yfLhC+RKIFwwBO8/VoyMZg8V5jCaMuveXTLciA86cksYLULmlDrwKadr2RqfbFIqaCy3tKreku5NtqL+kegx8MvjiQLK7ipIPFkEhP0z0GwYMK89lh6ZXl3rMTSVyjv9xI/x6RBfx1OIHLOTW+i++d6f4iM4gFvBvuZTmNzna2+gN7zDo01zPTThT+VIzhjuybox3wjKEAdfnJu4scqRaLcoiOQhqGCEWJFRkGcech/Stm+vaDVdndzoNuLTnpj7ENzDnu9MsqAtckuE/CMXuQt36uMMYqWSIOYtPAymI5uVeHt0jeQX6u2GQgwUrHaNfJg0maZY1aKwUxQvmEqwAdBRRPcrkE6lxMufZJNiUVk1rzTPYioNp7EWyE6Y6PGIbF9DGRxh7tBVY15roVnGilpds54MNuBOXoXi2eQsij2aXSqxtja1+ilajIn68TEHeYCQBUaIFiy533z/sGXkgdZew4S3SPndz7mKH8ODv98CGf4uXHeq1Hx4tecxaPNONx9GwIRC/vDsZjQZ4bi9Hva3shmuKc5QvnKE+Q13nXSbyttWNf2gVMNljBeX9f+S02FykP7f271Cs2yBZOcQCIQ1g==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-provider
      namespace: iam
