---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-provider
  namespace: iam
spec:
  encryptedData:
    client_secret: AgCMTnpHE4/emiAlSHmp2mhsx5+Cpwy+sh05lz/gwmZyxV5L6x9soDfoVn9CW/I0jDk11+iAUttIA+6/chZPDiseY8+i4HIHmC8sTxZcrHMlY1qFlcbSLSf4ttSo1U4JjSgRiJKu6NJP92k0ztFRFKjrt+YuIP3D8lZHjqFsrjPWXGOkvKS9Vi1qgumxch8syEUezjZmJRL+5hvg73HH+gzlbLEZnPuuu20hN24o/XXFp5k6aFQiH3tCkEla6buXgKRWxvNUidwRpyhXQqf+Ef2Y2epl5Jmf+TgPVjKfSrLwSqdmabBJXBvaiNigIhQeYJk4j0adQgPqfGCGwejCv8EKu/YkFeW9/2P72jg+8ln35oMFW8R8I/r3pM4YU/+dHKs17qozcNrpKzjYtrdZdn/LLsLsuGEVUDrW9oiMvDjPytTBCIyelNQN3WumkP2Zj289YiBWKfTplmDKVTWQGP7NnQLAH0eVERFaeXTm7ma5hloEJa/0ykiUo1IU4c2PfuwQXGOj8emQIJ6tQ7Tj8aaduLGgRfNxDJOX8eQr1Mzg1T32UN1lIOd6H9ZJLGDwOmbCXoNl2VqrDOCCzYq67nVWcmheC6w1ZdhM6Bq8MI0e4QEXWZj0zJj65zUDk8osSJJREuFei5sPSH7wBCo4X8zN0lmIoNxscfmHO0V1IB9zqM9UdXi1+Fw8VXz1LtSB5sOl0Mjk/ZPBPlsAFpFC9Yb/VycbEhCBSVfPZkbNJz71fQ==
    credentials: AgCl/9b/LqVSTzfjzgHSg5xvq7C0LsD5mTh7bY3Rv/TEjg2AhiPCGyxXJcKsW4emkuuV8jVOFDtJXEx1sTN2ROT31U4vADRvp8RK3PgV+UG2onhUHKcUpBjdhN7FhAdSf+xaMKG3kvs40FMMtTrvdWNOe4HRYFObNY+fpZeLk7658jIRZpZoCdcZKw1RSFIFL/imUmRJ0qQc7KCq4MQdIbpHBshZM7fPaiNN6X37dyscYIg3Tv7yO3ns1ZuuI2l/tj6xhXcl5fiRFetogSTtcXQEQM0T7IIwTXKiBjGwpz5F9XC990nAOp68EBChYMKhUKrE2qSy6BPjq18BWBsYu4JNQTCYFTysGiIz+//ZOrPgGeKJM2EV2oqsKNtsUxiW6pNFKH/HK5xyMa+NnikEzcAJ0Zc5ATGbXmM1X+6FVW7iHt4fZVtALoC/I2DoQ0FCfNKeK8Lxb8/CrcFPqn2o3DZj8BfUU5dPaAMuuAU5fb0LZMQk02j3sA9AxxHhijCgwbOErtHUTJliwKk2puY4CltvPrmImZkW6mN4+H0lODHnZ6x3YsO/IfE2fqlaGcQyRl19sza3huR5bU6oXTW57tZbqmZRsYAzO/7Xh6aJpKi9ashF1CPkB3j0veywKD9CkL1Afuk7Ih2KpM05Z2AtRfhmifvkTGnwGCIe6aBmtdykj8bz+8vf5mTVxQatN0UmOiTB6n/d97eITev8VUbNJPe/V+7TpjaTsNScoEJ9hEN1rmUAXG3MUOrWDZIjVyYJcHpeYrf/zIjFN+Ql5skYeTDZok+DDO9mG6FsIbwltcGCGMVxokqOknp8lInwuxtvu+xgxVC0uhsW+VmPpZPbOaz4uXFNDdUwpfTV5kpanpNzQAicN8IFtr5KCqFJWsOwb2opPd8HDNvpOhJLN+3puwjXKjemitM1oajkDCDyxPYB+KFTf9ubSLYHFzhjHCk6QUhwoA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-provider
      namespace: iam
