# Currently unused, because the secret is propagated via an external secret.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-provider
  namespace: iam-management
spec:
  encryptedData:
    client_secret: AgBZnMn3XGVLGzTpA5EjzDu/5Knn1IopJE+VPuiGDXjW1WZKD6TpwDP5PXhYCpvf0YNx2HigCHBtY+En/1tiJHm23x/Oy6JLBa9eHKSj0eHwxhAKUCo41dTj6DVWpM9GplWnviIAfJYsiITA2CBweiXfkFWWurWcSE2YY7DQ1f4dWuRTrUlNDXr8S7xBcyjxVEMn6+ResrGhu/N6E9DMh7RLrOXcrvgsTLhMuwCKoKpgKR06Aq2AQHule0hMD1erJxyLNy4uvrDdDCeY8k3Cotz9wFJwd6vakc/s6HygOOoZVSiabi8YFycVDhejD/YU1Mo50zzNTOXwzCbwZiZtSeEFPlA3+5K+tHkMdd4Gir1jYC9Z8nOcefH43pkzV1iuG/KqEM7VdHHO/4aHxuv/x6jr2/aO5MXd+7PfixLk35ug4bgCWoda+Gc/lgvone8c678tUkvpCbXsrzBTqI0zfd9cwwITksKnUXOkwuUmL9zmIPZntkq7yv4qJxjkceJiS9lkNxUP3MIkWh352xZ1mEkYPzyiYE4rtooa+8+bA07SJrOJf9tekfJdfWZXI/4rrH4FNOi3LKS3y1v+cKD8RVqETYf7rjD8+bcUBH/mBgJ0zOLR2AsqcAEbd6fmMlII7nrZXg4rmc2EuCzlaInPqMlbxMQlwhEgWZ9E86gAeF7mQuNvbKcCUOz827nDxC5qnQw=
    credentials: AgBCtHy4+qwQZZiQtYlQaa4WkDHp5LXP8jCypnsUykrn7pRXfktp4Zpe3pV+ymg7NxLoZe94VuxyV9RpmSmWgEjffTUUo8MWyj7r3JzbcxCjb341swQ7UoIZRoFIPw31tdjjojbogN7QA6b5nKo9SgRvKuPENOnVS0EaqIjjfMP/Na9KOMQOD6O0Ea188TRFw4nC2g0AcG64ieexLOwDdgHsb04tlrRWYJ29I4h6MNoLO+4EcqW/uhntxA8UM5zoDrpQkTjm0dSFmTQulcCBIXHCcw4CM+tPhxv1zDCUV8R0LNqFxUbTxNC4PdnC+2qmaUZUgYLRWtMCU0lyf+o4CgcW0Rw3LovzaJ+3jaqtyk3q55ZZINP5KuKlyz132N51ng/6JjP9vRi9HbNIySc0cKFb6HmFgYLXnAiEDgJDx/bY6MCUl1LqAiIcISjeSOx+IYQQELNbPYXGEHoy4MBxNDJKaJNJzurETbfENqgI0U8BDXrdrQVtyrxv+qOzsQGDKgs1XWIj61q4CW+q9dDHx89+4ADSIqZ7dI3ECwDkmgz4WWVWKEt5+2DHwzgTwsf4y54/QgYbPzd7u/S7xZ+L/8TsWiuhu4PoXtDva6Xbxe6lmMfDTh8tGVzqFenqlWZv6unzHlexj3sI+Skt4MeAjhlrBZmLIP020JeWNOWoPQ3plc3R6otk2+HJ61/ie+5HwKE3eqZhpQRzERUxElCl06GFxihgl7cq8cIS9VBw54SSdszSRxhs+jLVuBsSp8v00lcdTWfsPzlpRr5KTzns59e92QVZCncntASeudRyUMN4GGwJT5tKd10Wl1NuUls6p5o0IhZ3bYOYNSD83/QiJkpGSR29+7P+fZyfyMvKM5WFcRgUsa1sLP0ZTOMjuYPxnQx2ukOqkDjdWkdYzmqpXR94Ug31AlLq4+4sk20ESZ4E35sq+rv33x/VQa6jLBSVvQhgEP0=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-provider
      namespace: iam-management
