---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kc-postgres
  namespace: iam
spec:
  encryptedData:
    password: AgC6TX2Ave+ztMMPyyNKv72haogUv/lEvsEcMCXYXVk6CwkAU3ZjBkzok5Uldzx0kVLmBF3kUkXxGdzl5QgDzbBHf9Iotlpdqsxyp1Tk5GElWUrwHgVf6opA6CAsn2VxuLO83APFd/AjvECaUFMRkhs2JJRiIupVoqpP4fymb016LyooxAENmQr/mvO1X/pP9aw9VTlCoETsxHDLYS9pJqauRDlFV6Rs4J0OdC2BvboqXy4nb2w0tmRBRvOjOExM9jVqsnuCalwY7GO7dOdQBayJy5XXEhSyCUCilYi3gPNM336p4bjE8Y1qHQ95ocxz8sG4K18EUwn+OV/chRrwsaedYwfxhTx8Kmtl9FLjlJ9LXYnyJWcuuOmW8rbRq8y40hiiPWpCvT6w0Bkay1DXK/WKmrcNWPw7Ei29dZzEb8t5gMbBPpJA0fMkrhLypDSzAxlnBWk64p1TO+hFEG6+qGfxVaY8QbSdGQFg0sHSScfCaV2i8srxaLpWn3hMJwom3oJMcED8KPUHj3zH/ZUpisRVPacYCRvZAbm8vhGx4Y98i0jJAW4934HjYaNQiMjQ379oL8Yt0e+m0rziqH7YI4hW0+xDK/4WCVAhAUf1FY2Y3/A9/9swwz3hmgZW6/OqsS6Z+PfB47JnGe0dechFCcBr0bx/i3/2W4B/uPszeiufMOkqN9Ph0neePDM6st+zI/BF5SvSA/mzXxfpkIXqyhLOwriY1AyNuZ4tQJlJ6X+bvw==
    username: AgCvhZPISDDg+uwBqpiZWmPJ166OnKGxkhRBKtFiPav2y0vy46TOZlHtuREMeYF6iB9EDOVawIAWFzm6MxEUHjrwwBy6bFqoWVZ8G3jSw+Jx/A4xTgg+O1hN6hI9rDRQjuZzQymQsbT65tBp3YoGX0clWNYT6v4NOfTYG+e+9w3R1FCmk35bHpFEje0yZzjVL0lBGo/sLuIIUH+Rt5cv7r/7PNrkparBs0qzS0HJT+SzHADekXSnimMbzTLm0KgWbiIUPW7RMS9IsZZCJiQ2yeBSzYihEXA170crg3S5ofgbwNIu0KJytnxH+KrObRSyFuwIZTDkSzvvjgu9clx3afBi3/TV7/HlBr5RTCsQCwhiiAQk/faqnYQzltHAmI/Lu/T8f4q2ZFqJa72eopt/Xp8FO5UshgZDopxFZ/nKvrKDZ/0O+xX+LQouy7vyip23j8OtTE2lphrzxHikvUwgsluF3lEO4TxPAHwmOw+yh4pgNsQvvC/dzujyk3nQcGknpoSCRTa1iNA6Etkgg6Fc7kpbqkjbClM9Pzn8qQMLo3yigIlp75NKiV20Am+iY3SC/846daOIJllCi/6xwy1AQE1S4FELbpj1oC4e0vdhjXVbi4NeDFwPZEJ89BJxdVjJlSRzglaD6QNV9+YJUsCZc2tV/OGl194AEhXONRV/fn4/qNjnGhlk9P70XJ5zhmWEwPrhXWIp6G/jEA==
  template:
    metadata:
      creationTimestamp: null
      name: kc-postgres
      namespace: iam
