---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-provider
  namespace: iam-management
spec:
  encryptedData:
    credentials: AgCS0qaw1RWHKG3NiUpW/V3F5IIIXwq5hDg6pS4U4bWqzYyCtqueTbfU3XeGkFt0n7l6owIQozthsH9N1mW923GOq01IboaHzVuMg/M1bKKpQv1tXmXnppl0TpCIxkfVMO5m8sSxfV1rRn/tKbhjUFqz1umUbHeLMtHtGB+9CkGBB+Yg7kaMtr4rRjsMul8B0gSPskrgsWk4GCXZddpyPACXo+LqbMmGx74HL9wxDWmb6P87xEjRlFMzEMmFaLxgyWuMpMcvG15a/WGwZLE0ifPCkXPv8HE6HpQNjtMUcIlOnNySwJI7iYI3/gPBOVZwrDt4/jQUW7KDjKLUC4gJk7iAYCuvK+jBAhsjL4rNt0dqIgd8htjbXN5bq/UJ7lI3MxIwBbiAJLirQnYPhXe3JCq6pi677VEg8Dvt5sPcyh6Ne5oeTxHp7p2O4R7ibu6pc1Ah46pTiGn8mQ5dPzv4gnKbEz/lAdrnoVMzH3IBT602Khx0rpnb8UlnrvYvZpXOyVneDHfesShokp7QFJKgp5x5xTpNo9nRMrVFZND+gjS0+eU5EsWA0IhA4sptiZxd9lgCD3vWZY1430xso2VwaZ+h153QSNUHAwQvjx/W23qdQ1eDS4GJrm3Oe/H9jenCDTrhoQmxo0MTp5BMMyWT9KR3ysockCSJz44qw2lvj0j0PJfY42ejTMFvXXgJX/PLSSjTD29LnqImOb1eCKT9twvXFAgDcL44AKAgMFEKjxc+oFzbed318OZwGDF+ZVDUvyv7hYF8QWBu5M24N0JYvCOwzrfjFH8vd8MB7x2PtdQ4ioQhmQReF470DN/rBlCJl3xV06lVXNAb3rQXu6uwSpd9hziLJRDI1oaxlS8dCRfOdlaNafoHLE42gAly+GwGWeCBLz6efKl0iPFksbK8Wyu8puMJjFG28HolpA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-provider
      namespace: iam-management
