apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy-logs
  namespace: operations
  labels:
    app.kubernetes.io/name: alloy-logs
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy-logs
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
