apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-crossplane
  namespace: argocd
  labels:
    eoepca/app-name: workspace
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: v1.17.1
    helm:
      releaseName: workspace-crossplane
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
