apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-pipelines
  namespace: argocd
  labels:
    eoepca/app-name: workspace
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/workspace
    targetRevision: 0.0.2
    path: setup/eoepca-demo
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
