apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-api
  namespace: argocd
  labels:
    eoepca/app-name: workspace-api
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://eoepca.github.io/helm-charts-dev
    chart: rm-workspace-api
    targetRevision: 2.0.0
    helm:
      releaseName: workspace-api
      valuesObject:
        existingSecret: harbor
        fullnameOverride: workspace-api
        image:
          tag: 2.0.0-beta3
          pullPolicy: Always
        ingress:
          enabled: false
        prefixForName: "ws"
        workspaceSecretName: "bucket"
        s3Endpoint: "https://minio.develop.eoepca.org"
        s3Region: "eu-central-1"
        harborUrl: "https://harbor.develop.eoepca.org"
        harborUsername: "admin"
        harborPasswordSecretName: "harbor"
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
