apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-admin
  namespace: argocd
  labels:
    eoepca/app-name: workspace-admin
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://kubernetes.github.io/dashboard/
    chart: kubernetes-dashboard
    targetRevision: 7.6.1

    helm:
      releaseName: workspace-admin
      valuesObject:
        fullnameOverride: workspace-admin
        app:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/enable-cors: "true"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            hosts:
              - workspace-admin.develop.eoepca.org
            tls:
              secretName: workspace-admin-tls
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
