apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-ui
  namespace: argocd
  labels:
    eoepca/app-name: workspace-ui
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://eoepca.github.io/helm-charts-dev
    chart: workspace-ui
    targetRevision: 0.0.1

    helm:
      releaseName: workspace-ui
      valuesObject:
        fullnameOverride: workspace-ui
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          hosts:
            - host: workspace-ui.develop.eoepca.org
              paths: ["/"]
          tls:
            - hosts:
                - workspace-ui.develop.eoepca.org
              secretName: workspace-ui-tls
        brandingName: "Workspace UI (Global)"
        password: "changeme"
        s3CredentialsSecretName: ""
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
