apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: workspace-api
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: workspace-api
    accessType: PUBLIC
    clientId: workspace-api
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true # allow for now to simplify testing
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    oauth2DeviceAuthorizationGrantEnabled: true    
    rootUrl: https://workspace-api.rke2.deploybox.co.uk
    webOrigins: 
      - '*'
    validRedirectUris:
      - '*'
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: workspace-api-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: admin
    clientIdRef:
      name: workspace-api
      policy:
        resolution: Required
---
apiVersion: client.keycloak.m.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: workspace-api-audience-mapper
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    clientIdRef:
      name: workspace-api
      policy:
        resolution: Required
    realmId: eoepca
    protocol: openid-connect
    protocolMapper: oidc-audience-mapper
    name: workspace-api-audience
    config:
      included.client.audience: workspace-api
      access.token.claim: "true"
      id.token.claim: "false"
