
resources:
  - app-workspace-api.yaml
  - app-workspace-dependencies.yaml
  - app-workspace-pipeline.yaml
  - kyverno-rbac-workspace-apisix.yaml
  - kyverno-annotate-educates-ingresses.yaml
  - route.yaml
  - iam.yaml
  - secret.yaml
  - certificate.yaml
  - job.yaml
