
resources:
  - app-workspace-admin.yaml
  - app-workspace-api.yaml
  - app-workspace-dependencies.yaml
  - app-workspace-pipeline.yaml
  - route.yaml
  - iam.yaml
  - secret.yaml
  - certificate.yaml