apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: annotate-educates-ingresses
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  admission: true
  background: false
  rules:
    - name: generate-apisix-oidc-plugin-config-for-workspace-ingresses
      match:
        any:
          - resources:
              kinds:
                - Ingress
              selector:
                matchLabels:
                  training.educates.dev/application: workshop
                  training.educates.dev/component: session
      preconditions:
        all:
          - key: "{{ request.object.spec.ingressClassName || '' }}"
            operator: Equals
            value: apisix
          - key: "{{ (request.object.spec.rules || [])[?host != null && ends_with(host, '.lab.develop.eoepca.org')] | length(@) }}"
            operator: GreaterThan
            value: 0
          - key: "{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" || '' }}"
            operator: NotEquals
            value: ""
      generate:
        apiVersion: apisix.apache.org/v2
        kind: ApisixPluginConfig
        name: "workspace-oidc-{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" }}"
        namespace: "{{ request.namespace }}"
        synchronize: false
        data:
          metadata:
            labels:
              training.educates.dev/application: workshop
              training.educates.dev/component: session
              training.educates.dev/environment.name: "{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" }}"
          spec:
            plugins:
              - name: openid-connect
                enable: true
                config:
                  discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
                  use_jwks: true
                  bearer_only: false
                  scope: openid roles
                  set_access_token_header: true
                  access_token_in_authorization_header: true
                  set_id_token_header: false
                  set_userinfo_header: false
                  set_refresh_token_header: false
                  client_id: "{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" }}"
                  session:
                    secret: "{{ random('[A-Za-z0-9]{32}') }}"
                secretRef: "{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" }}-oauth2-client"
    - name: add-apisix-oidc-plugin-config-for-workspace-ingresses
      match:
        any:
          - resources:
              kinds:
                - Ingress
              selector:
                matchLabels:
                  training.educates.dev/application: workshop
                  training.educates.dev/component: session
      preconditions:
        all:
          - key: "{{ request.object.spec.ingressClassName || '' }}"
            operator: Equals
            value: apisix
          - key: "{{ (request.object.spec.rules || [])[?host != null && ends_with(host, '.lab.develop.eoepca.org')] | length(@) }}"
            operator: GreaterThan
            value: 0
          - key: "{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" || '' }}"
            operator: NotEquals
            value: ""
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(k8s.apisix.apache.org/plugin-config-name): "workspace-oidc-{{ request.object.metadata.labels.\"training.educates.dev/environment.name\" }}"
              +(k8s.apisix.apache.org/enable-websocket): "true"
    - name: set-apisix-class-for-workspace-registry-ingresses
      match:
        any:
          - resources:
              kinds:
                - Ingress
              selector:
                matchLabels:
                  training.educates.dev/application: registry
                  training.educates.dev/component: session
      preconditions:
        all:
          - key: "{{ request.object.spec.ingressClassName || '' }}"
            operator: NotEquals
            value: apisix
          - key: "{{ (request.object.spec.rules || [])[?host != null && ends_with(host, '.lab.develop.eoepca.org')] | length(@) }}"
            operator: GreaterThan
            value: 0
      mutate:
        patchStrategicMerge:
          spec:
            ingressClassName: apisix
