---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: workspace-api
  namespace: workspace
spec:
  ingressClassName: apisix
  http:
    - name: workspace-api-root-redirect
      match:
        hosts:
          - workspace-api.develop.eoepca.org
        paths:
          - /
      plugins:
        - name: redirect
          enable: true
          config:
            uri: /workspaces
            ret_code: 302
      backends:
        - serviceName: workspace-api
          servicePort: 8181
    - name: workspace-api-no-auth
      match:
        hosts:
          - workspace-api.rke2.deploybox.co.uk
        paths:
          - "/metrics*"
          - "/probe*"
          - "/ui*"
      backends:
        - serviceName: workspace-api
          servicePort: 8181
      plugins: []
    - name: workspace-api-debug
      match:
        hosts:
          - workspace-api.rke2.deploybox.co.uk
        paths:
          - /debug*
      backends:
        - serviceName: workspace-api
          servicePort: 8181
      plugins:
        - name: openid-connect
          enable: true
          config:
            discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/openid-configuration"
            use_jwks: true
            bearer_only: false
            set_access_token_header: true
            access_token_in_authorization_header: true
            set_id_token_header: true
            set_userinfo_header: true
            client_id: workspace-api
            client_secret: ""
            session:
              secret: "17Y56d3w4tnicLSCljwwbP0P"
    - name: workspace-api-docs
      match:
        hosts:
          - workspace-api.rke2.deploybox.co.uk
        paths:
          - /docs*
          - /openapi.json*
      backends:
        - serviceName: workspace-api
          servicePort: 8181
    - name: workspace-api-auth
      match:
        hosts:
          - workspace-api.rke2.deploybox.co.uk
        paths:
          - /*
      backends:
        - serviceName: workspace-api
          servicePort: 8181
      plugins:
        - name: openid-connect
          enable: true
          config:
            discovery: "https://iam-auth.rke2.deploybox.co.uk/realms/eoepca/.well-known/openid-configuration"
            use_jwks: true
            bearer_only: false
            set_access_token_header: true
            access_token_in_authorization_header: true
            scope: openid roles
            set_id_token_header: false
            set_userinfo_header: false
            client_id: workspace-api
            client_secret: ""
            session:
              secret: "17Y56d3w4tnicLSCljwwbP0P"