apiVersion: v1
kind: Secret
metadata:
  name: ghcr-helm-oci-workspace
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: ghcr-helm-oci-workspace
  type: helm
  url: oci://ghcr.io/eoepca/workspace
  enableOCI: "true"
  