apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-service
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: deploy-james
    path: argocd/base/eoepca/identity-service

    helm:
      releaseName: identity-service
      valueFiles:
        - values-identity-service.yaml
      parameters:
        - name: identity-service.identity-keycloak.ingress.hosts[0].host
          value: keycloak.develop.eoepca.org
        - name: identity-service.identity-keycloak.ingress.tls[0].hosts[0]
          value: keycloak.develop.eoepca.org
        - name: identity-service.identity-api.deployment.extraEnv[0].value
          value: https://keycloak.develop.eoepca.org
        - name: identity-service.identity-api-gatekeeper.config.discovery-url
          value: https://keycloak.develop.eoepca.org/realms/master
        - name: identity-service.identity-api-gatekeeper.targetService.host
          value: identity-api.develop.eoepca.org

  destination:
    name: in-cluster
    namespace: um
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
