#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  rm -rf tmp
  cd "${ORIG_DIR}"
}
trap onExit EXIT

# Get helper scripts
mkdir -p tmp/bin
mkdir -p tmp/cluster
curl -JLs -o tmp/bin/create-user https://raw.githubusercontent.com/EOEPCA/deployment-guide/main/deploy/bin/create-user
curl -JLs -o tmp/cluster/functions https://raw.githubusercontent.com/EOEPCA/deployment-guide/main/deploy/cluster/functions
chmod +x tmp/bin/create-user

createUser() {
  user="$1"
  password="changeme"
  tmp/bin/create-user \
    -a https://keycloak.develop.eoepca.org \
    -r "master" \
    -u "admin" \
    -p "changeme" \
    -c "admin-cli" \
    -U "${user}" \
    -P "${password}"
}

users=("eric" "bob" "alice")
for user in "${users[@]}"; do
  createUser "${user}"
done
