apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: deploy-develop
    path: argocd/infra/minio

    helm:
      releaseName: minio
      valueFiles:
        - admin-credentials.yaml
      valuesObject:
        minio:
          existingSecret: minio-auth
          replicas: 2
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
            path: /
            hosts:
              - minio.develop.eoepca.org
            tls:
              - secretName: minio-tls
                hosts:
                  - minio.develop.eoepca.org
          consoleIngress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
            path: /
            hosts:
              - console.minio.develop.eoepca.org
            tls:
            - secretName: minio-console-tls
              hosts:
                - console.minio.develop.eoepca.org
          resources:
            requests:
              memory: 1Gi
          persistence:
            storageClass: managed-nfs-storage-retain
            size: 50Gi
          buckets:
            - name: eoepca
            - name: cache-bucket
        minio-bucket-api:
          fullnameOverride: minio-bucket-api
          minIOServerEndpoint: https://minio.develop.eoepca.org
          accessCredentials:
            secretName: minio-auth

  destination:
    name: in-cluster
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # seems to cause a problem with unsealing of SealedSecrets
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
