---
image:
  #pullPolicy: Always
  registry: docker.io
  repository: eoepca/processing-editor
  tag: sha-b2c2441
replicaCount: 1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: apisix
    cert-manager.io/cluster-issuer: letsencrypt-http01-apisix
    apisix.ingress.kubernetes.io/use-regex: "true"
    k8s.apisix.apache.org/upstream-read-timeout: "600s"
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    k8s.apisix.apache.org/enable-websocket: "true"
    argocd.argoproj.io/ignore-healthcheck: "true"
  hosts:
    - host: editor.develop.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: openeo-web-editor-cert
      hosts:
        - editor.develop.eoepca.org
