apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  labels:
    eoepca/app-name: gitlab
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: eoepca
  source:
    repoURL: https://charts.gitlab.io
    chart: gitlab
    targetRevision: 8.1.0
    helm:
      valuesObject:
        global:
          edition: ce
          hosts:
            domain: develop.eoepca.org
          ingress:
            configureCertmanager: false
            class: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod

          minio:
            enabled: false
          
          appConfig:
            omniauth:
              enabled: false

            lfs:
              enabled: false
            artifacts:
              enabled: false
            uploads:
              enabled: false
            packages:
              enabled: false
            backups:
              bucket: gitlab-backup-storage
              tmpBucket: gitlab-tmp-storage

          registry:
            enabled: false

        

        upgradeCheck:
          enabled: false

        gitlab:
          gitaly:
            persistence:
              storageClass: managed-nfs-storage-retain
          webservice:
            ingress:
              tls:
                secretName: gitlab.develop.eoepca.org-tls

          kas:
            ingress:
              tls:
                secretName: kas.develop.eoepca.org-tls

          toolbox:
            backups:
              objectStorage:
                config:
                  secret: gitlab-storage-config
                  key: config
          sidekiq:
            enabled: true

        registry:
          enabled: false
          ingress:
            tls: 
              secretName: registry.develop.eoepca.org-tls

        minio:
          ingress:
            tls:
              secretName: minio.develop.eoepca.org-tls
        certmanager-issuer:
          email: me@example.com

        certmanager:
          install: false

        nginx-ingress:
          enabled: false

        nginx-ingress-geo:
          enabled: false

        prometheus:
          install: false  

        gitlab-runner:
          install: false

        redis:
          global:
            storageClass: managed-nfs-storage-retain
          metrics: 
            enabled: false

        postgresql:
          global:
            storageClass: managed-nfs-storage-retain
          metrics: 
            enabled: false

  syncPolicy:
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
