apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-sharinghub
  namespace: argocd
spec:
  destination:
    namespace: sharinghub
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/csgroup-oss/mlflow-sharinghub.git
    path: deploy/helm/mlflow-sharinghub
    targetRevision: "0.2.0"
    helm:
      valuesObject:
        image:
          repository: eoepca/mlflow-sharinghub
          pullPolicy: Always

        mlflowSharinghub:
          sharinghubUrl: https://sharinghub.develop.eoepca.org
          sharinghubStacCollection: ai-model
          sharinghubAuthDefaultToken: false
          artifactsDestination: s3://mlopsbb-mlflow-sharinghub

        s3:
          enabled: true
          endpointUrl: https://minio.develop.eoepca.org

        persistence:
          enabled: false

        podSecurityContext:
          fsGroup: 999

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: 10g
            nginx.ingress.kubernetes.io/configuration-snippet: |
              proxy_set_header X-Script-Name /mlflow;
              rewrite ^/mlflow/(.*)$ /$1 break;
          hosts:
            - host: sharinghub.develop.eoepca.org
              paths:
                - path: /mlflow/
                  pathType: ImplementationSpecific
          tls:
            - secretName: sharinghub.develop.eoepca.org-tls
              hosts:
                - sharinghub.develop.eoepca.org
        postgresql:
          enabled: true
          auth:
            existingSecret: mlflow-sharinghub-postgres
          global:
            storageClass: managed-nfs-storage

  syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
      - CreateNamespace=true
