apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: mlflow-sharinghub
  namespace: sharinghub
spec:
  timeout:
    read: "600s"
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: mlflow-sharinghub
  namespace: sharinghub
spec:
  ingressClassName: apisix
  http:
  - name: mlflow-sharinghub
    match:
      hosts:
      - rke2.deploybox.co.uk
      paths:
      - /mlflow
      - /mlflow/*
    backends:
    - serviceName: mlflow-sharinghub
      servicePort: 5000
    plugins:
    - name: cors
      enable: true
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri:
          - ^/mlflow($|/)(.*)
          - /$2
        scheme: https
        headers:
          set:
            X-Script-Name: /mlflow
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-sharinghub-tls
  namespace: sharinghub
spec:
  dnsNames:
    - rke2.deploybox.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01-apisix
  secretName: sharinghub-rke2.deploybox.co.uk-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: mlflow-sharinghub-tls
  namespace: sharinghub
spec:
  ingressClassName: apisix
  hosts:
    - rke2.deploybox.co.uk
  secret:
    name: sharinghub-rke2.deploybox.co.uk-tls
    namespace: sharinghub
