
resources:
  - app-sharinghub.yaml
  - app-gitlab.yaml
  - iam.yaml
  - ss-sharinghub-oidc.yaml
  - ss-sharinghub-s3.yaml
  - ss-sharinghub.yaml
  - ss-gitlab-storage.yaml
  - ss-gitlab-lfs-s3.yaml
  - ss-gitlab-gitlab-openid.yaml
  - ns-gitlab.yaml
  - ss-mlflow-postgres.yaml
  - ss-mlflow-sharinghub.yaml
  - ss-mlflow-s3.yaml
  - app-mlflow-sharinghub.yaml
  - ingress-mlflow-sharinghub.yaml
  - ingress-app-sharinghub.yaml

patches:
  - target: {kind: Namespace}
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {argocd.argoproj.io/sync-wave: "-20"}
  - target: {group: bitnami.com, kind: SealedSecret}
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {argocd.argoproj.io/sync-wave: "-10"}
  - target: {group: argoproj.io, kind: Application}
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {argocd.argoproj.io/sync-wave: "0"}
  - target:
      group: ^(apisix.apache.org|cert-manager.io|networking.k8s.io)$
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "10"
