apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openid-connect
  namespace: gitlab
spec:
  encryptedData:
    provider: AgCC7JgEItd3oiAYyrEEnbe11CCgPGjaP3k10uVvOsWFX91POWI08Ol/xSLEo0qbVTyQUbI/i1RHWr5uMOdm/lHBYrUpV75TTviLbRqSpk0TYbBh+bV6wQp/iQn6HWawFTUajxisKhoIGwTUJ5IbsCJqSO/5Q1BtR8LZvrYpKMx/SiyLuA1mfgzOZQAO79DoM7E3kiAc8NxYPYsdrrBtV1o+hmNPO9GGGH+APiT2VJ8epj6nLQmCAmPoFTpWnkPSISO9UlCW0+hAY1uCbOuxCYoZp8e9XFRlvx4tFC7OvXpZ+VfrgB+17Zw0chgKpr+9irrGvSXfj1g4USDh7TNDzDmHo8+KCrg43DBOfQtS8Sm7K+Vi/6ot+HWiAqJOubY/TlX+LgmAMSHHU2jQ8H/4HVFT6N1czlykXFQYerjSECpMnkuIbqjdesVXKP5PmkwNtKn2pllbHrdLkcshwf3RAPMEe0AOL0NYHPkdDJ3oKdOr50mG0JHEU4DtPSDU314ZzGjbZjSmsrgyONLs4Hv+btEGYWYt/sRZ8oB5ZXikT5SJJMdoedglY2eapbmyF0IY1cOUScPT06fH/CHQEJrJRuLLHubqFYV3MVwas9gz6zF77TTvYDrxnyEeSmTMC9ezGdIKPnmOFVl6IlxQSrfpB4hMJzl3l5XHBiFQMyfxMwsns6CxEuL9Va0URfIg/CxgszGYGtJNsemHNItaC8Gyhsakc+t4VWWsBfSIEO1BqXW1gkgB+tlKchqAGzK6asReNsa0cT2a21mmAqk5mRuJH1eOG0DxDE1ZdKeD7iGUdngWNzcQ84/RHb9UjzdPzdqK6pykaoHHY2DLP/kjWObfrgTJJ3XO2QHJ9usT8eo5bX92w+HXJwWZOTX13Niq0FwvjcibFDOwiEoA2FPVZXuQcURPyCiSoKERot+W46ljR8nrgWXf4JQWGGSP4OWneZ3W6HsX2Gmgbg4njKmEQqc+Sm1rMFeC7tjHOOCY7w3qfO74YEbq+CzASH3ANtBM0ZmAjkWnJBzeEQdDP/N4KGNH8QyXk6JMnIigmBkewiZsBpKDDWzH7DfIGxmQPrgow/nG4cV48Dpw4Ba/4zhbi+vZpIjpYfFiAU/l1f9sWdX3obcRGohalY7xm7/HwwdevnOibrzd9mPbr6l9+drl9aA1wVfSZ6TXYsUqhL/RqlVdXXSZ9+sRdVgUGzxn6way+b+IRvAlWz/GjiIVhR2MYYDH6nbxyG5OJrdFh5n7p0OubvbLS33tr6LrsZKqhmzm7l7b90aGUHwXdpY9nBb/my4rJNkFmyINFnNCAwUfPNaUk12JgYDekLVXrmz2pn8=
  template:
    metadata:
      creationTimestamp: null
      name: openid-connect
      namespace: gitlab

