---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openid-connect
  namespace: gitlab
spec:
  encryptedData:
    provider: AgBkpCG+8Dz8WIzEIUeWLWuZ37HFFIP/oRa4e5Rg+fj0PGEdTnPDOm+kbQmzqsh7M0FlMBJ5FwmkuHipdlVJUE3evYfD8dZs9AovmgZse4Wkphe/N6hhikIEaYFcOaQwXLASYXB+nl5e9wjpMnH7dys891L+hJ1ld8EL7iafCgnuZ2vM6QDT4a52wxua9kWwYNM6KiyCU6C4vnXFprkAkS83pbbbPg5RyuuQb772bv69weg51dSW6NPhvYLIaouPnD3JEkh2g7qpuYTyMgttw3Bmt1VDyUceq0E2qXUn64nHMr7jMA5OX/f8LIiSIkU87Z+wkjbJFY1SOqkn6ycFGLpS8bfGP8kKqAmwxQmVpWjQCKVQSXYPOHcQlF6g/vrkymxHr+Lwxhx9HuTguJDr5Qn971p88wikwVzJbNE9TlZcNLbmN6oVIb2wIDwrvWDKxryaEWkHIevxNlY7QtavtdEINAi1OfRCuSLhxpzPDaWprOmJdF2e0rLSJ07YDXxwv5f9OA2gYH3I+CUeZn++Kd8DYh++xFPYD+MZqFrNC8ayQNTI8bqZNtK/966Zt/PAW7MbWE/cYsWrno2v8kIkcRA0PLWGkhoRiKCmX0UPWWE5reNSBhk9Vyugn0OCfBwr+RKQQ4UJKUhLoYsaADb0JQl89DB5OBoCWOsehJC46YQHYWcVfaWFz93klxG1PFIunzMO1t/2H1NLFgyK1eMFz5m0rShsM/r+UBxZhzBXjJpFnWxsxCGbvjqa/5+LmvZ8QzeLL5nIz0G6RajduBkWqsxnCkCriHxc/7WP5R5DQWGwuVU2ZbkNuZrwyZknx4wgrZimjWFm5sb6z/EAqdtYdG4TrUsnTpFKvwjaYGQCzgD1b49uAKNC8Xy4+kwdxr3EwveLb4niJC8DT5Tg4r8EAGj3VnFBwaneNCUemtxAkLLy5TnPCBrZLwmWxwD+FKrSx3aMjzxU31yDtzOTTIX9o4KWdAPvSldBeTICHnJYCdhbVuUwz1fhqTPjLcWeqt05KqnBmXYV2N//cPqNFsQDqVGny6sFCv5Q2Y5Rq0XwL1D5iWk7SkFyXXEyjtCgwa+c1Q6kgzpXuacb/7Ex/oXmSPu5AcJRP9PeUXEue+bQRlAjJeWkGePY1FZs0TlU5deYJI/KVgpA/l39wz7gvw7xKFosCyz3GoRw3SjBukvgkHmRIXdl+kYcY6NzSXdSLF2ZzOp1l+Ua6Dao8kEdu8ZqmsOZlOgMAK4a0YJpJRrPDEX13XkaherGibcG7T0KGttqkxrk1fNuM+uLEOTPeYvrfiC0pdDW5RBZTAiWeIe25KieKAx9IV0U7B8Gs3j/91CGkNgROmxx6/hYF9nOwkqgQyjvrSoqDtfqfAbclocrAHl8umURIhhDhENeDTJyCElwtXC+LNo=
  template:
    metadata:
      creationTimestamp: null
      name: openid-connect
      namespace: gitlab
