apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sharinghub-s3
  namespace: sharinghub
spec:
  encryptedData:
    access-key: AgAabOMwmMAy43K9ThnKZ6GZN57919wfehrwlBV/HG3oUvnwXkHS3/vrR7Cfl5aJNFhLHi6211qEK8wCRdqiO+7IJQpT7FFW6mAfZWo9nN7u3MOEev0v3afVuHUP4Lr+jCtycstbpwdkiIK7fNkQY4s9DV9tWAVDs6D/ld0DHskwXfsDoVy3aM6djDPYSkV5kIL1OQhVLmo0/dkgwtA6EeEwhkbXSaEb7XGyaqZmnXVbfecfkPxru2xYEXnwScpMW0yRfKJvYxTIeL70cgUgoKPyaSox0TgtZH9v0eJbBl9bFSsDr1L81ps65mqLBkwtgckM5dun8uk3AIxG72O59YFTrMSxGdSS5tzfShu2BFTh7eZbjLWGGKxnzaAPUj+88zV4fWG649cBLGBcVNuMY1Wxqvoe036NjuFPmgxKJ2wXZqH/aaA7ZCjJUrkrk4vPbPJmnLyb5EoGWgNMl/iGP1YDKyNpm6qZlfZJ3IYDpsFFJLY/hg4lshSHXYuYx6ewqW5yETYXESszT3Hbuf9r0xA9tacZ6B90GzB2S4TXRq9eCn5H8+mRDUtkkr7VAw6CZncJn+PGbOSMPR42J5hG70hIVVSb5ii9tZ+ZdQ5ZFqyctL2Lhxr5g3Np0IrCThc7A8i5e1CYAyxnjoY3g8Y2GW8jGsDOIrWnZHskbgkwnoF41Oo/cstdRWYuN5OSaYN/m3dy0uv4Sg6jMr8oh33LC4hM
    secret-key: AgCBlMVOLtvP/2UF6fR0VMQ5CMjgqODk6lzmaR6HonEUIgJgbtMzjbbY1crhLv7US8wwEWn14oB+sgkrou9j5Jxt81gYty82SoW9VDpbE/JyC+HDWjZ7a8Qu0NdZ5hLcMuzeLOTBJj+fVECvCeKngnn9TwoLE28+XwYFl2ubDhdYTJHuNAQMkqkJ4IlOeVolJgrO0DjtvB27BtW3wfABDXlOXnSFkk/+5TTbjdoM6+doVtE3ynFHeH2bUTsJKXHrZR6HdJdr2JLG3n+e6Og6cP6d/lghQ9sjiDLfE7xJyIwkH1BTqlPP4I0KDnsxV0sb2yLeM82qy6Ki6XOi6PdvKd2Dr4fIu9nC4vr4hdI4lqTOwXc0nkKOZ9YvbnrP3zI9Xk2THuYY9gDSBgNykBgAmMEZIdJiBgp2RJtJj6YwXImBs+23l/fG8HHZB9ZAF4VZZK7z8lEMyqmgcf7bcx/3nTvWLAZSH786FIqGXg6DIrtvVx6k8METXZihb53vRJnJTSaToItApTgE2Do7j4VQwDhmAQfvd9lZz7+h9RdasJJO7jPacM1mIP/WViPn2N0n1Lz2UiKE3GVUm8B7ENN9Hyy3kf5f6Sp3Bwa6lMxnTdoCb+0apQtPWslmyqp57E5dhALlRHgSs35nZw39g8GU/3aE4HVA4PZbnzcJPKZwmhSFZJ/q1Cq+zeM6b5Js0K55jWOnnJP9ZXIYivsgukEcvXjd358YuP0ILLik/0gNN3ZwpA==
  template:
    metadata:
      creationTimestamp: null
      name: sharinghub-s3
      namespace: sharinghub

