apiVersion: v1
kind: Service
metadata:
  name: alloy-logs
  namespace: operations
  labels:
    app.kubernetes.io/name: alloy-logs
spec:
  selector:
    app.kubernetes.io/name: alloy-logs
  ports:
    - name: http-metrics
      port: 12345
      protocol: TCP
      targetPort: http-metrics
