
resources:
  - infra
  - eoepca
  - operations
  - test

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    patch: |
      - op: add
        path: /spec/syncPolicy/syncOptions/-
        value: ServerSideApply=true
      - op: add
        path: /spec/syncPolicy/syncOptions/-
        value: RespectIgnoreDifferences=true