
resources:
  - app-apisix.yaml

patches:
  - target:
      group: monitoring.coreos.com
      kind: ServiceMonitor
    patch: |
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: apisix.apache.org
      kind: ApisixGlobalRule
    patch: |
      apiVersion: apisix.apache.org/v2
      kind: ApisixGlobalRule
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: apisix.apache.org
      kind: ApisixTls
    patch: |
      apiVersion: apisix.apache.org/v2
      kind: ApisixTls
      metadata:
        name: not-used
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true