#-------------------------------------------------------------------------------
# EnvoyProxy
# ----------
# We only need this as we want to expose http/80 / https/443 on NodePorts 31080/31443
# - rather than the default LoadBalancer on port 80/443.
# Each `Gateway` resource instantiates a set of resources (deployment, pods, service, etc.)
# that implement the `Gateway` - including a `Service` that exposes the listening ports
# of the `Gateway`.
# These resources are defined by a template that can be patched via an `EnvoyProxy` resource.
# Thus, we patch the `envoyService` ports defintion to include the required `nodePort` values.
# The `EnvoyProxy/eoepca-public` is then used as a parameter in the `Gateway` definition.
#-------------------------------------------------------------------------------

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eoepca-public
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: http-80
                  port: 80
                  protocol: TCP
                  targetPort: 10080
                  nodePort: 31080
                - name: https-443
                  port: 443
                  protocol: TCP
                  targetPort: 10443
                  nodePort: 31443
