
resources:
  - app-envoy-gateway.yaml
  - gateway-class-envoy.yaml
  - envoy-proxy-eoepca-public.yaml
  - gateway-eoepca-public.yaml
  - route-apisix.yaml
  - route-eoapi-db.yaml
  - route-nginx.yaml
