apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-harvester-api-core
  namespace: argocd
  labels:
    eoepca/app-name: registration-harvester-api
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://flowable.github.io/helm/
      chart: flowable
      targetRevision: 7.0.0
      helm:
        releaseName: registration-harvester-api-engine
        valueFiles:
          - $values/argocd/eoepca/registration-harvester-api/parts/values.yaml
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: registration-harvester-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
