host:
  external: registration-harvester-api.develop.eoepca.org

rest:
  admin:
    username: eoepca
    password: eoepca

ingress:
  useHost: "true"
  sslRedirect: "true"
  clusterIssuer: letsencrypt-prod

harvester:
  service:
    name: registration-harvester
    type: ClusterIP
    port: 8080
  image:
    repository: eoepca/registration-harvester
    pullPolicy: Always
    tag: 2.0.0-beta1
  container_port: 8080
  config:
    flowable:
      host: https://registration-harvester-api.develop.eoepca.org/flowable-rest
      rest_user: eoepca
      rest_password: eoepca
      use_tls: true

# https://github.com/bitnami/charts/tree/postgresql/12.10.0/bitnami/postgresql
global:
  storageClass: managed-nfs-storage-retain
