apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: notifications-wildcard-route
  namespace: knative-serving
spec:
  ingressClassName: apisix
  http:
  - name: knative-serving-default
    match:
      hosts:
        - "*.notifications.develop.eoepca.org"
        - "*.default.notifications.develop.eoepca.org"
        - "*.knative-serving.notifications.develop.eoepca.org"
      paths:
        - "/*"
    backends:
    - serviceName: kourier
      servicePort: 80
