apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: notifications-wildcard-route
  namespace: knative-serving
spec:
  ingressClassName: apisix
  http:
  - name: knative-serving-default
    match:
      hosts:
        - "*.notifications.rke2.deploybox.co.uk"
        - "*.default.notifications.rke2.deploybox.co.uk"
        - "*.knative-serving.notifications.rke2.deploybox.co.uk"
      paths:
        - "/*"
    backends:
    - serviceName: kourier
      servicePort: 80
