apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-automation-helm
  namespace: argocd
  labels:
    eoepca/app-name: notification-automation
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/helm-charts-dev.git
    targetRevision: develop
    path: charts/notification-automation
    helm:
      releaseName: notification-automation
      parameters:
        - name: serving.install
          value: "false"
        - name: eventing.install
          value: "false"
        - name: apiServerSource.enabled # enable the API Server Source to receive events from Kubernetes API
          value: "true"
        - name: eventing.authenticationOidc
          value: "false"
        - name: webhookSource.enabled
          value: "true"
        - name: webhookSource.secrets.create
          value: "true"
        - name: webhookSource.secrets.githubSecret
          value: "123abc123"
        - name: webhookSource.sinkBinding.create
          value: "true"
        - name: webhookSource.nameOverride
          value: "webhooks"
        - name: webhookSource.domainMapping.enabled
          value: "true"
        - name: cloudEventsPlayer.enabled
          value: "true"
        - name: cloudEventsPlayer.subscribeBroker.enabled
          value: "true"
        - name: emailer.install
          value: "true"
        - name: emailer.config.emailFrom
          value: "noreply@example.com"
        - name: emailer.config.emailTo
          value: "team@example.com"
        - name: emailer.config.yagmailHost
          value: "smtp.example.com"
        - name: emailer.config.yagmailPort
          value: "587"
        - name: emailer.config.yagmailUser
          value: "user@example.com"
        - name: emailer.config.yagmailPassword
          value: "password"
        - name: emailer.config.yagmailSmtpStarttls
          value: "true"
        
  destination:
    name: in-cluster
    namespace: notifications
  ignoreDifferences:
    - group: serving.knative.dev
      kind: Service
      jqPathExpressions:
        - '.spec.template.metadata.creationTimestamp'
        - '.spec.template.spec.containerConcurrency'
        - '.spec.template.spec.enableServiceLinks'
        - '.spec.template.spec.timeoutSeconds'
        - '.spec.template.spec.containers[].name'
        - '.spec.template.spec.containers[].readinessProbe.failureThreshold'
        - '.spec.template.spec.containers[].readinessProbe.successThreshold'
        - '.spec.template.spec.containers[].readinessProbe.timeoutSeconds'
        - '.spec.template.spec.containers[].env[] | select(.name == "K_SINK")'
        - '.spec.template.spec.containers[].env[] | select(.name == "K_CE_OVERRIDES")'
        - '.spec.traffic[].latestRevision'
        - '.spec.traffic[].percent'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
