resources:
  - namespace-knative-serving.yaml
  - namespace-knative-eventing.yaml
  - knative-operator.yaml
  - knative-serving.yaml
  - knative-eventing.yaml
  - apisix-route.yaml
  - namespace-notifications.yaml
  #- kafka-cluster.yaml
