apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-check-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-check
  template:
    metadata:
      labels:
        app: storage-check
    spec:
      containers:
        - name: storage-check-container
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: storage-check-volume
      volumes:
        - name: storage-check-volume
          persistentVolumeClaim:
            claimName: storage-check-pvc
