apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zoo-project-dru-keda-core
  namespace: argocd
  labels:
    eoepca/app-name: zoo-project-dru-keda
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://zoo-project.github.io/charts/
      chart: zoo-project-dru
      targetRevision: 0.9.7
      helm:
        releaseName: zoo-project-dru-keda
        valueFiles:
          - $values/argocd/eoepca/zoo-dru-keda/parts/values-zoo.yaml
          # - $values/argocd/eoepca/zoo-dru-keda/parts/values-stageout.yaml
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: zookeda
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
        - /spec/template/metadata
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /spec/rules
        - /metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRun=true
      - ServerSideApply=true
