
resources:
  - app-kyverno.yaml
  - app-zoo-dru-keda-core.yaml
  - ingress-zoo.yaml
  - ss-zoo-workflow-env.yaml

patches:
  - target:
      group: argoproj.io
      kind: Application
      name: ^kyverno$
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {argocd.argoproj.io/sync-wave: "-10"}
  - target:
      group: argoproj.io
      kind: Application
      name: ^zoo-project-dru-keda-core$
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {argocd.argoproj.io/sync-wave: "0"}
  - target: {group: ^(apisix.apache.org|cert-manager.io)$}
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "10"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
