apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth-zzz
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    rootPassword: {{ .Values.adminCredentials.encryptedData.rootPassword }}
    rootUser: {{ .Values.adminCredentials.encryptedData.rootUser }}
  template:
    metadata:
      name: minio-auth-zzz
      namespace: {{ .Release.Namespace }}
