apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-auth
  namespace: infra
spec:
  encryptedData:
    rootPassword: AgBuekPttTFffE8XuYsbu5fFfOs5ic5JqZiICex/4f6hRUDYRThogWCSh31siruBXk4eEYWjPONvmoqcb4efUBT4zRm6vnNUKGNzWgmOoxn6eGede36dfAsvtVUxytj0x5H5bFD62UggzyfBIG+OUcjsv4k1l1anCL0sTUV5tTi5Ok5iR5D9BZGy8hf4d0JpJmTRlKoSIHwYhHLU16Ie1zp34ELutFdyTy0cvcoBDHlcgtZzVsNwQ2JMK9aXr0+kJWlyAjL5hbiO+OggXWF9C3A3ddMBzjPROhoSdEtD+JckUu/zKJ7WuzlxNSMyq1rdYqfrMdNPa2U3ebizvp7TP6CltzI0eHv2rplSgGheg3LrlQvAq+t2xj+Tc8+TQ8TO/merZpAVb/toJcs6yrWgJJ+jJ6ArZssjx5PULxGO2cl0lV3rFTZJcpcZO5Fmbgy+WpsYSh1/HPwZUuV3W2PgX5S3VHb1+Iobjv4iZJrYLOL+Cm0cjTXzIEEC8ztByy3rnZw0bYX8rHusbupY10GzwiFH5Sj2AgxlDA8IWaaa1mRHrqqin8CZTIGRKjCPIwnfAW3RoYXd0Lhd4+Yvrf4KqHm4pft/p53M/peCdUOsyNKE+WifO2S3WwDJktcVO9yQPWzf9fimhKYU5MrN7NQy4MPCD3q9jk8p1aLKNSHMrs4Xih3zsMUou/eFiaOi6pdfjzqkwknYZ2qsYw==
    rootUser: AgBzT7JY5kYpBVACAVBF+uc+hEXRsbQ+TPk0vAYhZe/blM6NSJ1NWoc0Q2K/30bnVfHnJ+4fMWd2RE0iAE6mbLTR6M01bnpZ2I1oRsBPN7vSrO+hxfQe08MPFev0rnVKhGz7iGCj0DxCsCraK1s3kVefqw79T1yOBjKWVgqC7sig7La34gRYKMp6095wLqZV1jomw1EctyQMehZzgFMTC/dtf/2cFuSfZxAgu+4wlTgAZ/nhscvfzwBLkiY7fzAc4cRmyGUSeyG72t6S6AasuIdeXEcFNK62rBsgW2nVoYmEthHi9rN7cAsNZgRy75XE+6G+XG1SQ1U98fvl4w+K3yQtpOld+EgYu8W7z6FNEf8x0CoqoMpBlm8MPOtvMMwhTViG63D2XQKNXfev6Y2uk/2ckt1lM0JtihCdpWS/MhILhIe7+UCyDzxbztsPyLblblq46vVHxxJANqjftlgOjcTIQrDsgVBaGhvVOvXwP3W/kDslaAVU5H+oEgWX7D1mNnbq0WmFrpPbW8hGhmD7Dr36Cye4BbNUVreESbl7lSIhsu6NCO9F+goZ4x1vD0sza+6yOqf54FiUzNku6jDtJXgw/55FWXaC3wkDJmTAxMA4y9IhR7rbUn6wc7kVQyLuB8HWN0E+kFfsZ9VYQcAZI78cgJtbx0rI74VaH0WZvVPeT5jBhPzDGUSt/ZGmdpsFC3POv6/eSx4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-auth
      namespace: infra

