apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: resource-catalogue-protected-route
  namespace: rm
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  http:
  - name: resource-catalogue-protected-public
    match:
      hosts:
        - resource-catalogue-protected.develop.eoepca.org
      paths:
        - /static*
        - /conformance*
    backends:
      - serviceName: resource-catalogue-protected-service
        servicePort: 80
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          Cookie: ""
    - name: cors
      enable: true
  - name: resource-catalogue-protected
    match:
      hosts:
        - resource-catalogue-protected.develop.eoepca.org
      paths:
        - /*
    backends:
      - serviceName: resource-catalogue-protected-service
        servicePort: 80
    plugins:
    - name: openid-connect
      enable: true
      config:
        discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
        use_jwks: true
        bearer_only: false
        set_access_token_header: true
        access_token_in_authorization_header: true
        set_id_token_header: false
        set_userinfo_header: false
        client_id: resource-catalogue
        client_secret: ""
    - name: opa
      enable: true
      config:
        host: http://iam-opa.iam:8181
        policy: eoepca/resourceregistration/registrationapi
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          Cookie: ""
    - name: cors
      enable: true