apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: default-pguser-pycsw
  namespace: rm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra
  target:
    name: default-pguser-pycsw
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: default-pguser-pycsw
        property: user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: default-pguser-pycsw
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: host
      remoteRef:
        key: default-pguser-pycsw
        property: host
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: port
      remoteRef:
        key: default-pguser-pycsw
        property: port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: database
      remoteRef:
        key: default-pguser-pycsw
        property: dbname
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
