apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: resource-catalogue
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: resource-catalogue
    accessType: PUBLIC
    clientId: resource-catalogue
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true # allow for now to simplify testing
    fullScopeAllowed: false
    serviceAccountsEnabled: false
    oauth2DeviceAuthorizationGrantEnabled: true    
    rootUrl: https://resource-catalogue-protected.develop-v2.eoepca.org
    webOrigins: 
      - '*'
    validRedirectUris:
      - '*'
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: records-editor
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: records_editor
    clientIdRef:
      name: resource-catalogue
      policy:
        resolution: Required
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: resource-catalogue-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    name: resource-catalogue-admin
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: resource-catalogue-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: resource-catalogue-admin
      policy:
        resolution: Required
    roleIdsRefs:
      - name: records-editor
        policy:
          resolution: Required
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: resource-catalogue-admin-members
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: resource-catalogue-admin
      policy:
        resolution: Required
    members:
      - eoepcauser