
resources:
  - eso-pgo.yaml
  - app-resource-catalogue-core.yaml
  - app-resource-catalogue-protected.yaml
  - app-resource-catalogue-route.yaml
  - app-resource-catalogue-protected-route.yaml
  - iam.yaml

patches:
  - target: {group: external-secrets.io, kind: ExternalSecret}
    patch: |-
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: resource-catalogue-database
        annotations:
          argocd.argoproj.io/sync-wave: "-20"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target:
      group: .*keycloak.m.crossplane.io
    patch: |-
      apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
      kind: Client
      metadata:
        name: resource-catalogue-iam
        annotations:
          argocd.argoproj.io/sync-wave: "-10"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  - target: {group: argoproj.io, kind: Application}
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: resource-catalogue-services
        annotations: {argocd.argoproj.io/sync-wave: "0"}
  - target: {group: apisix.apache.org}
    patch: |-
      apiVersion: apisix.apache.org/v2
      kind: ApisixRoute
      metadata:
        name: resource-catalogue-routes
        annotations:
          argocd.argoproj.io/sync-wave: "10"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
