
resources:
  - ss-resource-catalogue-secret.yaml
  - app-resource-catalogue-core.yaml
  - app-resource-catalogue-protected.yaml
  - app-resource-catalogue-route.yaml
  - app-resource-catalogue-protected-route.yaml
  - iam.yaml
