---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resource-catalogue-secret
  namespace: rm
spec:
  encryptedData:
    password: AgANE6wSpEs5/Iv56yu4XRSLLLnnHTJr5ZBAjcQ1r1rdIgEdKAwhjL7aUH0NZbRjCzuiMXcY4Tsgr1C6yWEsZTnJom98lHgK2YJnAgRRsIw+JU0txWvChf3v3TMUc1ZyQRt9K621D6MK7MIjDfkp4TnGq+8wpaFAe6thbr5luAosiSYiPnF5Zg2gWkwXKCIUfDd7jWB/u8qFMISfRb5jrton/GnqfooN52jbVvTR4+YlaID7gAurN3JgKhFmgQnN555i1srAjOyddLdB4laX70ONPM2URLEqDojxQ95YU/aPsFmndLOlvxcAYi7Rp5Z+9IAPToP/KrnVKZ2I6QMUJLLSq5X1KZ6/wA8awA1ue3i93q25nYaG6O8IBBQHQmoDWyQBH5Jgg04kgeKPwEX24W6BZq3vfIv8e1YzruIbHZT+BhsvGgtEGXL+OL94ZHf41CoPk+XYPytbtRfbvjMPOndUpSKryPDNcopgydg+Upj594Jof08tq6wPD6UhNAHsV6zxqnv81+Cs1dvUt4w/zuIYJQ+STYMY+/K4c1Z6cagGl2BVHXlU4dI4Oc2lIwhwbce/aoFE6mRrFlt5jLuOtPp2/0XcoTLuoxpzaYvmP3E0qrPwBCdR6Ev7qePdotx0zC0+U/TXpjbYH35ehtPxSGSENWideyv1HfH3kn6ry/xviw03PO0RZliDNouEJ6/0ZnXwGn4iZBdi/oqH5QU23lQsO2TloG2h18g=
    username: AgAaGnqu4wk81ELJnh44NdenAldvHXXEA4TfA0cztYQRe7bLzd0SRvmLCFn4RHP0WJ9xSJypgsbIyMyJNIEiVQLinZit79rPK7V/ijIuIcP98q9l7KIsnXZesce3KFI9f3culgCVhHRYv0Glfxm0ZJGNSjwvbLSCef0OlZl5vriplyuae+w0/DGKHyE+upGpw3i7Jsv7iammAGFAskE+cTwfbQUrblS/yEfEDXmvy4BfWU2eE63bzcKPtXJ3nPvB8mdtsnluXDc915fSPezi0C7aDH8igLjJa2ZJGeoPktQUAJ8tNHg3ZlaqOw0l3IVHBTSxGPxQ6d1WrHCjoz0t3zXXB6eNjZJTSCk/DZrZQ02FpCt8rddUaVQgDCntTL6k5vOBHhjOnIH5MoOw88S8lR/5ymc/OA6oBeJexv4JiGJu7IJL/durbRvW327bL+pht/9h804nNc7ez/rDogSKMrKyn7+tDu2nGZpP1qbyLg1anPXikxQ62bccn3eO2HJZDCuDl9gsXvPFIlg1zu5f9zA8QGl00eREV80UxkFdHjlpaoap5ixRb7RZWB+5/Uti2j1GaO2jfIoUqWXHEig1XcgianG1PUIaa8IuhAoVtwYAs6QDyCuZNxqn87WG00aUgK9dsmrPTS0N8/PVBAFyIFQopAum9Fcqvfi8zNEosxnVDq7PkbyPlI9Ceo9j0sYMj3HYBERYTQ==
  template:
    metadata:
      name: resource-catalogue-secret
      namespace: rm
