---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: resource-catalogue-secret
  namespace: rm
spec:
  encryptedData:
    password: AgCiQoh2ZVLaZ+p0AnOVvYKX2A/WHuSrIetdtm3bV0nda93beG4OhS2gcXX6bYj9vs6RcCFuweM4N9aq6fhIy2JnuG24/LgDt9weGP9myVZTMA6rajKtvjhM8pt4WSnJr4ylc5r0OcdRtSwIWYlaMWOp++XKob/lUCKxf0E6NyMqrzEKoC2QY808c8j8V3vvLVy5SxMFYDMYqzr8N1J0g4XYTm2I7s/rRunSHp6xX4G/B2p20Ut8mhZzC4jIRPWWHGvDlJG8LHoU/CoB0FZ4cNIyf2MEoOg1b9OHWT4RqzHNAkNZA+eWvneNxtNcG/e1t003umXPTXck94ZU6igT2X8SplXYL3/c65nxpBBP1yI31OUHuzFUD0BzoCqO65G83E5er2Wn4o4Mq2EfXEehzsxZYvKvmjPIqWySmm7/UAf3hFTjaOL+FhWiPe9zpuDTq/d1BNSA6pL1N4OwTnudoGCvycL9BUF3XDEKAmEIl0UB0PH7Qg+nXcCGgjKARmBXzMnfA3CnNyGuDzGfs2Qbudwd6kIGVkVqq7s4OVNuox3FFcbX8lys2cEkhtgHXt7Drc87pNs45Fp/NF82hh5nrNUSEDcH1qy90L90uino9LZF8tnyagUP0YE0ArNtruGNL/gMm/d0e3bxx1KWzU4h2yIpuBu0RjTqBkWibszs67Epxuyun09qOztKzXLdVfJG5sofwSNdE0sKZGUGgm6YwsMJGRUpgmhSk4c=
    username: AgDxYznj/+/2ZEqfp98QoymdPJ9wnmF46xbRsnXkqBEDwoq7D/extLCiJ6lQfmuwV0ihaNQArw1nUvgdUrpPlbTfEPL6VUIDYqJJZSgh4OrLY5270+0CxyHXX9vlkR0q+p5TLLIzzJl8WMAO9xGKdjSqlLRbPJ4STi3PSt5NvjqiAM8wVeKyo6kEWYhVIKDcV2sLReBu0Xi19xGZgB0pOaz7oTEu0Z0j1O9KZxYW4Qu8dUYT7yOnvh2NDpLA6ubXdLDG5YdMywzVYeRVT85VWshjMgMymvu9bCeBKYsTEjCRsIWmYB6w4Irk+XcJExHHvs6oTf4RNlcfSsvoic0afJIXpi/ypNXU9WH4TcIZGgEpvpZFnhn+UVwk8gM2oXklQNmsoJ6Hx8XTxrugSrDOHbsEHmGBQqQPHN1i6SmpBImooDMv2CMA2uRN0NLw9Lz717xyHvpJgCYTSkGqTRmd5dQ8lY6Vx11hjRK3+JwaqZv7Wg2BydythOJThgFLTr39hXJ37GxW/wKmC10JCyz20yfCat83gEBSP5tjXKr92y6zzX/x4Sl9vkYTLv/toKHDZ0aD9Fu2rKbR7DRiwWGjmh6/7PuMKlLZ3odGIdhxsEjqOS94kGrYJr9f0HHNHiZQNAAJ77HPFN5L90wU4ysZy348scfdtqXRqKSrrncqI+c4C4Kbxqt8IvWMgjmlVbf/2b/pc24yfA==
  template:
    metadata:
      creationTimestamp: null
      name: resource-catalogue-secret
      namespace: rm
