---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: resource-catalogue-secret
  namespace: rm
spec:
  encryptedData:
    password: AgBkm+5/Dtd1kPjMnHQTab3EdL7jKmRssApywniMyYmBAfOHsf8D6kMvKA1Uuppm29MIwMuwCXNfG8rp6hL86lydFo7b0ehyh64vka6Ujtaa5hvOWcSpfp4GyBOveOzA7uy06r4kVIFaS/NP400fpN9eoKTXlDqz4q9bSMH12J75LNgbz8r/0Dwk2pj/0frH/EU2o6GvOdsezKgHWFkSYz2k//Ij7++1eY/kmHaeQvR4nONcM3tktTQJ2ICjM9c9OdQhLDd2NgJSp17lxBUCCKQe94xGDHORYup1KoyzxOb8ZkdNArbVkb+xWz1BaYEPq/SlCEDHOIvdLx07FBkXUE/IpwSPnoGvoQAD3f5HVerb8FmdJaKpjMF4d5VT+MIaiq/lR5uuC0H3L4oe2bt9SKiOGQyqBn4xxFNXGbeNXqFewffae3+IcWkPdfnze9TEVxZmanXDxtSXQOG4+/Yj8hW8JgqmkQrayT6SMihxYkMikhW4j08sUZ80/H3I5fQzKmUFxc1o5XGhOPv0823s6l1IvJqI//BPJBKODPllUffIRbKXzpEIGtT337UaXWl+wX2S2XhE7d2ieg4cwceEN/cNWfwTikF0F/mWCjOFjod+BLaP51MogdxzO3QRHDctDCSl97Exiq1S0OOK8CRHpYtVwFdWHewdJXR3gEBZj3elCLvJMlcps5wfaukYvYdPAyUC4A7kF4Qf+SXJtL7PFxDon4q/J888Kxc=
    username: AgC1r/GLh77gNwLnW9DqFgzmLRAbBUN6YeWG4t2DaTdEyJyBCE30zfS4qOxtHAs/eYAyyWNkf10g4SdspoTATFqIgE94+xlwbg9o8q2AHBKDvVfrHaA9RA9rR4KlWMRH2b9/3Czm8Py37fNaQ/pYGJ4+IZHpu1NeeZKyonE5BxXDTVtcxSkXUuBPykTo23TBaR3Y7suiiLMyX2R7kqc2EQOWMUfHK6hOu7C8RH4N6xSDF7qjS2ten4cun7YdvtTbs/DZwRLPSBVVD9h7Z0/2m88g4ED+qdVtMBrrwh2wz49a6Bugxwtszr63v/tVzzo4bQIfBLh5+TgoeVkomjCEvZ29Bb+ZzXoMSvBAv1GMLWVC5SHjXhxmibYCZ/Tu4AGWTWHjFaMzFS3mkYhKMxtQp1N1UpHHgZ2zpNiTKuoHLREXLel+sNJWkScUTiQ7V5lZM64Lk8tfXEvyj/8suDSR6Gpe4Rxp3n3hGvPGe6syylwMxALE8V9tHfMaffWug4rb7pybGgYuY0IqBwLf3KEJlJ1TMR+feLeDz8kdimN4T3NeuZjCi+3IHEwxqhuMZAozaH4Eno2wGlQXJZ+rlXSLgkGRCS6+rZ1WwLV7Gh4SkqxARckpAYy8RyVzB3oqoygjc427LQRQb4UsYSS/YlUrxBM9Ax8oq5rUbNbpnYE95tNapFtSIoV5pWO0g6i2/b2EqM7IQCQ0Gw==
  template:
    metadata:
      creationTimestamp: null
      name: resource-catalogue-secret
      namespace: rm
