apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-catalogue
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: 'https://eoepca.github.io/helm-charts'
    chart: rm-resource-catalogue
    targetRevision: 1.4.0

    helm:
      releaseName: resource-catalogue
      valuesObject:
        global:
          namespace: rm
        ingress:
          enabled: true
          name: resource-catalogue
          host: resource-catalogue.guide.svc.rconway.uk
          tls_host: resource-catalogue.guide.svc.rconway.uk
          tls_secret_name: resource-catalogue-tls
          annotations:
            kubernetes.io/ingress.class: nginx
            ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-production
        db:
          volume_storage_type: standard
        pycsw:
          # image:
          #   # repository: geopython/pycsw
          #   tag: "eoepca-staging"
          #   pullPolicy: Always
          config:
            server:
              url: https://resource-catalogue.guide.svc.rconway.uk/
            manager:
              transactions: "true"
              allowed_ips: "*"

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
