
resources:
  - resource-catalogue
  - registration-api
  - data-access
  - datacube-access
  # - zoo-dru
  # - zoo-dru-wes
  - zoo-dru-std
  # - zoo-dru-keda
  - workspace
  # - mlops
  - application-quality
  # - portal-v1x
  - registration-harvester
  - iam
  - application-hub
  # - operations
  # - resource-health
  # - openeo-geotrellis
  # - openeo-web-editor
  # - openeofed
  # - openeo-argoworkflows
  # - notification-automation
  # - identity-service


patches:
  - target:
      kind: Application
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "0"
  - target:
      group: apisix.apache.org
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "2"
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true