global:
  storageClass: managed-nfs-storage-retain
#gateway:
#  type: LoadBalancer
#  tls:
#    enabled: true
#    containerPort: 443
etcd:
  persistence:
    storageClass: managed-nfs-storage-retain
    size: 8Gi
apisix:
  deployment:
    mode: decoupled
    role: "data_plane"
ingress-controller:
  enabled: true
  gateway:
    type: NodePort
    tls:
      enabled: true
#      containerPort: 443
  config:
    apisix:
      serviceName: iam-apisix-admin
      serviceNamespace: iam
ingress:
  enabled: true
  # -- (number) Service port to send traffic. Defaults to `service.http.servicePort`.
  servicePort:
  # -- Ingress annotations
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: iam.develop.eoepca.org
      paths:
        - /
    - host: iam-auth.develop.eoepca.org
      paths:
        - /
    - host: iam-test.develop.eoepca.org
      paths:
        - /
  tls:
    - hosts:
        - iam.develop.eoepca.org
      secretName: iam-cert
    - hosts:
        - iam-auth.develop.eoepca.org
      secretName: iam-auth-cert
    - hosts:
        - iam-test.develop.eoepca.org
      secretName: iam-test-cert
