global:
  storageClass: managed-nfs-storage-retain
gateway:
  tls:
    enabled: true
    containerPort: 443
#ingress:
#  enabled: true
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceName: iam-apisix-admin
      serviceNamespace: iam
# TODO: Maybe add the following if necessary
#pluginAttrs:
#  redirect:
#    https_port: 443
