# Note: This file is *not* used if Identity API is installed via the iam-bb
# Helm chart. Values are taken from iam-values.yaml instead in this case.

# Note: Only identity-api is installed.
# All other services are disabled.

identity-postgres:
  enabled: false
identity-keycloak:
  enabled: false
identity-api:
  enabled: true
  secrets:
    # Values for secret 'identity-api'
    # Note - if omitted, these can instead be set by creating the secret independently
    # e.g. as a SealedSecret via GitOps.
    #adminPassword: "changeme"
  deployment:
    # Config values that can be passed via env vars
    extraEnv:
      - name: AUTH_SERVER_URL  # see configMap.authServerUrl instead
        #value: https://iam-auth.rke2.deploybox.co.uk
        value: http://iam-keycloak.iam.svc.cluster.local
        # value: http://keycloak.iam.svc.cluster.local
      - name: ADMIN_USERNAME
        value: "identity-api"
      - name: REALM
        value: "eoepca"
      # - name: VERSION
      #   value: v1.0.0
      - name: LOG_LEVEL
        value: DEBUG
identity-gatekeeper:
  enabled: false
