apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: na-kafka-operator
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: 'https://strimzi.io/charts/'
    chart: strimzi-kafka-operator
    targetRevision: 0.8.2
    helm:
      releaseName: strimzi-kafka-operator
  destination:
    name: in-cluster
    namespace: strimzi-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
