resources:
  - app-crossplane-core.yaml
  - mrap.yaml
  - deploymentRuntimeConfigs.yaml
  - providers.yaml
  - providerConfigs.yaml
  - ss-keycloak-secret.yaml
  - ss-minio-secret.yaml
  - functions.yaml
  - rbac.yaml
