resources:
  - namespace-workspace.yaml
  - app-crossplane-core.yaml
  - mrap.yaml
  - deploymentRuntimeConfigs.yaml
  - providers.yaml
  - providerConfigs.yaml
  - functions.yaml
  - rbac.yaml

patches:
  - target:
      version: v1
      kind: Namespace
      name: ^(workspace|data-access|operations)$
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: crossplane-providerconfig-namespaces
        annotations:
          argocd.argoproj.io/sync-wave: "-20"
