---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: workspace
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  encryptedData:
    credentials: AgA7oXTua6Hrnp9Kd99YC9blMPIr7LNZdvA3BACmOTKfi0Zcl9xmIBg/bAIv1QZA29lPdn/K+Im7cCFt4wuZsg+GQSXBLJnb26Ee0LenF8ztUTttpw+28oEJg6Cckp8iaiMfYBcd/XuFT5aHRR6pQUnuz4Or2yPHDByH1HW7L0ACCJjAqgOKAH3N13SoMrnSRULC+ye+jxN2q54QjPOIntesFzcP2ojAHZTZ7T1F4udmpNvpooOAHq/Xg6QjWeGLnlugLhCyxpJzcInH7EjKtvtX4M1/6f9jExsF0LKpzh55Ou9StjU9nIYBqC3CLD841Un6Jr7O0D6FE+/GgWoz2F7aNbjZPhAaxcd+fAs/ZxlK88qRGG+TY6YcEgCRShMSokY5gWyLRT+ASHAO2nBW7zKqcsBBYqvgc2dFnr3Ch0sTc630uJlS0Tl4XxScBkbZC91+mqAJNdlBTOEidDyV4YvfOVjoojUoPkxGebtVRB9IF8+Kye4oBD41SAtDH/MBeZsyvJFlE7Cb34iuK3S4JcVAC1OA7liSS9ipOnPfLhEEy5M3gdlrYAlfHTsmwu2MHfvoGZSS6nGbXzjNXsXoLLVZS4kbRJuRvNG1w+j+4zFYr5w8TpmaJ9CTpqEr1DJVxP9WJaWcv7+QzzyQofdYdwfh88APlzSsHLNZptPWTaKx2/7UIvB3s4vIyuoi9KxOtWF/sckwknCuXrv24Jmh9ngE8p/XXpMD2Ea/IB6svmy+/TZmjeEWTu06KNjqmnePkCCTai7te0lAXksE63RDa8fVJnWqd8qdUw4SzJumJzicDPg3/hD4YwxprB/QAwQjyBqddlYmbvlHm9RLuBq/80yERQuLoRqkuEFaZY1GCN7QefsrTD7UHTIOm0nqfsg7wZdQ5Rt57uA4g09fjT8QucN1S8YRFxWAnXynYZIy/mln2ioXYur0cXMbpLLmsFJDdR95hlBtdgVQEHZ95J46LA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: workspace
    type: Opaque
