---
# Credentials for provider-minio's ProviderConfig, in the AWS_ACCESS_KEY_ID /
# AWS_SECRET_ACCESS_KEY format it expects. Values must match the minio-auth
# rootUser/rootPassword sealed secret in argocd/infra/minio/parts.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: workspace
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBiEzaxs+PpN5whKI/QcsvVaraZarKqP52LL5MKVpYVDqfJEQiT9OZuT2wbuTY1t7SnjTVPqUFATYBZbHy7BIrr8PUH+JV9OEnokBn8TjsRpv3z8rn0ZeawZPy/xjjU1lv6H7eC+dV4CzCDoJBEf5ifo4uIzJoA6lJaB7/L9WTjzh0hk6DOKjqELRWphxlLY5+OTIQrVWcGW5Kni7CpZGEVvmnND2NS316B+EuYN+sZeS/R87caFaQTztyMWjjJa5t2LbOAb/9pINqsN7QetARYd5am51F4yKRr2HN8wbn5RQk5NwkUgUfTLFjBYtPU8mZQle17OFlWH/GDKZQq6U0Bezp19EK9Ceu9Stzz2QowCcUKTdSOzc/v9dDsRi11DVwq+v5ea1E1U/+nPLXDe6ZnIZ6vFfPMpenI9cjBjK05HcHhFE3wkibNVPUGyzw+tWtRt7chNy6uAytft/e44Zi12pLejikGhQyAeYsnm9fi7mWzLT8AHE4PPmg67us+nORmItZV+3AGxl4RpaOhEOAhdRm0236fg/RlPA+m0QTN8Ic/wpph14KdwJQiuqRszyXxlMY80sJPP6IkFH22bOV20N1TlTrLGFJdfjvyGlvLI+qaatzzMq7YgoVFtnn72ceCPKuT5FCYm0GRot2yJ/Baw85CFCH/clJAxYsSfQzt6w71M//D4/QYk3LAq9sDgbvz3iZMPK0=
    AWS_SECRET_ACCESS_KEY: AgClCVG1q7JapYZoubj1Bo52t/NQfU6hG7p1gVJJU8Xr/7zRaMpjLcqBZnsJEbkVMGb7gimlPPqd+r5yweO8K4gjtVtYnfCy7t5Tmv9pWlKosAKz4r0WNiTfhsMm0+UqyP8Fq3HOuiq2auhxxPSAW901TQvjbptrzoGy4igDAMX50jINsE7lv7Jcegy/aP3B+QGaracYmNI6fmoah7q7iZ/6afv+wEQYX5YccXQs1K59aj93BvIUXBkOl/cvNI0LABwYMk7BzrNYOSCdBIg1ncqQ2da0VBCEYagNdR+bDkjJLRmLmP1wb3VKOzj9gLHseVvB+Hym5Fg+7eqIpuSMI6uh+vk5viezGqoYL+5Q2bqYPlEVzVwHHuYBx6wesHjTCKUFl2nTbtn6Una27Ft+sV3AGVlh7JWyT/j4sswyUgUTm15SrgHGklOvV7QDqF1G+iSyfueIuJhQvrIlxZqTOGzpVtQFU4F/UnCTIQgm0YLsusl+c3iCTP2P5VYqE337X67+/W5JrotyUoqtz1ykCXbhFZ6upwIH7yNXuMy8oaZiMT67G2G15sebWYHbUrDD92fvYoZF0tdOMaiYNj9ZsI9QfuyGpwik/37nHC+WIa3PyqzNriTeCMgDnB2i0R8rdNqUXttGnUxPnu6RQMl6TFNqi3k7cRzwyfIonpLIDrMU6cW0+DcJ/aO0x8xTT60IjYeK2uDabSmxJw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: workspace
