apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: deploy-james
    path: argocd/base/eoepca/data-access

    helm:
      releaseName: data-access
      valueFiles:
        - values-core.yaml
        - values-creodias-data.yaml
        - values-harvester.yaml
      parameters:
        - name: data-access.global.ingress.hosts[0].host
          value: data-access.develop.eoepca.org
        - name: data-access.global.ingress.tls[0].hosts[0]
          value: data-access.develop.eoepca.org

        - name: data-access.global.env.AWS_ENDPOINT_URL_S3
          value: https://minio.develop.eoepca.org
        - name: data-access.global.env.CREODIAS_EODATA_S3_ENDPOINT
          value: http://eodata.cloudferro.com
        - name: data-access.global.storage.cache.host
          value: minio.develop.eoepca.org
        - name: data-access.vs.registrar.config.defaultBackends[0].kwargs.ows_url
          value: https://data-access.develop.eoepca.org/ows


  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
