apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-access
  namespace: argocd
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: deploy-james
    path: argocd/base/eoepca/data-access

    helm:
      releaseName: data-access
      valueFiles:
        - values-core.yaml
        - values-creodias-data.yaml
        - values-harvester.yaml
      valuesMerge: override
      valuesInline:
        - |
          data-access:
            global:
              ingress:
                hosts:
                  - host: james-test-override.develop.eoepca.org
                tls:
                  - hosts:
                      - james-test-override.develop.eoepca.org

  destination:
    name: in-cluster
    namespace: rm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
