# Copied from Workspace and adapted

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: iam
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: rke2-argocd-sync-wave
    path: argocd/eoepca/iam/parts
  destination:
    name: in-cluster
    namespace: iam
  ignoreDifferences:
    - group: "openidclient.keycloak.m.crossplane.io"
      kind: Client
      name: eoepca-realm-management-client
      namespace: iam-management
      jsonPointers:
        - /metadata/annotations/crossplane.io~1external-name
    - group: "role.keycloak.m.crossplane.io"
      kind: Role
      name: eoepca-realm-admin
      namespace: iam-management
      jsonPointers:
        - /metadata/annotations/crossplane.io~1external-name
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
