#!/usr/bin/bash
ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"
onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT
source .env 2>/dev/null
SECRET_NAME="keycloak-provider"
PROVIDER_CLIENT_SECRET="${1:-${PROVIDER_CLIENT_SECRET:-changeme}}"
PROVIDER_CLIENT_ID="${2:-${PROVIDER_CLIENT_ID:-crossplane-keycloak-provider}}"
KEYCLOAK_URL=${3:-${KEYCLOAK_URL:-https://iam-auth.rke2.deploybox.co.uk}}
CREDENTIALS="`cat <<EOF
{
  "client_id": "$PROVIDER_CLIENT_ID",
  "client_secret": "$PROVIDER_CLIENT_SECRET",
  "url": "$KEYCLOAK_URL",
  "base_path": "",
  "realm": "eoepca"
}
EOF`"

sealFor() {
  local ns="$1"
  local outfile="$2"
  kubectl -n "${ns}" create secret generic "${SECRET_NAME}" \
    --from-literal="credentials=${CREDENTIALS}" \
    --from-literal="client_secret=${PROVIDER_CLIENT_SECRET}" \
    --dry-run=client -o yaml \
  | kubeseal -o yaml --controller-name sealed-secrets --controller-namespace infra > "${outfile}"
}
# Maybe add the following entries above if needed:
#    --from-literal="client_id=${PROVIDER_CLIENT_ID}" \
#    --from-literal="base_path=" \
#    --from-literal="realm=eoepca" \
#    --from-literal="url=${KEYCLOAK_URL}" \

# Note: Currently the secret is propagated to the iam-management ns
# through an external secret generated by the Helm chart.
#sealFor "iam-management" "parts/ss-${SECRET_NAME}.yaml"
sealFor "iam" "parts/ss-${SECRET_NAME}-iam.yaml"