
resources:
  - app-harbor-server.yaml
  - ingress-plugin.yaml
  - ss-harbor-auth.yaml

patches:
  - target:
      group: bitnami.com
      kind: SealedSecret
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-10"
  - target:
      group: argoproj.io
      kind: Application
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "0"
