apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-health
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: resource-health
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: deploy-develop
    path: argocd/eoepca/resource-health/parts
  destination:
    name: in-cluster
    namespace: resource-health
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: v1.35
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: v1.35
        security.eoepca.org/pod-security-exception-required: "true"
      annotations:
        security.eoepca.org/pod-security-exception-reason: >-
          The OpenSearch sysctl init container currently requires privileged access.
        security.eoepca.org/pod-security-remediation: >-
          Configure the required sysctl on the hosts and disable the privileged init container.
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
