apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-health
  namespace: argocd
spec:
  project: eoepca
  source:
    repoURL: 'https://github.com/EOEPCA/resource-health'
    path: resource-health-reference-deployment
    targetRevision: deploy-develop
    helm:
      valuesObject:
        global:
          defaultInternalIssuerRef:
            name: eoepca-ca-clusterissuer

        ## Example health checks to deploy with the resource health BB itself
        resource-health:
          healthchecks:
            checks:
            - name: hourly-mockapi-check
              image:
                repository: docker.io/eoepca/healthcheck_runner
                pullPolicy: IfNotPresent
                tag: "v0.1.0-demo"
              schedule: "@hourly"
              requirements: "https://gist.githubusercontent.com/tilowiklundSensmetry/a9fefe2873b731b483f554607a82deaa/raw/1136a82ca3c8f28b1ad4d895871514185927dd1c/requirements.txt"
              script: "https://raw.githubusercontent.com/EOEPCA/resource-health/refs/tags/v0.1.0-demo/pytest-health/instrumentation/examples/mock_api_check.py"
              userid: alice
              env:
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: https://resource-health-opentelemetry-collector:4317
                - name: MOCK_API_HOST
                  value: http://resource-health-mockapi:5000

            - name: daily-trivial-check
              image:
                repository: docker.io/eoepca/healthcheck_runner
                pullPolicy: IfNotPresent
                tag: "v0.1.0-demo"
              ## Every day at 08:00
              schedule: "0 8 * * *"
              requirements: "https://gist.githubusercontent.com/tilowiklundSensmetry/a9fefe2873b731b483f554607a82deaa/raw/1136a82ca3c8f28b1ad4d895871514185927dd1c/requirements.txt"
              script: "https://raw.githubusercontent.com/EOEPCA/resource-health/refs/tags/v0.1.0-demo/pytest-health/instrumentation/examples/trivial_check.py"
              userid: bob
              env:
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: https://resource-health-opentelemetry-collector:4317

  destination:
    namespace: resource-health
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
