apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-health
  namespace: argocd
spec:
  project: eoepca
  source:
    repoURL: 'https://github.com/EOEPCA/resource-health'
    path: resource-health-reference-deployment
    targetRevision: deploy-develop
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: resource-health
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
