apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keephq
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: keephq
spec:
  project: eoepca
  source:
    repoURL: https://github.com/EOEPCA/eoepca-plus
    targetRevision: deploy-develop
    path: argocd/infra/keephq/parts
  destination:
    name: in-cluster
    namespace: infra
  syncPolicy:
    automated:
      prune: false # never prune
      selfHeal: false # only manual sync
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
