apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: data-proxy
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: data-proxy-oidc
  forProvider:
    realmId: eoepca
    name: data-proxy
    accessType: PUBLIC
    clientId: data-proxy
    enabled: true
    standardFlowEnabled: false
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    fullScopeAllowed: true
    serviceAccountsEnabled: false
    useRefreshTokens: true
    rootUrl: https://eodag-api.rke2.deploybox.co.uk
    validRedirectUris: []
    validPostLogoutRedirectUris: []
    webOrigins: []
---
apiVersion: client.keycloak.m.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: data-proxy-audience-mapper
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    clientIdRef:
      name: data-proxy
      policy:
        resolution: Required
    realmId: eoepca
    protocol: openid-connect
    protocolMapper: oidc-audience-mapper
    name: data-proxy-audience
    config:
      "included.client.audience": "data-proxy"
      "access.token.claim": "true"
      "id.token.claim": "false"
