apiVersion: v1
data:
  config.yaml: |-
    services:
      github-opa:
        url: https://ghcr.io
        type: oci

    bundles:
      mybundle:
        service: github-opa
        resource: ghcr.io/eoepca/eoepca-plus/opa-bundle:latest
        polling:
          min_delay_seconds: 30
          max_delay_seconds: 60
kind: ConfigMap
metadata:
  name: opa-config
