apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: data-proxy
  namespace: data-proxy
spec:
  ingressClassName: apisix
  http:
    - name: stac-route
      websocket: true
      backends:
        - serviceName: eodag-stac-api-stac-fastapi-eodag
          servicePort: 8080
      match:
        hosts:
          - eodag-api.develop.eoepca.org
        paths:
          - /

    - name: proxy-route
      backends:
        - serviceName: eodag-data-proxy-eodag-data-proxy-chart-proxy
          servicePort: 8880
      match:
        hosts:
          - eodag-proxy.develop.eoepca.org
        paths:
          - /
