---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  creationTimestamp: null
  name: cs-container-pull
  namespace: data-proxy
spec:
  encryptedData:
    .dockerconfigjson: AgAcsvr+nzYSeNmeKpzEzyeRXx+KPda4d5GPv9TV5CcIPYgtg1q26mVPbFnrE/+4BpYXdBuchc7EeSH8mqmXp934AmUCGE0NiikixCat9BkV7Cmvo/CgHwd/qFC/qbOfdLukDf9pjeWY0vTmcpKSkN4lGqJDBvJzo3aC3BkcGS4eQPdDBcbqOYyoYVT8U1tRAVRm2bc+hhmOgU5BE6AczaOpIHxpWCxa7hfX/vBqtJ93S4ZEfIo+ul+vw8XThxP7ATAHTSPWI8MuyKnLREd4cEbzVMvdq0k3fMB0IH5qDgVyYlTEYdWXqQqYpFAzE7LmcBvLNByy+9KJtRvgwqUTd1GPBXKYT8D0j6zIlbbRpWQbrp/WwV4gWQEX7pO6fFYasNfTOU7gRvwX44yEMiEm1gwGGfWu/nAUkr4fuw6z/hghC2+YN391NUOosnQZb9z2O9npDf9iGdTTWYfE8Ap/6vujbbs0rWD4P8FgSHSDQsA0iZRR2gnrwr8Rd5mRJdFjNNAxajWRX3F+RnLdMyAIHXB+H87NMLoZ+aFD5HSCULr8yUBJHh5BBStOLaSJCBkqFC+W9anpHCBq+rDONyQTanRRuCs/Nj9dBWNyhae5NGM5kOqzGaJB/CAGZOqTW5mEZDqc+YMnVsHEBbEYr/SISCxA/jx1gPh62BfiPY1i+qls11Dcsv+pgJ9r1EKf+Mmtjt174irhGtGHpk207fbb8DTBxEaOGsuA6HIZSOy9GX76mXOTqAvIg5HVLxUXEA3pIWI4XErPnDF5xW0PbaQqIYCIkiXAswxwYCutzEbe8Nl0EvFLTG+Haq5RRNJlpcwCkpwSasGx2oLQhSKQY0DHlm/wNCL5oVIj7jef/Ve12zF7zrkLf6sWXzRKqMGflxRc+xiH7JBGS5IDJ89VcfJ/8820bhgf8KeRGRkhO69NcvaIJ96dRviie97u6AKaRamM+6tW6h7HKJS6XmSR7MV8LOjpQvnhFMQfHYkBZJOpGgVv4K2jx/QPhPRwf/NYNQA1qZLHRgkCuYvRELeJRC7ubQ==
  template:
    metadata:
      creationTimestamp: null
      name: cs-container-pull
      namespace: data-proxy
    type: kubernetes.io/dockerconfigjson
