apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-ca
  namespace: argocd
  labels:
    eoepca/app-name: step-ca
spec:
  project: eoepca
  source:
    repoURL: https://smallstep.github.io/helm-charts
    chart: step-certificates
    targetRevision: 1.26.2
    helm:
      values: |
        ca:
          db:
            persistent: true
            storageClass: "managed-nfs-storage-retain"
            size: "10Gi"
            accessModes:
              - ReadWriteOnce
  destination:
    name: in-cluster
    namespace: cert-manager-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
