apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
spec:
  selector:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns
    k8s-app: kube-dns
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 53
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
