
resources:
  - app-sealed-secrets.yaml
  - cert-manager
  - harbor
  - minio
  - knative-operator
  - strimzi-operator
  - apisix
  - pgo
  - mongodb-operator
  - redis-operator
  - gateway
  - eso
  - crossplane
  - trivy
