apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: monitoring
  namespace: infra
spec:
  ingressClassName: apisix
  http:
    - name: grafana
      match:
        hosts:
          - monitoring.develop.eoepca.org
        paths:
          - /
          - /*
      backends:
        - serviceName: kube-prometheus-stack-grafana
          servicePort: 80