apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-server
  namespace: argocd
  labels:
    eoepca/app-name: minio
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.7

    helm:
      releaseName: minio
      valuesObject:
        existingSecret: minio-auth
        replicas: 2
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
          path: /
          hosts:
            - minio.develop.eoepca.org
          tls:
            - secretName: minio-tls
              hosts:
                - minio.develop.eoepca.org
        consoleIngress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
          path: /
          hosts:
            - console.minio.develop.eoepca.org
          tls:
          - secretName: minio-console-tls
            hosts:
              - console.minio.develop.eoepca.org
        resources:
          requests:
            memory: 1Gi
        persistence:
          storageClass: standard
          size: 50Gi
        buckets:
          - name: eoepca
          - name: cache-bucket
          - name: gitlab-backup-storage
          - name: gitlab-tmp-storage

  destination:
    name: in-cluster
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
