apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-server
  namespace: argocd
  labels:
    eoepca/app-name: minio
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0

    helm:
      releaseName: minio
      valuesObject:
        existingSecret: minio-auth
        replicas: 2
        clusterDomain: cluster.local
        ingress:
          enabled: true
          ingressClassName: apisix
          annotations:
            k8s.apisix.apache.org/enable-websocket: "true"
            apisix.apache.org/ssl-redirect: "true"
            apisix.ingress.kubernetes.io/use-regex: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-http01-apisix"
            k8s.apisix.apache.org/enable-cors: "true"
            k8s.apisix.apache.org/upstream-read-timeout: "600s"
            argocd.argoproj.io/ignore-healthcheck: "true"
            k8s.apisix.apache.org/plugin-config-name: "minio-ingress"
          path: /
          hosts:
            - minio.develop.eoepca.org
          tls:
            - secretName: minio-tls
              hosts:
                - minio.develop.eoepca.org
        consoleIngress:
          enabled: true
          ingressClassName: apisix
          annotations:
            k8s.apisix.apache.org/enable-websocket: "true"
            apisix.apache.org/ssl-redirect: "true"
            apisix.ingress.kubernetes.io/use-regex: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-http01-apisix"
            k8s.apisix.apache.org/enable-cors: "true"
            k8s.apisix.apache.org/upstream-read-timeout: "600s"
            argocd.argoproj.io/ignore-healthcheck: "true"
            k8s.apisix.apache.org/plugin-config-name: "minio-ingress"
          path: /
          hosts:
            - console.minio.develop.eoepca.org
          tls:
          - secretName: minio-console-tls
            hosts:
              - console.minio.develop.eoepca.org
        resources:
          requests:
            memory: 1Gi
        persistence:
          storageClass: managed-nfs-storage-retain
          size: 50Gi
        buckets:
          - name: eoepca
          - name: cache-bucket
          - name: gitlab-backup-storage
          - name: gitlab-tmp-storage
          - name: gitlab-lfs-storage
          - name: mlopbb-mlflow-sharinghub
          - name: mlopbb-sharinghub
          - name: openeo-geotrellis-data

  destination:
    name: in-cluster
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
